force-app/main/default/objects/MUSW__Inspection__c/MUSW__Inspection__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Ensure work is done in compliance with rules and regulations</description>
    <label>Inspection</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Inspection__c/fields/Close_Inspection__c.field-meta.xml
<CustomField>
    <fullName>Close_Inspection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Close Inspection</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MUSW__Inspection__c/fields/Completed_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Completed_DateTime__c</fullName>
    <label>Completed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MUSW__Inspection__c/fields/Inspection_Chain_Closed__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Chain_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inspection Chain Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MUSW__Inspection__c/fields/Letter_Generated__c.field-meta.xml
<CustomField>
    <fullName>Letter_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Letter Generated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MUSW__Inspection__c/fields/MUSW__Closed_DateTime__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Closed_DateTime__c</fullName>
    <description>Optional. This can be used if inspection metrics are measured in hours rather than days.</description>
    <label>Closed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MUSW__Inspection__c/fields/MUSW__Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Completed_Date__c</fullName>
    <description>Date the inspection was completed.</description>
    <label>Completed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MUSW__Inspection__c/fields/MUSW__On_Itinerary__c.field-meta.xml
<CustomField>
    <fullName>MUSW__On_Itinerary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set to true on the itinerary page when an inspection is added to the itinerary and saved. This should be used in the creation of Views for the Itinerary page.</description>
    <label>On Itinerary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MUSW__Inspection__c/fields/MUSW__Previous_Inspection__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Previous_Inspection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is commonly used in configuration. If a reinspection is created via a DRE rule, it is a best practice to fill in the parent inspection lookup.</description>
    <label>Previous Inspection</label>
    <referenceTo>MUSW__Inspection__c</referenceTo>
    <relationshipLabel>Re-Inspections</relationshipLabel>
    <relationshipName>Next_Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Inspection__c/fields/MUSW__Priority__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Priority__c</fullName>
    <description>Can be used for sort order in views and reports.  Not used in any default configuration.</description>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3 High</fullName>
            </value>
            <value>
                <fullName>2 Normal</fullName>
                <default>true</default>
                <label>2 Normal</label>
            </value>
            <value>
                <fullName>1 Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Inspection__c/fields/MUSW__Scheduled_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Scheduled_Start_Date__c</fullName>
    <description>Date the inspection is scheduled for (usually before or by due date if not late). Used for views on the itinerary page.</description>
    <label>Scheduled Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MUSW__Inspection__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <description>Current status or outcome of the inspection.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Initialized Site Visit</fullName>
            </value>
            <value>
                <fullName>Pending Site Visit Report</fullName>
            </value>
            <value>
                <fullName>Pending Site Visit Review</fullName>
            </value>
            <value>
                <fullName>Requester Review</fullName>
            </value>
            <value>
                <fullName>Additional Review</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Inspection__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <description>Scope of the inspection activity to be done.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Building</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>Initial Inspection</fullName>
            </value>
            <value>
                <fullName>AG Permitting Site Verification Form</fullName>
            </value>
            <value>
                <fullName>Code Enforcement Inspection</fullName>
            </value>
            <value>
                <fullName>Codes / Zoning</fullName>
            </value>
            <value>
                <fullName>Farmer Initiated Online Request</fullName>
            </value>
            <value>
                <fullName>Permit Inspection</fullName>
            </value>
            <value>
                <fullName>Site Visit Request</fullName>
            </value>
            <value>
                <fullName>WWSA Inspection</fullName>
            </value>
            <value>
                <fullName>Site Visit Report</fullName>
            </value>
            <value>
                <fullName>Groundwater Withdrawal Information</fullName>
            </value>
            <value>
                <fullName>Surface Water Withdrawal Information</fullName>
            </value>
            <value>
                <fullName>Meter &amp; Telemetry Information</fullName>
            </value>
            <value>
                <fullName>Well Construction Inspection</fullName>
            </value>
            <value>
                <fullName>Well Plug and Abandon Inspection</fullName>
            </value>
            <value>
                <fullName>Ag Site Inspection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Inspection__c/fields/Pass_Fail__c.field-meta.xml
<CustomField>
    <fullName>Pass_Fail__c</fullName>
    <formula>CASE( MUSW__Status__c, 

&quot;Failed&quot;,&quot;Failed&quot;, 
&quot;Passed&quot;,&quot;Passed&quot;, 
&quot;Stop Work&quot;,&quot;Failed&quot;, 
&quot;Closed&quot;,&quot;Passed&quot;, 

&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pass/Fail</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__Inspection__c/fields/Requested_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Requested_DateTime__c</fullName>
    <label>Requested Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/InspectionUpdateParentTriggerTest.cls
@isTest(SeeAllData = true)
public class InspectionUpdateParentTriggerTest{


    public static testMethod void testCreateReinspectionFromIV(){
    
        MUSW__Inspection__c preIns = new MUSW__Inspection__c();
                
        preIns.Name = 'asfsdafsda';
        preIns.MUSW__Type__c = 'Mechanical';
        preIns.MUSW__Priority__c= '2 Normal';
        preIns.MUSW__Status__c = 'failed';
        preIns.Close_Inspection__c = false;
        preIns.MUSW__On_Itinerary__c = false;
        preIns.Letter_Generated__c = false;
        preIns.MUSW__Scheduled_Start_Date__c = date.today();
        preIns.Requested_DateTime__c = date.today();
        preIns.Completed_DateTime__c = date.today();
        preIns.MUSW__Completed_Date__c = date.today();
        preIns.MUSW__Closed_DateTime__c = date.today();
        preIns.Inspection_Chain_Closed__c = false;
        preIns.MUSW__Previous_Inspection__c = null;
        insert preIns;   
        
             

        MUSW__Inspection__c ins = new MUSW__Inspection__c();
                
        ins.Name = 'hot123';
        ins.MUSW__Type__c = 'Mechanical';
        ins.MUSW__Priority__c= '2 Normal';
        ins.MUSW__Status__c = 'failed';
        ins.Close_Inspection__c = false;
        ins.MUSW__On_Itinerary__c = false;
        ins.Letter_Generated__c = false;
        ins.MUSW__Scheduled_Start_Date__c = null;
        ins.Requested_DateTime__c = date.today();
        ins.Completed_DateTime__c = date.today();
        ins.MUSW__Completed_Date__c = date.today();
        ins.MUSW__Closed_DateTime__c = date.today();
        ins.Inspection_Chain_Closed__c = false;
        ins.MUSW__Previous_Inspection__c = preIns.id;
        
        
        insert ins;


        MUSW__Inspection__c nextIns = new MUSW__Inspection__c();
                
        nextIns.Name = 'tgrahgdsadfsdg';
        nextIns.MUSW__Type__c = 'Mechanical';
        nextIns.MUSW__Priority__c= '2 Normal';
        nextIns.MUSW__Status__c = 'Pending';
        nextIns.Close_Inspection__c = false;
        nextIns.MUSW__On_Itinerary__c = false;
        nextIns.Letter_Generated__c = false;
        nextIns.MUSW__Scheduled_Start_Date__c = null;
        nextIns.Requested_DateTime__c = null;
        nextIns.Completed_DateTime__c = null;
        nextIns.MUSW__Completed_Date__c = null;
        nextIns.MUSW__Closed_DateTime__c = null;
        nextIns.Inspection_Chain_Closed__c = false;
        nextIns.MUSW__Previous_Inspection__c = ins.id;
        //ins.Pass_Fail__c == 'Passed';
        
        insert nextIns;
        nextIns.MUSW__Status__c = 'passed';
        nextIns.Inspection_Chain_Closed__c = true;
        update nextIns;
        
        ins.Inspection_Chain_Closed__c = true;
        
        update ins;
        
        preIns.Inspection_Chain_Closed__c = true;
        
        update preIns;
        
        
        /*
        

        MUSW__Inspection__c updateIns = [select id, Name, MUSW__Type__c, MUSW__Priority__c, MUSW__Status__c, Close_Inspection__c, 
                                            MUSW__On_Itinerary__c, Letter_Generated__c, MUSW__Scheduled_Start_Date__c, Requested_DateTime__c , 
                                            Completed_DateTime__c, MUSW__Closed_DateTime__c,  Inspection_Chain_Closed__c, MUSW__Previous_Inspection__c  from MUSW__Inspection__c  where Name ='hot123' limit 1 ];


        updateIns.Name = 'abc';
        nextIns.MUSW__Status__c = 'Passed';
        update updateIns ;
       
       MUSW__Inspection__c updatePreIns = [select id, Name, MUSW__Type__c, MUSW__Priority__c, MUSW__Status__c, Close_Inspection__c, 
                                            MUSW__On_Itinerary__c, Letter_Generated__c, MUSW__Scheduled_Start_Date__c, Requested_DateTime__c , 
                                            Completed_DateTime__c, MUSW__Closed_DateTime__c,  Inspection_Chain_Closed__c, MUSW__Previous_Inspection__c  from MUSW__Inspection__c  where Name ='asfsdafsda' limit 1 ];

        
        
        update updatePreIns ;
        
    */
    }  


}