force-app/main/default/objects/MUSW__Inspection__c/MUSW__Inspection__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Ensure work is done in compliance with rules and regulations</description>
    <label>Inspection</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Inspection__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <description>Current status or outcome of the inspection.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Initialized Site Visit</fullName>
            </value>
            <value>
                <fullName>Pending Site Visit Report</fullName>
            </value>
            <value>
                <fullName>Pending Site Visit Review</fullName>
            </value>
            <value>
                <fullName>Requester Review</fullName>
            </value>
            <value>
                <fullName>Additional Review</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AvoInspectionTriggerHandler.cls
/**
 * Description of class
 * trigger proxy for inspections
 * @author Jason Li
 * last modified by Jason Li
 * @date 06/28/2021
 *  
 */
public class AvoInspectionTriggerHandler extends AvoTriggerHandler { 
    
    public override void afterUpdate() {
        for(MUSW__Inspection__c inspection : (List<MUSW__Inspection__c>) Trigger.new) { 

            MUSW__Inspection__c oldInspection = (MUSW__Inspection__c)Trigger.oldMap.get(inspection.Id);
            // trigger the process engine only if the inspection result has changed.
            if (inspection.MUSW__Status__c != null && oldInspection.MUSW__Status__c != inspection.MUSW__Status__c){
            	AvoProcessEngineInspection avoProcessEngineInspection = new AvoProcessEngineInspection(inspection);
            	avoProcessEngineInspection.run(); 
            }
        }


    }
}