force-app/main/default/objects/MUSW__Inspection__c/MUSW__Inspection__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Ensure work is done in compliance with rules and regulations</description>
    <label>Inspection</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Inspection__c/fields/Close_Inspection__c.field-meta.xml
<CustomField>
    <fullName>Close_Inspection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Close Inspection</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MUSW__Inspection__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <description>Current status or outcome of the inspection.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Initialized Site Visit</fullName>
            </value>
            <value>
                <fullName>Pending Site Visit Report</fullName>
            </value>
            <value>
                <fullName>Pending Site Visit Review</fullName>
            </value>
            <value>
                <fullName>Requester Review</fullName>
            </value>
            <value>
                <fullName>Additional Review</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Inspection_Violation__c/MUSW__Inspection_Violation__c.object-meta.xml
<CustomObject>
    <label>Inspection Violation</label>
    <nameField>
        <displayFormat>IV-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspection Violations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Inspection_Violation__c/fields/MUSW__Inspection__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Inspection__c</fullName>
    <description>Associated Inspection (required). This allows multiple violations to be recorded per inspection.</description>
    <label>Inspection</label>
    <referenceTo>MUSW__Inspection__c</referenceTo>
    <relationshipLabel>Violations</relationshipLabel>
    <relationshipName>Inspection_Violations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ViolationAddEditBatch.cls
public class ViolationAddEditBatch implements Database.Batchable<MUSW__Inspection_Violation__c>, Database.Stateful
{
    public String error;
    private MUSW__Inspection__c ins;
    private MUSW__Inspection__c[] fieldObservations;
    private MUSW__Inspection_Violation__c[] ivs;
    
    public ViolationAddEditBatch(MUSW__Inspection__c ins, MUSW__Inspection__c[] fos, MUSW__Inspection_Violation__c[] ivs)
    {
        this.ivs = ivs;
        this.ins = ins;
        this.fieldObservations = fos;
    }
    
    public Iterable<MUSW__Inspection_Violation__c> start(Database.BatchableContext bc)
    { 
        return ivs;
    }
    
    public void execute(Database.BatchableContext bc, List<MUSW__Inspection_Violation__c> scopedIvs)
    {
        system.debug('scopedIvs=' + scopedIvs);
        update scopedIvs;
    }
    
    public void finish(Database.BatchableContext bc)
    {
        // coming from Inspection
        // update to run DRE
        if (ins != null)
        {
            ins.Close_Inspection__c = true;
            update ins;
        }
        
        // coming from Permit/Parcel
        // update to run DRE (cannot do on insert because DRE is blocked & rules need IV's)
        if (fieldObservations.size() > 0)
        {
            for (MUSW__Inspection__c foins : fieldObservations)
            {
                foins.Close_Inspection__c = true;
                foins.MUSW__Status__c = 'Completed with open violations';
            }
            System.debug('fieldObservations=' +fieldObservations );
            update fieldObservations;
        }
    }
    

    
}