force-app/main/default/objects/avo_Cybersource_Transaction__c/avo_Cybersource_Transaction__c.object-meta.xml
<CustomObject>
    <label>Cybersource Transaction</label>
    <nameField>
        <displayFormat>CT-{0000000}</displayFormat>
        <label>Cybersource Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cybersource Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/avo_Cybersource_Transaction__c/fields/Merchant_ID__c.field-meta.xml
<CustomField>
    <fullName>Merchant_ID__c</fullName>
    <label>Merchant ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/avo_Cybersource_Transaction__c/fields/Processor_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Processor_Transaction_Id__c</fullName>
    <label>Processor Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clariti__Cart__c/clariti__Cart__c.object-meta.xml
<CustomObject>
    <description>Cart is used to process the transaction for a collection of cart items</description>
    <label>Cart</label>
    <nameField>
        <displayFormat>C-{MM}{DD}{YYYY}-{000}</displayFormat>
        <label>Cart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clariti__Cart__c/fields/clariti__FailureReason__c.field-meta.xml
<CustomField>
    <fullName>clariti__FailureReason__c</fullName>
    <description>States the reason for failed status of cart.</description>
    <label>Failure Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/clariti__Cart__c/fields/clariti__Status__c.field-meta.xml
<CustomField>
    <fullName>clariti__Status__c</fullName>
    <description>Status of the cart.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/clariti__Payment__c/clariti__Payment__c.object-meta.xml
<CustomObject>
    <description>Payment is used to record the amount collected per payment method during the cart transaction</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{MM}{DD}{YYYY}-{000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clariti__Payment__c/fields/clariti__Cart__c.field-meta.xml
<CustomField>
    <fullName>clariti__Cart__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to cart associated to the the payment transaction.</description>
    <label>Cart</label>
    <referenceTo>clariti__Cart__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clariti__Payment__c/fields/clariti__MerchantId__c.field-meta.xml
<CustomField>
    <fullName>clariti__MerchantId__c</fullName>
    <label>Merchant Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/clariti__Payment__c/fields/clariti__Payment__c.field-meta.xml
<CustomField>
    <fullName>clariti__Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>clariti__Payment__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clariti__Payment__c/fields/clariti__PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>clariti__PaymentMethod__c</fullName>
    <description>Payment Method used to make the payment.</description>
    <label>Payment Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clariti__Payment__c/fields/clariti__Status__c.field-meta.xml
<CustomField>
    <fullName>clariti__Status__c</fullName>
    <description>Status of the payment transaction.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Initiated</fullName>
            </value>
            <value>
                <fullName>Partially Refunded</fullName>
            </value>
            <value>
                <fullName>Fully Refunded</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/clariti__Payment__c/fields/Processor_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Processor_Transaction_Id__c</fullName>
    <externalId>true</externalId>
    <label>Processor Transaction Id</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clariti__PaymentMethod__mdt/clariti__PaymentMethod__mdt.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <pluralLabel>Payment Methods</pluralLabel>
</CustomObject>

force-app/main/default/classes/CybersourcePaymentGateway.cls
public with sharing class CybersourcePaymentGateway {
    public static final String CYBER_SOURCE_PAYMENT_PROXY_NAME = 'CyberSourcePayment';

    @AuraEnabled
    public static clariti__Payment__c getPayment(String merchRefNumber) {
        clariti__Payment__c payment = [
            SELECT Name, clariti__MerchantId__c, clariti__Status__c, clariti__Cart__r.clariti__FailureReason__c
            FROM clariti__Payment__c
            WHERE clariti__MerchantId__c = :merchRefNumber
            LIMIT 1
        ];

        return payment;
    }

    @AuraEnabled
    public static avo_Cybersource_Transaction__c getCyberSourceTransaction(String merchRefNumber) {
        
        // check the cybersource transaction table to see if there is a completed transaction for the current payment
        List<avo_Cybersource_Transaction__c> transactions = [
            SELECT iD, Merchant_ID__c,Status__c, Message__c,Processor_Transaction_Id__c	
            FROM avo_Cybersource_Transaction__c
            WHERE Merchant_ID__c = :merchRefNumber
        ];
        if (transactions.size() >0)
        {
            List<clariti__Payment__c> payments= [
                SELECT  Name, clariti__MerchantId__c, clariti__Status__c, clariti__Cart__r.clariti__FailureReason__c,
                        Processor_Transaction_Id__c,clariti__PaymentMethod__c
                FROM clariti__Payment__c
                WHERE clariti__MerchantId__c = :merchRefNumber];
            
            if (payments.size() >0)
            {

                 // this is how clariti handles payment, block start here.
                clariti__Payment__c payment;
                payment = payments[0];
                                        
                if (transactions[0].Status__c!='Success') {
                    clariti__Cart__c cart = new clariti.CartSelector().getCartAndItemsById(payment.clariti__Cart__c, new Set<String>());
                    cart.clariti__Status__c = 'Failed';
                    cart.clariti__FailureReason__c = transactions[0].Message__c;        
                    payment.clariti__Status__c = 'Failed';
                    payment.Processor_Transaction_Id__c = transactions[0].Processor_Transaction_Id__c;
                    update new List<SObject> { payment, cart };
                }
                
                //TODO Processor_Transaction_Id__c should store a value returned by Cyber Source
                payment.Processor_Transaction_Id__c = transactions[0].Processor_Transaction_Id__c;  
                update new List<SObject> { payment };
                clariti__PaymentMethod__mdt paymentMethodSetting = new clariti.PaymentMethodSelector().getSettingByNameOrLabel(
                    payment.clariti__PaymentMethod__c
                );
       
                List<clariti.PaymentService.PaymentMethod> paymentMethods = clariti.PaymentService.buildPaymentMethods(
                    new List<clariti__PaymentMethod__mdt>{ paymentMethodSetting },
                    payment
                );
        		
                if (transactions[0].Status__c =='Success') {
                	clariti.PaymentProcessorService.handlePaymentProcess(payment.clariti__Cart__c, paymentMethods, payment);
                }
                // block end here.
            }
            return transactions[0];
        }
        return null;
    }

    @AuraEnabled
    public static InitiatePurchaseResult initiatePurchase(String cartId, String paymentMethods, Decimal amount) {
        String merchRefNumber = getRefNumber(); //getPaymentMerchantTransactionId();

        List<clariti.PaymentService.PaymentMethod> deserializedPaymentMethods = deserializePaymentMethods(paymentMethods);

        clariti.PaymentService.PaymentResult paymentResult = clariti.PaymentProcessorService.processInitiatedPayment(
            cartId,
            deserializedPaymentMethods,
            merchRefNumber
        );

        if (!paymentResult.success) {
            throw new AuraHandledException(paymentResult.failureReason);
        }

        return new InitiatePurchaseResult(paymentResult, merchRefNumber);
    }

    public static String getRefNumber(){
        DateTime oUTSDateTime = System.now();
        String oUTSRefNum = oUTSDateTime.format('yyyyMMddHHmmssSSS') + String.valueOf(Integer.valueof((Math.random() * 10000000)));      
        return oUTSRefNum;
    }

    public static String getPaymentMerchantTransactionId() {
        Blob b = Crypto.generateAesKey(128);
        String h = EncodingUtil.convertToHex(b);
        String guid = h.substring(0,8) + '-' + h.substring(8,12) + '-' + h.substring(12,16) + '-' + h.substring(16,20) + '-' + h.substring(20);       
        return guid;
    }
    
    @AuraEnabled
    public static String getPostUrl() {
        Site serviceSite = [SELECT Id FROM Site WHERE Name = :CYBER_SOURCE_PAYMENT_PROXY_NAME];
        SiteDetail serviceSiteDetail = [SELECT SecureUrl FROM SiteDetail WHERE DurableId = :serviceSite.Id];

        return serviceSiteDetail.SecureUrl;
    }

    private static List<clariti.PaymentService.PaymentMethod> deserializePaymentMethods(String data) {
        List<CustomPaymentMethod> deserializedPaymentMethods = (List<CustomPaymentMethod>) JSON.deserialize(
            data,
            List<CustomPaymentMethod>.class
        );

        List<clariti.PaymentService.PaymentMethod> result = new List<clariti.PaymentService.PaymentMethod>();

        for (CustomPaymentMethod m : deserializedPaymentMethods) {
            clariti.PaymentService.PaymentMethod pm = new clariti.PaymentService.PaymentMethod();

            pm.label = m.label;
            pm.name = m.name;
            pm.portalAccessible = m.portalAccessible;
            pm.isValidForDepositPayable = m.isValidForDepositPayable;
            pm.paymentGatewayEventName = m.paymentGatewayEventName;
            pm.fields = new List<clariti.PaymentService.PaymentField>();

            if (m.fields != null) {
                for (CustomPaymentField f : m.fields) {
                    clariti.PaymentService.PaymentField pf = new clariti.PaymentService.PaymentField();

                    pf.label = f.label;
                    pf.fieldName = f.fieldName;
                    pf.required = f.required;
                    pf.value = f.value;
                    pf.displayValue = f.displayValue;
                    pf.type = f.type;
                    pf.maxLength = f.maxLength;

                    pm.fields.add(pf);
                }
            }

            result.add(pm);
        }

        return result;
    }

    public class InitiatePurchaseResult {
        @AuraEnabled
        public String paymentResult;
        @AuraEnabled
        public String merchantId;

        public InitiatePurchaseResult(clariti.PaymentService.PaymentResult paymentResult, String merchantId) {
            this.paymentResult = JSON.serialize(new CustomPaymentResult(paymentResult));
            this.merchantId = merchantId;
        }
    }

    public class CustomPaymentMethod {
        public String label { get; set; }
        public String name { get; set; }
        public Boolean portalAccessible { get; set; }
        public Boolean isValidForDepositPayable { get; set; }
        public List<CustomPaymentField> fields { get; set; }
        public String paymentGatewayEventName { get; set; }

        public CustomPaymentMethod() {
            this.portalAccessible = false;
            this.fields = new List<CustomPaymentField>();
        }
    }

    public class CustomPaymentField {
        public String label { get; set; }
        public String fieldName { get; set; }
        public Boolean required { get; set; }
        public String value { get; set; }
        public String displayValue { get; set; }
        public String type { get; set; }
        public Integer maxLength { get; set; }
    }

    public class CustomPaymentResult {
        public Boolean success;
        public Id paymentId;
        public String paymentName;
        public String paymentMethod;
        public Decimal paymentAmount;
        public String failureReason;

        public CustomPaymentResult(clariti.PaymentService.PaymentResult pr) {
            this.success = pr.success;
            this.paymentId = pr.paymentId;
            this.paymentName = pr.paymentName;
            this.paymentMethod = pr.paymentMethod;
            this.paymentAmount = pr.paymentAmount;
            this.failureReason = pr.failureReason;
        }
    }
}