force-app/main/default/objects/avo_Cybersource_Transaction__c/avo_Cybersource_Transaction__c.object-meta.xml
<CustomObject>
    <label>Cybersource Transaction</label>
    <nameField>
        <displayFormat>CT-{0000000}</displayFormat>
        <label>Cybersource Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cybersource Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/avo_Cybersource_Transaction__c/fields/Merchant_ID__c.field-meta.xml
<CustomField>
    <fullName>Merchant_ID__c</fullName>
    <label>Merchant ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/avo_Cybersource_Transaction__c/fields/Processor_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Processor_Transaction_Id__c</fullName>
    <label>Processor Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clariti__Payment__c/clariti__Payment__c.object-meta.xml
<CustomObject>
    <description>Payment is used to record the amount collected per payment method during the cart transaction</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{MM}{DD}{YYYY}-{000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clariti__Payment__c/fields/clariti__Payment__c.field-meta.xml
<CustomField>
    <fullName>clariti__Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>clariti__Payment__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clariti__Payment__c/fields/Processor_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Processor_Transaction_Id__c</fullName>
    <externalId>true</externalId>
    <label>Processor Transaction Id</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CyberSourcePaymentResponseController.cls
global with sharing class CyberSourcePaymentResponseController {
    public clariti__Payment__c payment { get; set; }

    public CyberSourcePaymentResponseController() {
             
         
    }
    public void UpdatePayment()
    {
        
        string merchantid = ApexPages.currentPage().getParameters().get('req_reference_number');
        string decision = ApexPages.currentPage().getParameters().get('decision');
        string result = 'Failure';
        string message = ApexPages.currentPage().getParameters().get('message');
        string processorTransactionId = ApexPages.currentPage().getParameters().get('transaction_id');

        if (decision == 'ACCEPT')
            result= 'Success';
        
        avo_Cybersource_Transaction__c cybersourceTransaction = new avo_Cybersource_Transaction__c();
        cybersourceTransaction.Merchant_ID__c = merchantid;
        cybersourceTransaction.Status__c = result;
        cybersourceTransaction.Message__c = message;
        cybersourceTransaction.Processor_Transaction_Id__c = processorTransactionId;

        insert cybersourceTransaction; 
        
    }
}