force-app/main/default/objects/AVO_County__c/AVO_County__c.object-meta.xml
<CustomObject>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_County__c/fields/AVO_County__c.field-meta.xml
<CustomField>
    <fullName>AVO_County__c</fullName>
    <label>County #</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AVO_County__c/fields/AVO_FIPS__c.field-meta.xml
<CustomField>
    <fullName>AVO_FIPS__c</fullName>
    <label>FIPS</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AVO_County__c/recordTypes/County.recordType-meta.xml
<RecordType>
    <fullName>County</fullName>
    <active>true</active>
    <label>County</label>
</RecordType>

force-app/main/default/objects/AVO_Withdrawals__c/AVO_Withdrawals__c.object-meta.xml
<CustomObject>
    <label>Withdrawals</label>
    <nameField>
        <label>Withdrawals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Withdrawals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Withdrawals__c/fields/AVO_GIS_UNIQUE__c.field-meta.xml
<CustomField>
    <fullName>AVO_GIS_UNIQUE__c</fullName>
    <description>Unique Identifier for the table.</description>
    <label>GIS Unique ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AVO_Withdrawals__c/fields/AVO_Permit__c.field-meta.xml
<CustomField>
    <fullName>AVO_Permit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Permit</label>
    <referenceTo>MUSW__Permit2__c</referenceTo>
    <relationshipLabel>Withdrawals</relationshipLabel>
    <relationshipName>Withdrawals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AVO_Withdrawals__c/fields/AVO_Well_Latitude__c.field-meta.xml
<CustomField>
    <fullName>AVO_Well_Latitude__c</fullName>
    <label>Well Latitude</label>
    <precision>15</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AVO_Withdrawals__c/fields/AVO_Well_Long__c.field-meta.xml
<CustomField>
    <fullName>AVO_Well_Long__c</fullName>
    <label>Well Longitude</label>
    <precision>15</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AVO_Withdrawals__c/fields/Point_X__c.field-meta.xml
<CustomField>
    <fullName>Point_X__c</fullName>
    <label>SW Pump Longitude</label>
    <precision>15</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AVO_Withdrawals__c/fields/Point_Y__c.field-meta.xml
<CustomField>
    <fullName>Point_Y__c</fullName>
    <label>SW Pump Latitude</label>
    <precision>15</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/MUSW__Permit2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Permit application details</description>
    <label>Permit</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_AppID__c.field-meta.xml
<CustomField>
    <fullName>AVO_AppID__c</fullName>
    <label>AppID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_Basin__c.field-meta.xml
<CustomField>
    <fullName>AVO_Basin__c</fullName>
    <label>Basin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALTAMAHA</fullName>
            </value>
            <value>
                <fullName>CHATTAHOOCHEE</fullName>
            </value>
            <value>
                <fullName>COOSA</fullName>
            </value>
            <value>
                <fullName>FLINT</fullName>
            </value>
            <value>
                <fullName>OCHLOCKONEE</fullName>
            </value>
            <value>
                <fullName>OCMULGEE</fullName>
            </value>
            <value>
                <fullName>OCONEE</fullName>
            </value>
            <value>
                <fullName>OGEECHEE</fullName>
            </value>
            <value>
                <fullName>SAINT MARYS</fullName>
            </value>
            <value>
                <fullName>SATILLA</fullName>
            </value>
            <value>
                <fullName>SAVANNAH</fullName>
            </value>
            <value>
                <fullName>SUWANNEE</fullName>
            </value>
            <value>
                <fullName>TALLAPOOSA</fullName>
            </value>
            <value>
                <fullName>TENNESSEE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_County__c.field-meta.xml
<CustomField>
    <fullName>AVO_County__c</fullName>
    <label>County</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_County_Lookup__c.field-meta.xml
<CustomField>
    <fullName>AVO_County_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County of the Water Source</label>
    <referenceTo>AVO_County__c</referenceTo>
    <relationshipLabel>Permits (County)</relationshipLabel>
    <relationshipName>Permits1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_Volumetric_Limits__c.field-meta.xml
<CustomField>
    <fullName>AVO_Volumetric_Limits__c</fullName>
    <label>Volumetric Limits</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_Well_Latitude__c.field-meta.xml
<CustomField>
    <fullName>AVO_Well_Latitude__c</fullName>
    <inlineHelpText>Percise GPS Coordinates of planned drilling location (Degrees, Minutes, Seconds or Decimal Degrees):</inlineHelpText>
    <label>Well Latitude</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/Avo_Withdrawals__c.field-meta.xml
<CustomField>
    <fullName>Avo_Withdrawals__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Withdrawals</label>
    <referenceTo>AVO_Withdrawals__c</referenceTo>
    <relationshipLabel>Permits (Withdrawals)</relationshipLabel>
    <relationshipName>Permits1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AVOGISmapControllerTest.cls
@isTest
public class AVOGISmapControllerTest {

   static void setup() {
        // Setup County
        
            AVO_County__c county = new AVO_County__c(
            Name = 'TestCounty', 
            AVO_FIPS__c = 111, 
            AVO_County__c = 111
        );
        insert county;

        // Setup Permit with matching values
        MUSW__Permit2__c permit = new MUSW__Permit2__c(
            Name = 'Permit1',
            AVO_AppID__c = 'G-00284',
            AVO_Basin__c = 'Satilla',
            AVO_Volumetric_Limits__c = 100 ,
            AVO_County_Lookup__c = county.Id
        );
        insert permit;

        // Setup Withdrawal record types
        Id gwRT = Schema.SObjectType.AVO_Withdrawals__c.getRecordTypeInfosByName().get('Ground Water Withdrawal Application').getRecordTypeId();
        Id swRT = Schema.SObjectType.AVO_Withdrawals__c.getRecordTypeInfosByName().get('Surface Water Withdrawal Application').getRecordTypeId();

        // Create withdrawals matching GIS keys
        insert new List<AVO_Withdrawals__c>{
            new AVO_Withdrawals__c(
                AVO_Permit__c = permit.Id,
                AVO_GIS_UNIQUE__c = '',
                RecordTypeId = gwRT
            ),
            new AVO_Withdrawals__c(
                AVO_Permit__c = permit.Id,
                AVO_GIS_UNIQUE__c = 'G-00284_G1',
                RecordTypeId = swRT
            )
        };
    }

    @isTest(seealldata = true)
    static void testUploadFile() {
        setup();
        // Construct matching CSV data
       /* String csv = 
            'APP_ID,COUNTY,DNRBASINS,POINT_X,POINT_Y,GIS_unique,SUBAREA4,COASTAL24,FRBPCONZON,Suspension,CritStrBuf,PrioZone,DarkGreenA\n' +
            'APP001,TESTCOUNTY,ALTAMAHA,-84.12,31.55,GIS_GW,Yes,None,R,No,Yes,7,Yes\n' +
            'APP001,TESTCOUNTY,ALTAMAHA,-82.98,30.33,GIS_SW,No,None,X,Yes,No,3,No'; */

        
        String csv = 'OBJECTID,SOURCE,APP_ID,PERMIT_NO,PrimaryID,OwNameComm,MapCreate,Pond_Fund,PUMPNO,VERIFIED,GIS_unique,SUBAREA4,COUNTY,COASTAL24,HUC08,FRBPCONZON,HUC10,HUC12,HUC08NAME,HUC10NAME,DNRBASINS,POINT_X,POINT_Y,Type,HUC12NAME,AWDregion,Meter,Suspension,CritStrBuf,Inactive,Fips,APM,PrioZone,DarkGreenA\n'+
'17731,GFC,G-00284,,G-00284,,,,1,YES,G-00284_G1,no,LEE,none,3070202,R,307020201,30702020104,Little Satilla River,Big Satilla Creek-upper-,Satilla,-82.30672511,31.61119301,G,BIG SATILLA CREEK UPPER 3,,,GW only,Yes,,1,,10,Yes\n'+
'17519,GFC,G-00289,,G-00289,,,,1,YES,G-00289_G1,no,Laurens,Hello,3070202,R,307020201,30702020104,Little Satilla River,Big Satilla Creek-upper-,Satilla,-82.30353724,31.60461901,G,BIG SATILLA CREEK UPPER 3,,,GW only,No,,1,,9,No';
        
        //String encoded = EncodingUtil.base64Encode(Blob.valueOf(csv));
		 Blob csvBlob = Blob.valueOf(csv);
        String base64String = EncodingUtil.base64Encode(csvBlob);
        
        
        Test.startTest();
        String result = AVOGISmapController.uploadFile(base64String);
        Test.stopTest();

        System.debug('Result: ' + result);
        System.assert(result.contains('Updated'));

        // Validate the records were updated
        List<AVO_Withdrawals__c> updated = [
            SELECT AVO_GIS_UNIQUE__c, AVO_Well_Long__c, AVO_Well_Latitude__c, Point_X__c, Point_Y__c
            FROM AVO_Withdrawals__c
            WHERE AVO_GIS_UNIQUE__c IN ('GIS_GW', 'GIS_SW')
        ];
       // System.assertEquals(2, updated.size(), '2 withdrawals should be updated');

        for (AVO_Withdrawals__c w : updated) {
            if (w.AVO_GIS_UNIQUE__c == 'GIS_GW') {
                System.assertEquals(Decimal.valueOf('-84.12'), w.AVO_Well_Long__c);
                System.assertEquals(Decimal.valueOf('31.55'), w.AVO_Well_Latitude__c);
            } else {
                System.assertEquals(Decimal.valueOf('-82.98'), w.Point_X__c);
                System.assertEquals(Decimal.valueOf('30.33'), w.Point_Y__c);
            }
        }
    }
}