force-app/main/default/objects/AVO_Meter_Transaction__c/AVO_Meter_Transaction__c.object-meta.xml
<CustomObject>
    <label>Meter Transaction</label>
    <nameField>
        <label>Meter Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meter Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Meter_Transaction__c/fields/AVO_Application_Number__c.field-meta.xml
<CustomField>
    <fullName>AVO_Application_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application Number</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MUSW__Permit2__c.MUSW__Type__c</field>
            <operation>notEqual</operation>
            <value>Revision</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MUSW__Permit2__c</referenceTo>
    <relationshipLabel>Meter_Transaction Application Number</relationshipLabel>
    <relationshipName>Meter_Transaction_Application_Number</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AVO_Meter_Transaction__c/fields/AVO_Permit_Number__c.field-meta.xml
<CustomField>
    <fullName>AVO_Permit_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Permit Number</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>MUSW__Permit2__c.MUSW__Type__c</field>
            <operation>notEqual</operation>
            <value>Revision</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MUSW__Permit2__c</referenceTo>
    <relationshipLabel>Meter Transaction</relationshipLabel>
    <relationshipName>Meter_Transaction_Permit_Number</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/MUSW__Permit2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Permit application details</description>
    <label>Permit</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_Inactive_Reason__c.field-meta.xml
<CustomField>
    <fullName>AVO_Inactive_Reason__c</fullName>
    <label>Inactive Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AVO_Inactive_Reason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_Permit_Closed_Status__c.field-meta.xml
<CustomField>
    <fullName>AVO_Permit_Closed_Status__c</fullName>
    <label>Permit Closed Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled Must Reapply</fullName>
            </value>
            <value>
                <fullName>Relinquished</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Cancelled Application</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_Volumetric_Limits__c.field-meta.xml
<CustomField>
    <fullName>AVO_Volumetric_Limits__c</fullName>
    <label>Volumetric Limits</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <description>Status of the permit as it moves through the business workflow.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Submitted Documents</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Transaction</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Finaled</fullName>
            </value>
            <value>
                <fullName>Enforcement</fullName>
            </value>
            <value>
                <fullName>Initial Review</fullName>
            </value>
            <value>
                <fullName>LOC Package</fullName>
            </value>
            <value>
                <fullName>LOC Issued</fullName>
            </value>
            <value>
                <fullName>LOC Documents Uploaded</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Form Assessment</fullName>
            </value>
            <value>
                <fullName>Final Evaluation</fullName>
            </value>
            <value>
                <fullName>Permit Approval</fullName>
            </value>
            <value>
                <fullName>Revision Approval</fullName>
            </value>
            <value>
                <fullName>Ready for Issuance</fullName>
            </value>
            <value>
                <fullName>Permit Issued</fullName>
            </value>
            <value>
                <fullName>Revision Issued</fullName>
            </value>
            <value>
                <fullName>Issued</fullName>
            </value>
            <value>
                <fullName>Permit Rejected</fullName>
            </value>
            <value>
                <fullName>Consolidated</fullName>
            </value>
            <value>
                <fullName>Permit Denied</fullName>
            </value>
            <value>
                <fullName>Revision Denied</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Undocumented Source</fullName>
            </value>
            <value>
                <fullName>APPLICATION GIS MAPPING</fullName>
            </value>
            <value>
                <fullName>Undocumented Source Pending Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <description>The permit type. This is typically related to the record type.</description>
    <label>Type (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agricultural Surface Water Pump</fullName>
            </value>
            <value>
                <fullName>Agricultural Water Withdrawal Application</fullName>
            </value>
            <value>
                <fullName>Agricultural Water Withdrawal Permit</fullName>
            </value>
            <value>
                <fullName>Agricultural Well Pump</fullName>
            </value>
            <value>
                <fullName>Application for Permit Consolidation</fullName>
            </value>
            <value>
                <fullName>Revision</fullName>
            </value>
            <value>
                <fullName>Permit Relinquishment</fullName>
            </value>
            <value>
                <fullName>Well and Pump Data</fullName>
            </value>
            <value>
                <fullName>Well Plug and Abandonment</fullName>
            </value>
            <value>
                <fullName>AG Water Metering Installation</fullName>
            </value>
            <value>
                <fullName>Undocumented Source</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/recordTypes/Agricultural_Water_Withdrawal_Permit.recordType-meta.xml
<RecordType>
    <fullName>Agricultural_Water_Withdrawal_Permit</fullName>
    <active>true</active>
    <label>Agricultural Water Withdrawal Permit</label>
</RecordType>

force-app/main/default/objects/MUSW__Permit2__c/recordTypes/AVO_Agricultural_Water_Withdrawal_Application.recordType-meta.xml
<RecordType>
    <fullName>AVO_Agricultural_Water_Withdrawal_Application</fullName>
    <active>true</active>
    <label>Agricultural Water Withdrawal Application</label>
</RecordType>

force-app/main/default/objects/MUSW__Review__c/MUSW__Review__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Tracks the collaborative plan review process and associated documents</description>
    <label>Review</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Review__c/fields/AVO_Meter_Transaction__c.field-meta.xml
<CustomField>
    <fullName>AVO_Meter_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meter Transaction</label>
    <referenceTo>AVO_Meter_Transaction__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Review__c/fields/MUSW__Permit2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Permit2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Permit</label>
    <referenceTo>MUSW__Permit2__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Review__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <description>Current status of the review.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Required</fullName>
            </value>
            <value>
                <fullName>Additional Information Required</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Completed to LOC Package</fullName>
            </value>
            <value>
                <fullName>Completed to Form Assessment</fullName>
            </value>
            <value>
                <fullName>Completed to Final Evaluation</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
            <value>
                <fullName>Pending Wavier Approval</fullName>
                <label>Pending Waiver Approval</label>
            </value>
            <value>
                <fullName>Wavier Denied</fullName>
                <label>Waiver Denied</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Fail Back</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Review__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AG Program Manager Review</fullName>
                <label>Step 1 - AG Program Manager Approval</label>
            </value>
            <value>
                <fullName>Director Office Review</fullName>
            </value>
            <value>
                <fullName>Evaluation of Withdrawal 1st Cut</fullName>
            </value>
            <value>
                <fullName>Evaluation of Withdrawal 2nd Cut</fullName>
            </value>
            <value>
                <fullName>Irrigation Efficiency Cert Review</fullName>
            </value>
            <value>
                <fullName>Low Flow Protection Plan Review</fullName>
            </value>
            <value>
                <fullName>Special Appraisal</fullName>
            </value>
            <value>
                <fullName>Water Conservation Plan Review</fullName>
            </value>
            <value>
                <fullName>Water Reuse Visibility Study Review</fullName>
            </value>
            <value>
                <fullName>Water Shed Manager Review</fullName>
                <label>Step 3 - Water Shed Manager Approval</label>
            </value>
            <value>
                <fullName>Water Supply Manager Review</fullName>
                <label>Step 2 - Water Supply Manager Approval</label>
            </value>
            <value>
                <fullName>Well Data Form Review</fullName>
            </value>
            <value>
                <fullName>Completeness Review</fullName>
            </value>
            <value>
                <fullName>Waiver Review</fullName>
            </value>
            <value>
                <fullName>Withdrawal LOC Review</fullName>
            </value>
            <value>
                <fullName>Form Assessment Review</fullName>
            </value>
            <value>
                <fullName>Final Evaluation Review</fullName>
            </value>
            <value>
                <fullName>Meter Installation Review</fullName>
            </value>
            <value>
                <fullName>Requester Review</fullName>
            </value>
            <value>
                <fullName>Permitting Review</fullName>
            </value>
            <value>
                <fullName>Compliance Review</fullName>
            </value>
            <value>
                <fullName>Metering Review</fullName>
            </value>
            <value>
                <fullName>WWSA Review</fullName>
            </value>
            <value>
                <fullName>GIS Review</fullName>
            </value>
            <value>
                <fullName>Meter Review</fullName>
            </value>
            <value>
                <fullName>Step 5 - Director Approval</fullName>
            </value>
            <value>
                <fullName>Permit Management Review</fullName>
            </value>
            <value>
                <fullName>Step 4 - Deputy Director Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/AVO_Inactive_Reason.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Duplicate</fullName>
    </customValue>
    <customValue>
        <fullName>Never Installed</fullName>
    </customValue>
    <customValue>
        <fullName>Non AG Use/Other Applciation</fullName>
    </customValue>
    <customValue>
        <fullName>Voluntarily Relinquished</fullName>
    </customValue>
    <customValue>
        <fullName>Consolidated Permit</fullName>
    </customValue>
    <customValue>
        <fullName>New Well/Pump not Installed</fullName>
    </customValue>
    <customValue>
        <fullName>Ag SW Currently Unused</fullName>
    </customValue>
    <customValue>
        <fullName>AG GW Currently Unused</fullName>
    </customValue>
    <customValue>
        <fullName>AG WTP Currently Unused</fullName>
    </customValue>
    <customValue>
        <fullName>Revoked</fullName>
    </customValue>
    <customValue>
        <fullName>Dormant at permitee Request</fullName>
    </customValue>
    <customValue>
        <fullName>Plugged/Abandoned</fullName>
    </customValue>
    <customValue>
        <fullName>Expired LOC</fullName>
    </customValue>
    <customValue>
        <fullName>Incomplete Form</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Compliance Case</fullName>
    </customValue>
    <customValue>
        <fullName>Applicant Request</fullName>
    </customValue>
    <customValue>
        <fullName>GPMS Under Permitting Capacity</fullName>
    </customValue>
    <customValue>
        <fullName>Merged to an existing application/permit</fullName>
    </customValue>
    <customValue>
        <fullName>Not Waters of the State</fullName>
    </customValue>
    <customValue>
        <fullName>No Longer Present</fullName>
    </customValue>
    <customValue>
        <fullName>Transfer Pump Only</fullName>
    </customValue>
    <customValue>
        <fullName>Application Denied</fullName>
    </customValue>
    <masterLabel>AVO Inactive Reason</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AvoConsolidateTest.cls
@isTest
private class AvoConsolidateTest {

    @TestSetup
    static void dataSetup() {
        ID WITHDRAWAL_APP_REC_TYPE_ID = Schema.SObjectType.MUSW__Permit2__c
            .getRecordTypeInfosByDeveloperName().get('AVO_Agricultural_Water_Withdrawal_Application').getRecordTypeId();

        ID WITHDRAWAL_PERMIT_REC_TYPE_ID = Schema.SObjectType.MUSW__Permit2__c
            .getRecordTypeInfosByDeveloperName().get('Agricultural_Water_Withdrawal_Permit').getRecordTypeId();

        // Permit to KEEP (Permit)
        MUSW__Permit2__c permitToKeep = new MUSW__Permit2__c(
            Name = 'Permit To Keep',
            RecordTypeId = WITHDRAWAL_PERMIT_REC_TYPE_ID,
            MUSW__Type__c = 'Agricultural Water Withdrawal Permit',
            MUSW__Status__c = 'Final Evaluation',
            AVO_Volumetric_Limits__c = 10
        );
        insert permitToKeep;

        // Permit to CONSOLIDATE (App)
        MUSW__Permit2__c permitToConsolidate = new MUSW__Permit2__c(
            Name = 'Permit To Consolidate',
            RecordTypeId = WITHDRAWAL_APP_REC_TYPE_ID,
            MUSW__Type__c = 'Agricultural Water Withdrawal Application',
            AVO_Inactive_Reason__c = 'Merged to an existing application/permit',
            MUSW__Status__c = 'Consolidated',
            AVO_Permit_Closed_Status__c = 'Cancelled Application',
            AVO_Volumetric_Limits__c = 10
        );
        insert permitToConsolidate;

        // Review
        insert new MUSW__Review__c(
            Name = 'Review1',
            MUSW__Permit2__c = permitToKeep.Id,
            MUSW__Type__c = 'Withdrawal LOC Review',
            MUSW__Status__c = 'Open'
        );

        // Task
        insert new Task(
            WhatId = permitToKeep.Id,
            Subject = 'GIS Mapping',
            Status = 'Open'
        );

        // Meter
        insert new AVO_Meter_Transaction__c(
            AVO_Application_Number__c = permitToConsolidate.Id,
            AVO_Permit_Number__c = permitToConsolidate.Id
        );
    }

    @isTest
    static void testAppToPermitConsolidation() {
        MUSW__Permit2__c permitToKeep = [SELECT Id FROM MUSW__Permit2__c WHERE Name = 'Permit To Keep' LIMIT 1];
        MUSW__Permit2__c permitToConsolidate = [SELECT Id FROM MUSW__Permit2__c WHERE Name = 'Permit To Consolidate' LIMIT 1];

        AvoConsolidate.ConsolidationReq req = new AvoConsolidate.ConsolidationReq();
        req.recordIdToKeep = permitToKeep.Id;
        req.recordIdToConsolidate = permitToConsolidate.Id;

        Test.startTest();
        List<ID> results = AvoConsolidate.consolidateRecord(new List<AvoConsolidate.ConsolidationReq>{ req });
        Test.stopTest();

        System.assertEquals(1, results.size());
        System.assertEquals(permitToKeep.Id, results[0]);

        MUSW__Permit2__c updatedConsolidated = [
            SELECT AVO_ActiveRefNo__c, MUSW__Status__c, AVO_Inactive_Reason__c, AVO_Permit_Closed_Status__c
            FROM MUSW__Permit2__c WHERE Id = :permitToConsolidate.Id
        ];
      System.assertEquals('Consolidated', updatedConsolidated.MUSW__Status__c);
       System.assertEquals('Merged to an existing application/permit', updatedConsolidated.AVO_Inactive_Reason__c);
        System.assertEquals('Cancelled Application', updatedConsolidated.AVO_Permit_Closed_Status__c);
       //System.assertEquals(permitToKeep.Id, updatedConsolidated.AVO_ActiveRefNo__c);

        List<AVO_Meter_Transaction__c> meters = [
            SELECT AVO_Application_Number__c, AVO_Permit_Number__c
            FROM AVO_Meter_Transaction__c WHERE AVO_Application_Number__c = :permitToKeep.Id
        ];
        System.assert(meters.size() > 0, 'Meter transactions should be moved to permitToKeep');

        List<Task> updatedTasks = [SELECT Status FROM Task WHERE WhatId = :permitToKeep.Id];
        for (Task t : updatedTasks) {
            //System.assertEquals('Denied', t.Status, 'Old tasks should be marked Denied');
        }

        List<MUSW__Review__c> reviews = [SELECT MUSW__Status__c FROM MUSW__Review__c WHERE MUSW__Permit2__c = :permitToKeep.Id];
        for (MUSW__Review__c r : reviews) {
            System.assertEquals('Fail Back', r.MUSW__Status__c);
        }
    }

    @isTest
    static void testAppToAppWithInReviewStatus() {
        ID appRT = Schema.SObjectType.MUSW__Permit2__c
            .getRecordTypeInfosByDeveloperName().get('AVO_Agricultural_Water_Withdrawal_Application').getRecordTypeId();

        MUSW__Permit2__c appToKeep = new MUSW__Permit2__c(
            Name = 'App To Keep 2',
            RecordTypeId = appRT,
            MUSW__Type__c = 'Agricultural Water Withdrawal Application',
            MUSW__Status__c = 'In Review',
            AVO_Volumetric_Limits__c = 1
        );
        insert appToKeep;

        MUSW__Permit2__c appToConsolidate = new MUSW__Permit2__c(
            Name = 'App To Consolidate 2',
            RecordTypeId = appRT,
            MUSW__Type__c = 'Agricultural Water Withdrawal Application',
            MUSW__Status__c = 'Submitted',
            AVO_Permit_Closed_Status__c = 'Cancelled Application',
            AVO_Inactive_Reason__c = 'Merged to an existing application/permit',
            AVO_Volumetric_Limits__c = 1
            
        );
        insert appToConsolidate;

        insert new AVO_Meter_Transaction__c(
            AVO_Application_Number__c = appToConsolidate.Id,
            AVO_Permit_Number__c = appToConsolidate.Id
        );

        AvoConsolidate.ConsolidationReq req = new AvoConsolidate.ConsolidationReq();
        req.recordIdToKeep = appToKeep.Id;
        req.recordIdToConsolidate = appToConsolidate.Id;

        Test.startTest();
        AvoConsolidate.consolidateRecord(new List<AvoConsolidate.ConsolidationReq>{ req });
        Test.stopTest();

        MUSW__Permit2__c updated = [
            SELECT AVO_Permit_Closed_Status__c, AVO_Inactive_Reason__c, AVO_ActiveRefNo__c, MUSW__Status__c
            FROM MUSW__Permit2__c WHERE Id = :appToConsolidate.Id
        ];
      System.assertEquals('Cancelled Application', updated.AVO_Permit_Closed_Status__c);
      System.assertEquals('Merged to an existing application/permit', updated.AVO_Inactive_Reason__c);
       // System.assertEquals(appToKeep.Id, updated.AVO_ActiveRefNo__c);
    }

    @isTest
    static void testPermToPermConsolidation() {
        ID permitRTId = Schema.SObjectType.MUSW__Permit2__c
            .getRecordTypeInfosByDeveloperName().get('Agricultural_Water_Withdrawal_Permit').getRecordTypeId();

        MUSW__Permit2__c permToKeep = new MUSW__Permit2__c(
            Name = 'Perm To Keep 2',
            RecordTypeId = permitRTId,
            MUSW__Type__c = 'Agricultural Water Withdrawal Permit',
            MUSW__Status__c = 'Form Assesment',
            AVO_Volumetric_Limits__c = 1
        );
        insert permToKeep;

        MUSW__Permit2__c permToConsolidate = new MUSW__Permit2__c(
            Name = 'Perm To Consolidate 2',
            RecordTypeId = permitRTId,
            MUSW__Type__c = 'Agricultural Water Withdrawal Permit',
            MUSW__Status__c = 'Consolidated',
            AVO_Inactive_Reason__c = 'Consolidated Permit',
            AVO_Volumetric_Limits__c = 1
        );
        insert permToConsolidate;

        AvoConsolidate.ConsolidationReq req = new AvoConsolidate.ConsolidationReq();
        req.recordIdToKeep = permToKeep.Id;
        req.recordIdToConsolidate = permToConsolidate.Id;

        Test.startTest();
        AvoConsolidate.consolidateRecord(new List<AvoConsolidate.ConsolidationReq>{ req });
        Test.stopTest();

        MUSW__Permit2__c consolidated = [SELECT MUSW__Status__c, AVO_Inactive_Reason__c FROM MUSW__Permit2__c WHERE Id = :permToConsolidate.Id];
        System.assertEquals('Consolidated', consolidated.MUSW__Status__c);
        System.assertEquals('Consolidated Permit', consolidated.AVO_Inactive_Reason__c);
    }
}