force-app/main/default/objects/AVO_Meter_Transaction__c/AVO_Meter_Transaction__c.object-meta.xml
<CustomObject>
    <label>Meter Transaction</label>
    <nameField>
        <label>Meter Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meter Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Meter_Transaction__c/fields/AVO_Batch_ID__c.field-meta.xml
<CustomField>
    <fullName>AVO_Batch_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch ID</label>
    <referenceTo>AVO_Meter_Transaction__c</referenceTo>
    <relationshipLabel>Meter Transactions (Batch ID)</relationshipLabel>
    <relationshipName>Meter_Transactions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AVO_Meter_Transaction__c/fields/AVO_Batch_Status__c.field-meta.xml
<CustomField>
    <fullName>AVO_Batch_Status__c</fullName>
    <label>Batch Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Review Required</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Meter_Transaction__c/fields/AVO_Meter_Reading_Type__c.field-meta.xml
<CustomField>
    <fullName>AVO_Meter_Reading_Type__c</fullName>
    <label>Meter Reading Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yearly Reading</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Meter_Transaction__c/fields/AVO_Meter_Serial_Number_MSN__c.field-meta.xml
<CustomField>
    <fullName>AVO_Meter_Serial_Number_MSN__c</fullName>
    <label>Meter Serial Number (MSN)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AVO_Meter_Transaction__c/fields/AVO_Reading__c.field-meta.xml
<CustomField>
    <fullName>AVO_Reading__c</fullName>
    <label>Meter Reading</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AVO_Meter_Transaction__c/fields/AVO_Reading_Comment__c.field-meta.xml
<CustomField>
    <fullName>AVO_Reading_Comment__c</fullName>
    <label>Reading Comment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AVO_Meter_Transaction__c/fields/AVO_Type__c.field-meta.xml
<CustomField>
    <fullName>AVO_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agricultural Flow Meter Approval</fullName>
            </value>
            <value>
                <fullName>AG Water Metering Installation</fullName>
            </value>
            <value>
                <fullName>Batch Meter Entry</fullName>
            </value>
            <value>
                <fullName>Meter Allocation</fullName>
            </value>
            <value>
                <fullName>Meter Application</fullName>
            </value>
            <value>
                <fullName>Batch Meter Reading</fullName>
            </value>
            <value>
                <fullName>Meter Maintenance Request</fullName>
            </value>
            <value>
                <fullName>Meter Reading</fullName>
            </value>
            <value>
                <fullName>Meter Update</fullName>
            </value>
            <value>
                <fullName>Meter Entry</fullName>
            </value>
            <value>
                <fullName>Meter Replacement Installation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Meter_Transaction__c/fields/Read_Meter__c.field-meta.xml
<CustomField>
    <fullName>Read_Meter__c</fullName>
    <label>Read Meter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MeterReadingCSVProcessor.cls
public with sharing class MeterReadingCSVProcessor {
    @AuraEnabled
    public static void processMeterReadingCSV(Id batchMeterReadingId) {
        System.debug('RecordId IS: '+ batchMeterReadingId);
        AVO_Meter_Transaction__c batchMeterReading;
        try {
            batchMeterReading = [SELECT Id, (SELECT Id,FileExtension FROM CombinedAttachments WHERE FileExtension = 'csv')
                                 FROM AVO_Meter_Transaction__c
                                 WHERE Id = :batchMeterReadingId
                                 LIMIT 1];
        } catch (Exception e) {
            System.debug('Error occurred while querying Batch Meter Entry: ' + e.getMessage());
            return;
        }
        
        if (batchMeterReading != null) {
            List<CombinedAttachment> combinedAttachments = batchMeterReading.CombinedAttachments;
            
            for (CombinedAttachment combinedAttachment : combinedAttachments) {
                system.debug('show' + combinedAttachment);
                
                if (combinedAttachment.FileExtension == 'csv') {
                    ContentVersion contentVersion = [SELECT VersionData FROM ContentVersion WHERE ContentDocumentId = :combinedAttachment.Id];
    
                            
                            
                          
if (contentVersion != null) {
                        // Parse the CSV data
                        String csvData = contentVersion.VersionData.toString();
                        List<String> rows = csvData.split('\n');
                        Id meterEntryRecordTypeId = Schema.SObjectType.AVO_Meter_Transaction__c.getRecordTypeInfosByName().get('Meter Entry').getRecordTypeId();

                        // Update Meter Reading records for each row
                        List<AVO_Meter_Transaction__c> meterReadings = new List<AVO_Meter_Transaction__c>();
                        for (Integer i = 1; i < rows.size(); i++) {
                            List<String> rowData = rows[i].split(',');
       
                            AVO_Meter_Transaction__c MeterReadingRecords = [ SELECT Read_Meter__c, AVO_Reading_Comment__c,AVO_Batch_Status__c , AVO_Meter_Reading_Type__c , AVO_Meter_Geolocation__Longitude__s ,AVO_Meter_Geolocation__Latitude__s , AVO_Meter_Serial_Number_MSN__c , AVO_Reading__c
                                                                            FROM AVO_Meter_Transaction__c  
                                                                            WHERE Read_Meter__c = 'true'AND AVO_Reading_Comment__c =''AND AVO_Batch_Status__c ='Pending'AND AVO_Meter_Reading_Type__c ='Yearly Reading' AND AVO_Batch_ID__c =: batchMeterReadingId];                 
                            
                            
                            
                            
                            // Updating a new Meter Entry record
                            AVO_Meter_Transaction__c meterReading = new AVO_Meter_Transaction__c();
                            
                            meterReading.RecordTypeId = Schema.SObjectType.AVO_Meter_Transaction__c.getRecordTypeInfosByName().get('Batch Meter Reading').getRecordTypeId();
                            meterReading.AVO_Type__c = 'Batch Meter Reading';
                            meterReading.AVO_Batch_ID__c = batchMeterReading.Id;

                                 
                                
                       if(MeterReadingRecords.AVO_Meter_Serial_Number_MSN__c == rowData[0] && MeterReadingRecords.AVO_Meter_Geolocation__Latitude__s == Decimal.valueOf(rowData[1]) && MeterReadingRecords.AVO_Meter_Geolocation__Longitude__s ==Decimal.valueOf(rowData[2])){
                                 meterReading.AVO_Batch_Status__c = 'Approved';  
                                 meterReadings.add(meterReading);
                                }
                            }  
    
    update meterReadings;
                            
                        }
                    }
                }
            }
        }
    }