force-app/main/default/objects/AVO_Process_State_Transition__c/AVO_Process_State_Transition__c.object-meta.xml
<CustomObject>
    <label>Process State Transition</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>State Transition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process State Transitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Process_State_Transition__c/fields/Avo_To_State__c.field-meta.xml
<CustomField>
    <fullName>Avo_To_State__c</fullName>
    <label>To State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Object_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/MUSW__Permit2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Permit application details</description>
    <label>Permit</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <description>Status of the permit as it moves through the business workflow.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Submitted Documents</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Transaction</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Finaled</fullName>
            </value>
            <value>
                <fullName>Enforcement</fullName>
            </value>
            <value>
                <fullName>Initial Review</fullName>
            </value>
            <value>
                <fullName>LOC Package</fullName>
            </value>
            <value>
                <fullName>LOC Issued</fullName>
            </value>
            <value>
                <fullName>LOC Documents Uploaded</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Form Assessment</fullName>
            </value>
            <value>
                <fullName>Final Evaluation</fullName>
            </value>
            <value>
                <fullName>Permit Approval</fullName>
            </value>
            <value>
                <fullName>Revision Approval</fullName>
            </value>
            <value>
                <fullName>Ready for Issuance</fullName>
            </value>
            <value>
                <fullName>Permit Issued</fullName>
            </value>
            <value>
                <fullName>Revision Issued</fullName>
            </value>
            <value>
                <fullName>Issued</fullName>
            </value>
            <value>
                <fullName>Permit Rejected</fullName>
            </value>
            <value>
                <fullName>Consolidated</fullName>
            </value>
            <value>
                <fullName>Permit Denied</fullName>
            </value>
            <value>
                <fullName>Revision Denied</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Undocumented Source</fullName>
            </value>
            <value>
                <fullName>APPLICATION GIS MAPPING</fullName>
            </value>
            <value>
                <fullName>Undocumented Source Pending Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/recordTypes/All.recordType-meta.xml
<RecordType>
    <fullName>All</fullName>
    <active>false</active>
    <label>All</label>
</RecordType>

force-app/main/default/globalValueSets/Avo_Object_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Initial Review</fullName>
    </customValue>
    <customValue>
        <fullName>In Review</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Issued</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Finaled</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Enforcement</fullName>
    </customValue>
    <customValue>
        <fullName>LOC Package</fullName>
    </customValue>
    <customValue>
        <fullName>LOC Issued</fullName>
    </customValue>
    <customValue>
        <fullName>LOC Documents Uploaded</fullName>
    </customValue>
    <customValue>
        <fullName>Form Assessment</fullName>
    </customValue>
    <customValue>
        <fullName>Final Evaluation</fullName>
    </customValue>
    <customValue>
        <fullName>Permit Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Revision Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Permit Issued</fullName>
    </customValue>
    <customValue>
        <fullName>Revision Issued</fullName>
    </customValue>
    <customValue>
        <fullName>Ready to Issuance</fullName>
    </customValue>
    <customValue>
        <fullName>New</fullName>
    </customValue>
    <customValue>
        <fullName>In Transaction</fullName>
    </customValue>
    <customValue>
        <fullName>Ready for Issuance</fullName>
    </customValue>
    <customValue>
        <fullName>Ready for Final Inspection</fullName>
        <isActive>false</isActive>
        <label>Ready for Final Inspection</label>
    </customValue>
    <customValue>
        <fullName>In Violation</fullName>
        <isActive>false</isActive>
        <label>In Violation</label>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
        <isActive>false</isActive>
        <label>Closed</label>
    </customValue>
    <masterLabel>Avo Object Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AvoProcessEnginePermit.cls
/**
 * Description of class
 * a process engine fulfills all process related auto logic
 * @author Jason Li
 * last modified by Jason Li
 * @date 06/22/2021
 *  
 */

public class AvoProcessEnginePermit extends AvoProcessEngineBase{
    
    // call this function when the process engine is triggered from a permit record
    public AvoProcessEnginePermit(MUSW__Permit2__c permitTriggeredFrom) {
        permit = permitTriggeredFrom;
		triggerFrom = TriggerFromObjectEnum.PERMIT;
        initialize();
    }

    // check the process definition to see if there are stopppers which will prevent the requested
    // permit status change from happening    

    public Boolean isStatusChangeAllowed(){
        if (processFound() == false) return true;

        for(AVO_Process_State_Transition__c processStateTransition: processStateTransitions) {
            // only check the to be state, no need to check on the orignial state
            if (processStateTransition.Avo_To_State__c == permit.MUSW__Status__c){
                system.debug('Matching state transition found:' + processStateTransition);
                if (StopperConditionsMet(processStateTransition) == false){
                    // if one of the defined transitions doesn't allow the state transition to happen,
                    // the transition should not be allowed

                    // in other words, if there are multiple transition matched, the system will check
                    // to ensure all conditions are met
                    return false;
                }
            }
        }
        // return true if all conditions are met.
        return true;
    }

    // 
    public void createPostTransitionActions(){

        system.debug('starting creating post transition actions');
        if (processFound() == true){
            for(AVO_Process_State_Transition__c processStateTransition: processStateTransitions) {
                // check the to be state and orignial state
                if (processStateTransition.Avo_To_State__c == permit.MUSW__Status__c){
                    system.debug('Matching state transition found:' + processStateTransition);
                    createPostActions(processStateTransition);
                }
            }
        }
    }
}