force-app/main/default/objects/AVO_Condition_Template__c/AVO_Condition_Template__c.object-meta.xml
<CustomObject>
    <label>Condition Template</label>
    <nameField>
        <label>Condition Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Process__c/AVO_Process__c.object-meta.xml
<CustomObject>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Process_State_Post_Actions__c/AVO_Process_State_Post_Actions__c.object-meta.xml
<CustomObject>
    <label>Process State Transition Post Action</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Post Action ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process State Transition Post Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Process_State_Post_Actions__c/fields/Avo_Process__c.field-meta.xml
<CustomField>
    <fullName>Avo_Process__c</fullName>
    <formula>Avo_Process_State_Transition__r.Avo_Process__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Process</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Post_Actions__c/fields/Avo_Process_State_Transition__c.field-meta.xml
<CustomField>
    <fullName>Avo_Process_State_Transition__c</fullName>
    <label>Process State Transition</label>
    <referenceTo>AVO_Process_State_Transition__c</referenceTo>
    <relationshipLabel>Process State Transition Post Actions</relationshipLabel>
    <relationshipName>Process_State_Transition_Post_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition__c/AVO_Process_State_Transition__c.object-meta.xml
<CustomObject>
    <label>Process State Transition</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>State Transition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process State Transitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Process_State_Transition__c/fields/Avo_Process__c.field-meta.xml
<CustomField>
    <fullName>Avo_Process__c</fullName>
    <label>Process</label>
    <referenceTo>AVO_Process__c</referenceTo>
    <relationshipLabel>Process State Transitions</relationshipLabel>
    <relationshipName>State_Transitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition_Stopper__c/AVO_Process_State_Transition_Stopper__c.object-meta.xml
<CustomObject>
    <label>Process State Transition Stopper</label>
    <nameField>
        <displayFormat>TT-{00000}</displayFormat>
        <label>Transition Condition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process State Transition Stoppers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Process_State_Transition_Stopper__c/fields/Avo_Process_State_Transition__c.field-meta.xml
<CustomField>
    <fullName>Avo_Process_State_Transition__c</fullName>
    <label>Process State Transition</label>
    <referenceTo>AVO_Process_State_Transition__c</referenceTo>
    <relationshipLabel>Process State Transition Must Met Conditions</relationshipLabel>
    <relationshipName>Process_State_Transition_Stoppers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition_Trigger__c/AVO_Process_State_Transition_Trigger__c.object-meta.xml
<CustomObject>
    <label>Process State Transition Trigger</label>
    <nameField>
        <displayFormat>TT-{00000}</displayFormat>
        <label>Transition Trigger ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process State Transition Triggers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Process_State_Transition_Trigger__c/fields/Avo_Process_State_Transition__c.field-meta.xml
<CustomField>
    <fullName>Avo_Process_State_Transition__c</fullName>
    <label>Process State Transition</label>
    <referenceTo>AVO_Process_State_Transition__c</referenceTo>
    <relationshipName>Process_State_Transition_Triggers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BGBL__Applied_Query__c/BGBL__Applied_Query__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Queries required by letter including any unique instructions eg. order, parent query and attach</description>
    <label>Letter Applied Query</label>
    <nameField>
        <displayFormat>AQ-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letter Applied Queries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BGBL__Applied_Query__c/fields/BGBL__Batch_Letter__c.field-meta.xml
<CustomField>
    <fullName>BGBL__Batch_Letter__c</fullName>
    <label>Letter</label>
    <referenceTo>BGBL__Batch_Letter__c</referenceTo>
    <relationshipLabel>Applied Letter Queries</relationshipLabel>
    <relationshipName>Applied_Queries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BGBL__Applied_Query__c/fields/BGBL__Query__c.field-meta.xml
<CustomField>
    <fullName>BGBL__Query__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Query</label>
    <referenceTo>BGBL__Query__c</referenceTo>
    <relationshipLabel>Letter Applied Queries as Query</relationshipLabel>
    <relationshipName>Applied_Queries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BGBL__Batch_Letter__c/BGBL__Batch_Letter__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Single and Batch letter configuration</description>
    <label>Letter</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Letters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGBL__Batch_Letter__c/fields/BGBL__Merge_Template__c.field-meta.xml
<CustomField>
    <fullName>BGBL__Merge_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Letter Template</label>
    <referenceTo>BGBL__Merge_Template__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Batch_Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BGBL__Merge_Template__c/BGBL__Merge_Template__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Stores latest attached document and versions</description>
    <label>Letter Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Letter Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGBL__Query__c/BGBL__Query__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Query definitions including fields, where clause, etc</description>
    <label>Letter Query</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Letter Queries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Review_List__c/Master_Review_List__c.object-meta.xml
<CustomObject>
    <label>Master Review List</label>
    <nameField>
        <label>Master Review List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Review Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Review_List__c/fields/avo_Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>avo_Legacy_Id__c</fullName>
    <externalId>true</externalId>
    <label>Legacy Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Master_Task_List__c/Master_Task_List__c.object-meta.xml
<CustomObject>
    <label>Master Task List</label>
    <nameField>
        <label>Master Task List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Task Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Master_Inspection_List__c/MUSW__Master_Inspection_List__c.object-meta.xml
<CustomObject>
    <label>Inspection Template</label>
    <nameField>
        <label>Inspection Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inspection Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Master_Submission_List__c/MUSW__Master_Submission_List__c.object-meta.xml
<CustomObject>
    <label>Submission Template</label>
    <nameField>
        <label>Submission Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Master_Submission_List__c/fields/avo_Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>avo_Legacy_Id__c</fullName>
    <externalId>true</externalId>
    <label>Legacy Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AvoDataMigration.cls
public class AvoDataMigration {
    public AvoDataMigration() {

    }

    // this method will update all missing guids for all objects
    public static void updateGuids(){

        System.enqueueJob(new AvoDataMigrationQueueable('AVO_Process__c'));
        System.enqueueJob(new AvoDataMigrationQueueable('AVO_Process_State_Transition__c'));
        System.enqueueJob(new AvoDataMigrationQueueable('AVO_Process_State_Transition_Trigger__c'));
        System.enqueueJob(new AvoDataMigrationQueueable('AVO_Process_State_Transition_Stopper__c'));
        System.enqueueJob(new AvoDataMigrationQueueable('AVO_Process_State_Post_Actions__c'));
        
        System.enqueueJob(new AvoDataMigrationQueueable('BGBL__Merge_Template__c '));
        System.enqueueJob(new AvoDataMigrationQueueable('BGBL__Query__c '));
        System.enqueueJob(new AvoDataMigrationQueueable('BGBL__Batch_Letter__c '));
        System.enqueueJob(new AvoDataMigrationQueueable('BGBL__Applied_Query__c '));
        
        System.enqueueJob(new AvoDataMigrationQueueable('MUSW__Master_Inspection_List__c'));
        System.enqueueJob(new AvoDataMigrationQueueable('MUSW__Master_Submission_List__c'));
        System.enqueueJob(new AvoDataMigrationQueueable('Master_Task_List__c'));
        System.enqueueJob(new AvoDataMigrationQueueable('Master_Review_List__c'));
        System.enqueueJob(new AvoDataMigrationQueueable('AVO_Condition_Template__c'));
        
    }
    // prepare GUID for all records with GUID 
    public static void updateGuid(string sObjectName){
           
        // retrieve existing records without AVO_GUID__c
        List<sObject> recordsTobeUpdated = Database.query('SELECT ID, avo_Legacy_Id__c FROM ' + sObjectName);

        system.debug('number of records to be updated from ' + sObjectName + ' : ' + recordsTobeUpdated.size());
        // add AVO_GUID__c to each record without AVO_GUID__c
        for (sObject record:recordsTobeUpdated) {
            record.put('avo_Legacy_Id__c',record.get('ID'));
        }

        Update recordsTobeUpdated;
    }
}