force-app/main/default/objects/MUSW__Deposit__c/MUSW__Deposit__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <label>Deposit</label>
    <nameField>
        <label>Deposit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deposits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Deposit__c/fields/MUSW__Amount__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Amount__c</fullName>
    <description>The total Amount that needs to be collected.</description>
    <label>Required Amount</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MUSW__Deposit__c/fields/MUSW__Permit2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Permit2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Permit</label>
    <referenceTo>MUSW__Permit2__c</referenceTo>
    <relationshipLabel>Deposits</relationshipLabel>
    <relationshipName>Deposits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Deposit__c/fields/MUSW__Transfered_In_Amount__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Transfered_In_Amount__c</fullName>
    <description>Total amount that has been transferred in to this deposit.</description>
    <label>Transfered In Amount</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MUSW__Deposit__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trust Account</fullName>
            </value>
            <value>
                <fullName>Cash Bond</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/MUSW__Permit2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Permit application details</description>
    <label>Permit</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_Volumetric_Limits__c.field-meta.xml
<CustomField>
    <fullName>AVO_Volumetric_Limits__c</fullName>
    <label>Volumetric Limits</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <description>The permit type. This is typically related to the record type.</description>
    <label>Type (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agricultural Surface Water Pump</fullName>
            </value>
            <value>
                <fullName>Agricultural Water Withdrawal Application</fullName>
            </value>
            <value>
                <fullName>Agricultural Water Withdrawal Permit</fullName>
            </value>
            <value>
                <fullName>Agricultural Well Pump</fullName>
            </value>
            <value>
                <fullName>Application for Permit Consolidation</fullName>
            </value>
            <value>
                <fullName>Revision</fullName>
            </value>
            <value>
                <fullName>Permit Relinquishment</fullName>
            </value>
            <value>
                <fullName>Well and Pump Data</fullName>
            </value>
            <value>
                <fullName>Well Plug and Abandonment</fullName>
            </value>
            <value>
                <fullName>AG Water Metering Installation</fullName>
            </value>
            <value>
                <fullName>Undocumented Source</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Work_Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Work_Type__c</fullName>
    <description>Type of work that this permit has requested for approval.</description>
    <label>Work Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Addition</fullName>
            </value>
            <value>
                <fullName>Alteration</fullName>
            </value>
            <value>
                <fullName>Demolition</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/recordTypes/Building.recordType-meta.xml
<RecordType>
    <fullName>Building</fullName>
    <active>false</active>
    <description>Permit related to a Building</description>
    <label>Building</label>
</RecordType>

force-app/main/default/classes/DepositAddControllerTest.cls
@isTest
private class DepositAddControllerTest
{
  private static MUSW__Deposit__c dep;
  private static MUSW__Deposit__c dep2;

  @isTest
  private static void testDepositAddTest()
  {
    setupTestData();

    // set page 
    PageReference depositAddPage = Page.DepositAdd;
    depositAddPage.getParameters().put('depositIds', dep.Id + ',' + dep2.Id);
    Test.setCurrentPage(depositAddPage);
    ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(new List<MUSW__Deposit__c>{dep,dep2});
    DepositAddController dtc = new DepositAddController(ssc);
    System.assertNotEquals(null,dtc.initOrder());
    System.assertNotEquals(null,dtc);
  }

  /**
    *   Preparation of the test data
    */
    @testSetup
    private static void setupTestData() {
        try{

           MUSW__Permit2__c testPermit = new MUSW__Permit2__c(MUSW__Type__c='Building',MUSW__Work_Type__c='New', AVO_Volumetric_Limits__c = 10);
          insert testPermit;

          MUSW__Deposit__c deposit = new MUSW__Deposit__c(MUSW__Amount__c=5000, MUSW__Permit2__c = testPermit.Id);
          insert deposit;

          MUSW__Deposit__c deposit2 = new MUSW__Deposit__c(MUSW__Amount__c=5000, MUSW__Permit2__c = testPermit.Id,MUSW__Transfered_In_Amount__c=4000);
          insert deposit2;

          dep = deposit;
          dep2 = deposit2;
        }
        catch(Exception ex){
            throw ex;
        }
    }
}