force-app/main/default/objects/MUSW__Deposit__c/MUSW__Deposit__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <label>Deposit</label>
    <nameField>
        <label>Deposit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deposits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Deposit__c/fields/MUSW__Amount__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Amount__c</fullName>
    <description>The total Amount that needs to be collected.</description>
    <label>Required Amount</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MUSW__Deposit__c/fields/MUSW__Available_Amount__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Available_Amount__c</fullName>
    <description>Total remaining amount available on the deposit.</description>
    <formula>MUSW__Paid_Amount__c - MUSW__Used_Amount__c - MUSW__Refunded_Amount__c - MUSW__Transfered_Out_Amount__c + MUSW__Transfered_In_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MUSW__Deposit__c/fields/MUSW__Permit2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Permit2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Permit</label>
    <referenceTo>MUSW__Permit2__c</referenceTo>
    <relationshipLabel>Deposits</relationshipLabel>
    <relationshipName>Deposits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Deposit__c/fields/MUSW__Transfered_In_Amount__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Transfered_In_Amount__c</fullName>
    <description>Total amount that has been transferred in to this deposit.</description>
    <label>Transfered In Amount</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MUSW__Deposit__c/fields/MUSW__Transfered_Out_Amount__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Transfered_Out_Amount__c</fullName>
    <description>Total amount that has been transferred out from this deposit.</description>
    <label>Transfered Out Amount</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MUSW__Deposit__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trust Account</fullName>
            </value>
            <value>
                <fullName>Cash Bond</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Deposit__c/fields/MUSW__Unpaid_Amount__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Unpaid_Amount__c</fullName>
    <description>Total outstanding amount that still needs to be collected.</description>
    <formula>IF((MUSW__Amount__c - MUSW__Paid_Amount__c - MUSW__Transfered_In_Amount__c) &lt; 0, 0, MUSW__Amount__c - MUSW__Paid_Amount__c - MUSW__Transfered_In_Amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unpaid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MUSW__Deposit__c/fields/MUSW__Used_Amount__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Used_Amount__c</fullName>
    <description>Total amount of the deposit that has been used to pay fees.</description>
    <label>Used Amount</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/MUSW__Permit2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Permit application details</description>
    <label>Permit</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_Volumetric_Limits__c.field-meta.xml
<CustomField>
    <fullName>AVO_Volumetric_Limits__c</fullName>
    <label>Volumetric Limits</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <description>The permit type. This is typically related to the record type.</description>
    <label>Type (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agricultural Surface Water Pump</fullName>
            </value>
            <value>
                <fullName>Agricultural Water Withdrawal Application</fullName>
            </value>
            <value>
                <fullName>Agricultural Water Withdrawal Permit</fullName>
            </value>
            <value>
                <fullName>Agricultural Well Pump</fullName>
            </value>
            <value>
                <fullName>Application for Permit Consolidation</fullName>
            </value>
            <value>
                <fullName>Revision</fullName>
            </value>
            <value>
                <fullName>Permit Relinquishment</fullName>
            </value>
            <value>
                <fullName>Well and Pump Data</fullName>
            </value>
            <value>
                <fullName>Well Plug and Abandonment</fullName>
            </value>
            <value>
                <fullName>AG Water Metering Installation</fullName>
            </value>
            <value>
                <fullName>Undocumented Source</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Work_Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Work_Type__c</fullName>
    <description>Type of work that this permit has requested for approval.</description>
    <label>Work Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Addition</fullName>
            </value>
            <value>
                <fullName>Alteration</fullName>
            </value>
            <value>
                <fullName>Demolition</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/recordTypes/Building.recordType-meta.xml
<RecordType>
    <fullName>Building</fullName>
    <active>false</active>
    <description>Permit related to a Building</description>
    <label>Building</label>
</RecordType>

force-app/main/default/classes/CartDepositsControllerTest.cls
@isTest
private class CartDepositsControllerTest
{
  private static MUSW__Deposit__c dep;
  private static MUSW__Deposit__c dep2;

  @isTest
  private static void testTopupDepositAmount()
  {
    setupTestData();

    MUSW__Deposit__c deposit =  [SELECT Id, MUSW__Amount__c,MUSW__Unpaid_Amount__c,MUSW__Transfered_In_Amount__c,MUSW__Used_Amount__c,MUSW__Available_Amount__c,MUSW__Transfered_Out_Amount__c FROM MUSW__Deposit__c WHERE Id = :dep.Id];

    // set page 
    pageReference depositAmountPage = Page.CartDeposits;
    depositAmountPage.getParameters().put('depositId', deposit.Id);
    Test.setCurrentPage(depositAmountPage);
    CartDepositsController dtc = new CartDepositsController();

    dtc.depositAmount = 6000;
    dtc.processDepositAmount();

    deposit =  [SELECT Id, MUSW__Amount__c,MUSW__Available_Amount__c FROM MUSW__Deposit__c WHERE Id = :dep.Id];

    System.assertEquals(6000,deposit.MUSW__Amount__c);
    System.assertEquals(0,deposit.MUSW__Available_Amount__c);
  }

  @isTest
  private static void testTopupDepositAmountWithTransferIn()
  {
    setupTestData();

    MUSW__Deposit__c deposit =  [SELECT Id, MUSW__Amount__c,MUSW__Unpaid_Amount__c,MUSW__Transfered_In_Amount__c,MUSW__Used_Amount__c,MUSW__Available_Amount__c,MUSW__Transfered_Out_Amount__c FROM MUSW__Deposit__c WHERE Id = :dep2.Id];

    // set page 
    pageReference depositAmountPage = Page.CartDeposits;
    depositAmountPage.getParameters().put('depositId', deposit.Id);
    Test.setCurrentPage(depositAmountPage);
    CartDepositsController dtc = new CartDepositsController();

    dtc.depositAmount = 3000;
    dtc.processDepositAmount();

    deposit =  [SELECT Id, MUSW__Amount__c,MUSW__Available_Amount__c FROM MUSW__Deposit__c WHERE Id = :dep2.Id];

    System.assertEquals(7000,deposit.MUSW__Amount__c);
    System.assertEquals(4000,deposit.MUSW__Available_Amount__c);
  }

  @isTest
  private static void testTopupDepositAWithoutAmount()
  {
    setupTestData();

    MUSW__Deposit__c deposit =  [SELECT Id, MUSW__Amount__c,MUSW__Unpaid_Amount__c,MUSW__Transfered_In_Amount__c,MUSW__Used_Amount__c,MUSW__Available_Amount__c,MUSW__Transfered_Out_Amount__c FROM MUSW__Deposit__c WHERE Id = :dep2.Id];

    // set page 
    pageReference depositAmountPage = Page.CartDeposits;
    depositAmountPage.getParameters().put('depositId', deposit.Id);
    Test.setCurrentPage(depositAmountPage);
    CartDepositsController dtc = new CartDepositsController();

    dtc.depositAmount = 0;
    dtc.processDepositAmount();

    ApexPages.Message[] pageMessages = ApexPages.getMessages();
    System.assertNotEquals(0, pageMessages.size());
    System.assert(pageMessages[0].getDetail().contains('Please enter an amount.'));
    dtc.goBack();
  }


  /**
    *   Preparation of the test data
    */
    @testSetup
    private static void setupTestData() {
        try{

           MUSW__Permit2__c testPermit = new MUSW__Permit2__c(MUSW__Type__c='Building',MUSW__Work_Type__c='New', AVO_Volumetric_Limits__c = 10);
          insert testPermit;

          MUSW__Deposit__c deposit = new MUSW__Deposit__c(MUSW__Amount__c=5000, MUSW__Permit2__c = testPermit.Id);
          insert deposit;

          MUSW__Deposit__c deposit2 = new MUSW__Deposit__c(MUSW__Amount__c=5000, MUSW__Permit2__c = testPermit.Id,MUSW__Transfered_In_Amount__c=4000);
          insert deposit2;

          dep = deposit;
          dep2 = deposit2;
        }
        catch(Exception ex){
            throw ex;
        }
    }
}