force-app/main/default/objects/MUSW__Deposit__c/MUSW__Deposit__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <label>Deposit</label>
    <nameField>
        <label>Deposit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deposits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Deposit__c/fields/MUSW__Amount__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Amount__c</fullName>
    <description>The total Amount that needs to be collected.</description>
    <label>Required Amount</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MUSW__Deposit__c/fields/MUSW__Available_Amount__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Available_Amount__c</fullName>
    <description>Total remaining amount available on the deposit.</description>
    <formula>MUSW__Paid_Amount__c - MUSW__Used_Amount__c - MUSW__Refunded_Amount__c - MUSW__Transfered_Out_Amount__c + MUSW__Transfered_In_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MUSW__Deposit__c/fields/MUSW__Transfered_In_Amount__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Transfered_In_Amount__c</fullName>
    <description>Total amount that has been transferred in to this deposit.</description>
    <label>Transfered In Amount</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MUSW__Deposit__c/fields/MUSW__Transfered_Out_Amount__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Transfered_Out_Amount__c</fullName>
    <description>Total amount that has been transferred out from this deposit.</description>
    <label>Transfered Out Amount</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MUSW__Deposit__c/fields/MUSW__Unpaid_Amount__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Unpaid_Amount__c</fullName>
    <description>Total outstanding amount that still needs to be collected.</description>
    <formula>IF((MUSW__Amount__c - MUSW__Paid_Amount__c - MUSW__Transfered_In_Amount__c) &lt; 0, 0, MUSW__Amount__c - MUSW__Paid_Amount__c - MUSW__Transfered_In_Amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unpaid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MUSW__Deposit__c/fields/MUSW__Used_Amount__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Used_Amount__c</fullName>
    <description>Total amount of the deposit that has been used to pay fees.</description>
    <label>Used Amount</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CartDepositsController.cls
public with sharing class CartDepositsController {

    public Decimal depositAmount { get; set; }
    public MUSW__Deposit__c currentDeposit { get; set; }

    public CartDepositsController() {
        Id depositId = System.currentPageReference().getParameters().get('depositId');
        currentDeposit = [SELECT Id, MUSW__Amount__c,MUSW__Unpaid_Amount__c,MUSW__Transfered_In_Amount__c,MUSW__Used_Amount__c,MUSW__Available_Amount__c,MUSW__Transfered_Out_Amount__c FROM MUSW__Deposit__c WHERE Id = :depositId];
        depositAmount = currentDeposit.MUSW__Amount__c;
    }

    public PageReference processDepositAmount(){

        if(depositAmount == 0) {
          ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please enter an amount.'));
          return null;
        }

        if(currentDeposit.MUSW__Transfered_In_Amount__c != null && currentDeposit.MUSW__Transfered_In_Amount__c > 0) {
            Decimal transfout = currentDeposit.MUSW__Transfered_Out_Amount__c==null?0:currentDeposit.MUSW__Transfered_Out_Amount__c;
            Decimal usedAmount = currentDeposit.MUSW__Used_Amount__c==null?0:currentDeposit.MUSW__Used_Amount__c;
            if(depositAmount > (currentDeposit.MUSW__Amount__c - (currentDeposit.MUSW__Available_Amount__c + transfout + usedAmount))) {
                currentDeposit.MUSW__Amount__c = depositAmount + currentDeposit.MUSW__Available_Amount__c + transfout + usedAmount;
                update currentDeposit;
            }
        } else {
            if(depositAmount > currentDeposit.MUSW__Unpaid_Amount__c) {
                currentDeposit.MUSW__Amount__c = currentDeposit.MUSW__Amount__c + (depositAmount - currentDeposit.MUSW__Unpaid_Amount__c);
                update currentDeposit;
            }
        }

        PageReference ret = Page.Cart;
        ret.setRedirect(true);
        ret.getParameters().put('depositId', currentDeposit.Id);
        ret.getParameters().put('retURL', System.currentPageReference().getParameters().get('retURL'));
        ret.getParameters().put('depositAccountId', System.currentPageReference().getParameters().get('depositAccountId'));
        ret.getParameters().put('id', System.currentPageReference().getParameters().get('id'));

        return ret;
    }
    
      /*
      * Go back to the deposit page
      */
      public PageReference goBack() {
        pageReference  pr = new pageReference('/'+currentDeposit.Id);
        pr.setredirect(true);
        return pr;  
      }
}