force-app/main/default/objects/MUSW__Permit2__c/MUSW__Permit2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Permit application details</description>
    <label>Permit</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_ActiveRefNo__c.field-meta.xml
<CustomField>
    <fullName>AVO_ActiveRefNo__c</fullName>
    <label>Active Reference Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_GIS_Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>AVO_GIS_Unique_ID__c</fullName>
    <label>GIS Unique ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_Inactive_Reason__c.field-meta.xml
<CustomField>
    <fullName>AVO_Inactive_Reason__c</fullName>
    <label>Inactive Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AVO_Inactive_Reason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>AVO_Transaction_Status__c</fullName>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AVO_Transaction_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>AVO_Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AVO_Transaction_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/Avo_Withdrawals__c.field-meta.xml
<CustomField>
    <fullName>Avo_Withdrawals__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Withdrawals</label>
    <referenceTo>AVO_Withdrawals__c</referenceTo>
    <relationshipLabel>Permits (Withdrawals)</relationshipLabel>
    <relationshipName>Permits1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <description>Status of the permit as it moves through the business workflow.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Submitted Documents</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Transaction</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Finaled</fullName>
            </value>
            <value>
                <fullName>Enforcement</fullName>
            </value>
            <value>
                <fullName>Initial Review</fullName>
            </value>
            <value>
                <fullName>LOC Package</fullName>
            </value>
            <value>
                <fullName>LOC Issued</fullName>
            </value>
            <value>
                <fullName>LOC Documents Uploaded</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Form Assessment</fullName>
            </value>
            <value>
                <fullName>Final Evaluation</fullName>
            </value>
            <value>
                <fullName>Permit Approval</fullName>
            </value>
            <value>
                <fullName>Revision Approval</fullName>
            </value>
            <value>
                <fullName>Ready for Issuance</fullName>
            </value>
            <value>
                <fullName>Permit Issued</fullName>
            </value>
            <value>
                <fullName>Revision Issued</fullName>
            </value>
            <value>
                <fullName>Issued</fullName>
            </value>
            <value>
                <fullName>Permit Rejected</fullName>
            </value>
            <value>
                <fullName>Consolidated</fullName>
            </value>
            <value>
                <fullName>Permit Denied</fullName>
            </value>
            <value>
                <fullName>Revision Denied</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Undocumented Source</fullName>
            </value>
            <value>
                <fullName>APPLICATION GIS MAPPING</fullName>
            </value>
            <value>
                <fullName>Undocumented Source Pending Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <description>The permit type. This is typically related to the record type.</description>
    <label>Type (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agricultural Surface Water Pump</fullName>
            </value>
            <value>
                <fullName>Agricultural Water Withdrawal Application</fullName>
            </value>
            <value>
                <fullName>Agricultural Water Withdrawal Permit</fullName>
            </value>
            <value>
                <fullName>Agricultural Well Pump</fullName>
            </value>
            <value>
                <fullName>Application for Permit Consolidation</fullName>
            </value>
            <value>
                <fullName>Revision</fullName>
            </value>
            <value>
                <fullName>Permit Relinquishment</fullName>
            </value>
            <value>
                <fullName>Well and Pump Data</fullName>
            </value>
            <value>
                <fullName>Well Plug and Abandonment</fullName>
            </value>
            <value>
                <fullName>AG Water Metering Installation</fullName>
            </value>
            <value>
                <fullName>Undocumented Source</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/recordTypes/Agricultural_Water_Withdrawal_Permit.recordType-meta.xml
<RecordType>
    <fullName>Agricultural_Water_Withdrawal_Permit</fullName>
    <active>true</active>
    <label>Agricultural Water Withdrawal Permit</label>
</RecordType>

force-app/main/default/objects/MUSW__Permit2__c/recordTypes/AVO_Agricultural_Water_Withdrawal_Application.recordType-meta.xml
<RecordType>
    <fullName>AVO_Agricultural_Water_Withdrawal_Application</fullName>
    <active>true</active>
    <label>Agricultural Water Withdrawal Application</label>
</RecordType>

force-app/main/default/objects/MUSW__Review__c/MUSW__Review__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Tracks the collaborative plan review process and associated documents</description>
    <label>Review</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Review__c/fields/AVO_Meter_Transaction__c.field-meta.xml
<CustomField>
    <fullName>AVO_Meter_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meter Transaction</label>
    <referenceTo>AVO_Meter_Transaction__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Review__c/fields/MUSW__Permit2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Permit2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Permit</label>
    <referenceTo>MUSW__Permit2__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Review__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <description>Current status of the review.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Required</fullName>
            </value>
            <value>
                <fullName>Additional Information Required</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Completed to LOC Package</fullName>
            </value>
            <value>
                <fullName>Completed to Form Assessment</fullName>
            </value>
            <value>
                <fullName>Completed to Final Evaluation</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
            <value>
                <fullName>Pending Wavier Approval</fullName>
                <label>Pending Waiver Approval</label>
            </value>
            <value>
                <fullName>Wavier Denied</fullName>
                <label>Waiver Denied</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Fail Back</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Review__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AG Program Manager Review</fullName>
                <label>Step 1 - AG Program Manager Approval</label>
            </value>
            <value>
                <fullName>Director Office Review</fullName>
            </value>
            <value>
                <fullName>Evaluation of Withdrawal 1st Cut</fullName>
            </value>
            <value>
                <fullName>Evaluation of Withdrawal 2nd Cut</fullName>
            </value>
            <value>
                <fullName>Irrigation Efficiency Cert Review</fullName>
            </value>
            <value>
                <fullName>Low Flow Protection Plan Review</fullName>
            </value>
            <value>
                <fullName>Special Appraisal</fullName>
            </value>
            <value>
                <fullName>Water Conservation Plan Review</fullName>
            </value>
            <value>
                <fullName>Water Reuse Visibility Study Review</fullName>
            </value>
            <value>
                <fullName>Water Shed Manager Review</fullName>
                <label>Step 3 - Water Shed Manager Approval</label>
            </value>
            <value>
                <fullName>Water Supply Manager Review</fullName>
                <label>Step 2 - Water Supply Manager Approval</label>
            </value>
            <value>
                <fullName>Well Data Form Review</fullName>
            </value>
            <value>
                <fullName>Completeness Review</fullName>
            </value>
            <value>
                <fullName>Waiver Review</fullName>
            </value>
            <value>
                <fullName>Withdrawal LOC Review</fullName>
            </value>
            <value>
                <fullName>Form Assessment Review</fullName>
            </value>
            <value>
                <fullName>Final Evaluation Review</fullName>
            </value>
            <value>
                <fullName>Meter Installation Review</fullName>
            </value>
            <value>
                <fullName>Requester Review</fullName>
            </value>
            <value>
                <fullName>Permitting Review</fullName>
            </value>
            <value>
                <fullName>Compliance Review</fullName>
            </value>
            <value>
                <fullName>Metering Review</fullName>
            </value>
            <value>
                <fullName>WWSA Review</fullName>
            </value>
            <value>
                <fullName>GIS Review</fullName>
            </value>
            <value>
                <fullName>Meter Review</fullName>
            </value>
            <value>
                <fullName>Step 5 - Director Approval</fullName>
            </value>
            <value>
                <fullName>Permit Management Review</fullName>
            </value>
            <value>
                <fullName>Step 4 - Deputy Director Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Review__c/recordTypes/AVO_Review_Default_Withdrawal_LOC_Review_Only.recordType-meta.xml
<RecordType>
    <fullName>AVO_Review_Default_Withdrawal_LOC_Review_Only</fullName>
    <active>true</active>
    <description>AVO Review Default - Withdrawal LOC Review Only</description>
    <label>AVO Review Default - Withdrawal LOC Review Only</label>
</RecordType>

force-app/main/default/globalValueSets/AVO_Inactive_Reason.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Duplicate</fullName>
    </customValue>
    <customValue>
        <fullName>Never Installed</fullName>
    </customValue>
    <customValue>
        <fullName>Non AG Use/Other Applciation</fullName>
    </customValue>
    <customValue>
        <fullName>Voluntarily Relinquished</fullName>
    </customValue>
    <customValue>
        <fullName>Consolidated Permit</fullName>
    </customValue>
    <customValue>
        <fullName>New Well/Pump not Installed</fullName>
    </customValue>
    <customValue>
        <fullName>Ag SW Currently Unused</fullName>
    </customValue>
    <customValue>
        <fullName>AG GW Currently Unused</fullName>
    </customValue>
    <customValue>
        <fullName>AG WTP Currently Unused</fullName>
    </customValue>
    <customValue>
        <fullName>Revoked</fullName>
    </customValue>
    <customValue>
        <fullName>Dormant at permitee Request</fullName>
    </customValue>
    <customValue>
        <fullName>Plugged/Abandoned</fullName>
    </customValue>
    <customValue>
        <fullName>Expired LOC</fullName>
    </customValue>
    <customValue>
        <fullName>Incomplete Form</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Compliance Case</fullName>
    </customValue>
    <customValue>
        <fullName>Applicant Request</fullName>
    </customValue>
    <customValue>
        <fullName>GPMS Under Permitting Capacity</fullName>
    </customValue>
    <customValue>
        <fullName>Merged to an existing application/permit</fullName>
    </customValue>
    <customValue>
        <fullName>Not Waters of the State</fullName>
    </customValue>
    <customValue>
        <fullName>No Longer Present</fullName>
    </customValue>
    <customValue>
        <fullName>Transfer Pump Only</fullName>
    </customValue>
    <customValue>
        <fullName>Application Denied</fullName>
    </customValue>
    <masterLabel>AVO Inactive Reason</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/AVO_Transaction_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>To Be Updated</fullName>
    </customValue>
    <customValue>
        <fullName>To Be Transferred</fullName>
    </customValue>
    <customValue>
        <fullName>To Be Corrected</fullName>
    </customValue>
    <customValue>
        <fullName>To Be Modified</fullName>
    </customValue>
    <customValue>
        <fullName>To Be Relinquished</fullName>
    </customValue>
    <customValue>
        <fullName>To Be Revoked</fullName>
    </customValue>
    <customValue>
        <fullName>Updated</fullName>
    </customValue>
    <customValue>
        <fullName>Transferred</fullName>
    </customValue>
    <customValue>
        <fullName>Corrected</fullName>
    </customValue>
    <customValue>
        <fullName>Modified</fullName>
    </customValue>
    <customValue>
        <fullName>Relinquished</fullName>
    </customValue>
    <customValue>
        <fullName>Revoked</fullName>
    </customValue>
    <customValue>
        <fullName>To Be Modified &amp; Transferred</fullName>
    </customValue>
    <customValue>
        <fullName>Modified &amp; Transferred</fullName>
    </customValue>
    <customValue>
        <fullName>To Be Consolidated</fullName>
    </customValue>
    <customValue>
        <fullName>Consolidated</fullName>
    </customValue>
    <customValue>
        <fullName>To Be Split</fullName>
    </customValue>
    <customValue>
        <fullName>Split</fullName>
    </customValue>
    <customValue>
        <fullName>To Be Unrevoked</fullName>
    </customValue>
    <customValue>
        <fullName>Unrevoked</fullName>
    </customValue>
    <customValue>
        <fullName>To Be Corrected &amp; Transferred</fullName>
    </customValue>
    <customValue>
        <fullName>Corrected &amp; Transferred</fullName>
    </customValue>
    <customValue>
        <fullName>To Be Modified &amp; Updated</fullName>
    </customValue>
    <customValue>
        <fullName>Modified &amp; Updated</fullName>
    </customValue>
    <customValue>
        <fullName>New</fullName>
    </customValue>
    <customValue>
        <fullName>Application</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled Must reapply</fullName>
    </customValue>
    <customValue>
        <fullName>To be Updated &amp; Transferred</fullName>
    </customValue>
    <masterLabel>AVO Transaction Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/AVO_Transaction_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Modify Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Transfer Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Relinquish Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Revoke Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Split Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Update Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Modify &amp; Transfer Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Modify &amp; Update Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Correct Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Unrevoke Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Undocumented Source</fullName>
    </customValue>
    <customValue>
        <fullName>External Correspondence</fullName>
    </customValue>
    <customValue>
        <fullName>Application</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled Must Reapply</fullName>
    </customValue>
    <customValue>
        <fullName>Correct &amp; Transfer Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Permit History</fullName>
    </customValue>
    <customValue>
        <fullName>Consolidate Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>AVO Transaction Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AvoConsolidate.cls
public with sharing class AvoConsolidate {
    @InvocableMethod(label= 'Consolidate' description = 'Consolidates a record into a retained record. Can be App to App, App to Perm, or Perm to Perm')
    public static List<ID> consolidateRecord(List<ConsolidationReq> reqs) {
        // Record Type IDs
        ID WITHDRAWAL_APP_REC_TYPE_ID = Schema.SObjectType.MUSW__Review__c.getRecordTypeInfosByDeveloperName()
            .get('AVO_Agricultural_Water_Withdrawal_Application')?.getRecordTypeId();
        if (WITHDRAWAL_APP_REC_TYPE_ID == null) {
            System.debug('Error: AVO_Agricultural_Water_Withdrawal_Application record type not found');
        }

        ID WITHDRAWAL_PERMIT_REC_TYPE_ID = Schema.SObjectType.MUSW__Review__c.getRecordTypeInfosByDeveloperName()
            .get('Agricultural_Water_Withdrawal_Permit')?.getRecordTypeId();
        if (WITHDRAWAL_PERMIT_REC_TYPE_ID == null) {
            System.debug('Error: Agricultural_Water_Withdrawal_Permit record type not found');
        }

        ID LOC_REVIEW_REC_TYPE_ID = Schema.SObjectType.MUSW__Review__c.getRecordTypeInfosByDeveloperName()
            .get('AVO_Review_Default_Withdrawal_LOC_Review_Only')?.getRecordTypeId();
        if (LOC_REVIEW_REC_TYPE_ID == null) {
            System.debug('Error: AVO_Review_Default_Withdrawal_LOC_Review_Only record type not found');
        }

        List<MUSW__Permit2__c> permitsToUpdate = new List<MUSW__Permit2__c>();
        List<AVO_Withdrawals__c> withdrawalsToUpdate = new List<AVO_Withdrawals__c>();
        List<AVO_Meter_Transaction__c> metersToUpdate = new List<AVO_Meter_Transaction__c>();
        List<MUSW__Review__c> reviewsToUpdate = new List<MUSW__Review__c>();
        List<Task> tasksToUpdate = new List<Task>();
        List<ID> keptIDs = new List<ID>();
        List<String> reviewTypes = new List<String>();

        for (ConsolidationReq request : reqs) {
            System.debug('Processing request: ' + request);
            
            if (request.recordIdToKeep == null || request.recordIdToConsolidate == null) {
                System.debug('Error: One of the record IDs is null. recordIdToKeep: ' + request.recordIdToKeep + ' recordIdToConsolidate: ' + request.recordIdToConsolidate);
                continue;
            }
            
            keptIDs.add(request.recordIdToKeep);
            String consolidateObjectName = request.recordIdToConsolidate.getSObjectType().getDescribe().getName();
            
            // Query permit records
            List<MUSW__Permit2__c> permitToKeepList = [SELECT ID, Name, recordTypeId, MUSW__Status__c, AVO_Transaction_Type__c, AVO_GIS_Unique_ID__c, MUSW__Type__c
                                                       FROM MUSW__Permit2__c WHERE ID IN (:request.recordIdToKeep)];
            List<MUSW__Permit2__c> permitToConsolidateList = [SELECT ID, Name, recordTypeId, AVO_Transaction_Type__c, AVO_Inactive_Reason__c, AVO_ActiveRefNo__c
                                                           FROM MUSW__Permit2__c WHERE ID IN (:request.recordIdToConsolidate)];

            if (permitToKeepList.isEmpty() || permitToConsolidateList.isEmpty()) {
                System.debug('Error: One of the permit records is missing. permitToKeepList: ' + permitToKeepList + ' permitToConsolidateList: ' + permitToConsolidateList);
                continue;
            }
            
            MUSW__Permit2__c permitToKeep = permitToKeepList[0];
            MUSW__Permit2__c permitToConsolidate = permitToConsolidateList[0];

            System.debug('Consolidating ' + permitToConsolidate + ' into ' + permitToKeep);

            // Logic for the permit to keep
            if (permitToKeep.recordTypeId == WITHDRAWAL_PERMIT_REC_TYPE_ID) {
                System.debug('Permit to keep is a permit');
                if (permitToKeep.MUSW__Status__c == 'Form Assesment' || permitToKeep.MUSW__Status__c == 'Final Evaluation') {
                    permitToKeep.MUSW__Status__c = 'In Review';
                    System.debug('in final eval if');
                }
                permitToKeep.MUSW__Status__c = 'In Review';
                permitToKeep.AVO_Transaction_Type__c = 'New Permit';
            }
            if (permitToKeep.recordTypeId == WITHDRAWAL_APP_REC_TYPE_ID) {
                System.debug('Permit to keep is an application');
                if (!(permitToKeep.MUSW__Status__c == 'Pending' || permitToKeep.MUSW__Status__c == 'Submitted')) {
                    if (permitToKeep.MUSW__Status__c == 'In Review') {
                        reviewTypes.add('Withdrawal LOC Review');
                    }
                    else {
                        permitToKeep.MUSW__Status__c = 'In Review';
                    }
                }
                
                permitToKeep.AVO_Transaction_Type__c = 'New Permit';
            }

            // Logic for the permit to consolidate
            if (permitToConsolidate.recordTypeId == WITHDRAWAL_PERMIT_REC_TYPE_ID) {
                System.debug('Permit to consolidate is a permit');
                permitToConsolidate.AVO_Transaction_Type__c = 'Consolidate Permit';
                permitToConsolidate.AVO_Transaction_Status__c = 'To Be Consolidated';
                permitToConsolidate.AVO_Inactive_Reason__c = 'Consolidated Permit';
                permitToConsolidate.AVO_ActiveRefNo__c = permitToKeep.Id;
                permitToConsolidate.MUSW__Status__c = 'Consolidated';
            }
            if (permitToConsolidate.recordTypeId == WITHDRAWAL_APP_REC_TYPE_ID) {
                System.debug('Permit to consolidate is an application');
                permitToConsolidate.AVO_Transaction_Type__c = 'New Permit';
                permitToConsolidate.AVO_Permit_Closed_Status__c = 'Cancelled Application';
                permitToConsolidate.AVO_Inactive_Reason__c = 'Merged to an existing application/permit';
                permitToConsolidate.AVO_ActiveRefNo__c = permitToKeep.Id;
                permitToConsolidate.MUSW__Status__c = 'Consolidated';
            }

            // Fail Back reviews 
            List<MUSW__Review__c> LOCReviews = [SELECT Name, ID, MUSW__Status__c FROM MUSW__Review__c WHERE MUSW__Permit2__c = :permitToKeep.Id
                                                 AND MUSW__Type__c IN ('Withdrawal LOC Review', 'Form Assessment Review', 'Final Evaluation Review', 'Metering Review', 'Waiver Review')];
            if (LOCReviews.isEmpty()) {
                System.debug('No reviews found for permitToKeep');
            } else {
                for (MUSW__Review__c review : LOCReviews) {
                    review.MUSW__Status__c = 'Fail Back';
                }
                reviewsToUpdate.addAll(LOCReviews);
            }

            // Create new reviews
            AvoProcessEnginePermit process = new AvoProcessEnginePermit(permitToKeep);
            System.debug('Creating reviews');
            process.createReview(reviewTypes);
            System.debug('Created ' + reviewTypes + ' reviews');

            // Set old GIS tasks to cancelled
            List<Task> oldTasks = [SELECT ID, Status, WhatId FROM Task WHERE WhatId = :permitToKeep.Id];
            for (Task t : oldTasks) {
                t.Status = 'Denied';
            }
            tasksToUpdate.addAll(oldTasks);

            // Create GIS Task
            process.createTask(new AVO_Process_State_Post_Actions__c(Avo_Task_Type__c = 'GIS Application Mapping'));
            System.debug('creating GIS Application Mapping');

			// 130 commented by Adithya 
            //withdrawalsToUpdate.addAll(consolidateWithdrawals(permitToConsolidate.Id, permitToKeep));
            metersToUpdate.addAll(consolidateMeterTransaction(permitToConsolidate.Id, permitToKeep));

            permitsToUpdate.add(permitToConsolidate);
            permitsToUpdate.add(permitToKeep);
        }

        // Final update operations
        try {
            update withdrawalsToUpdate;
            update metersToUpdate;
            update permitsToUpdate;
            update reviewsToUpdate;
            update tasksToUpdate;
        } catch (Exception e) {
            System.debug('Error during update operations: ' + e.getMessage());
        }

        return keptIDs;
    }
// 150 to 168 commented by Adithya 
  /*  public static List<AVO_Withdrawals__c> consolidateWithdrawals(ID oldPermitID, MUSW__Permit2__c newPermit) {
        List<AVO_Withdrawals__c> updatedWithdrawals = new List<AVO_Withdrawals__c>();
        List<AVO_Withdrawals__c> relatedWithdrawals = [SELECT ID, App_ID__c, AVO_Permit__c, AVO_Well_Number__c, AVO_GIS_UNIQUE__c, AVO_Well_Status__c, AVO_Pump_Activity_Use__c
            FROM AVO_Withdrawals__c WHERE AVO_Permit__c = :oldPermitID];
        
        if (relatedWithdrawals.isEmpty()) {
            System.debug('No related withdrawals found for old permit: ' + oldPermitID);
        }

        for (AVO_Withdrawals__c withdrawal : relatedWithdrawals) {
            withdrawal.App_ID__c = newPermit.ID;
            withdrawal.AVO_Permit__c = newPermit.ID;
            withdrawal.AVO_GIS_UNIQUE__c = newPermit.AVO_GIS_Unique_ID__c;
            withdrawal.AVO_Well_Status__c = 'Permit/App Consolidated';
            withdrawal.AVO_Pump_Activity_Use__c = 'Inactive';
            updatedWithdrawals.add(withdrawal);
        }
        return updatedWithdrawals;
    }*/

    public static List<AVO_Meter_Transaction__c> consolidateMeterTransaction(ID oldPermitID, MUSW__Permit2__c newPermit) {
        List<AVO_Meter_Transaction__c> updatedMeterTransaction = new List<AVO_Meter_Transaction__c>();
        List<AVO_Meter_Transaction__c> relatedMeterTransaction = [SELECT ID, AVO_Application_Number__c, AVO_Permit_Number__c
            FROM AVO_Meter_Transaction__c WHERE AVO_Application_Number__c = :oldPermitID OR AVO_Permit_Number__c = :oldPermitID];
        
        if (relatedMeterTransaction.isEmpty()) {
            System.debug('No related meter transactions found for old permit: ' + oldPermitID);
        }

        for (AVO_Meter_Transaction__c meter : relatedMeterTransaction) {
            if (meter.AVO_Application_Number__c == oldPermitID) {
                meter.AVO_Application_Number__c = newPermit.ID;
            }
            if (meter.AVO_Permit_Number__c == oldPermitID) {
                meter.AVO_Permit_Number__c = newPermit.ID;
            }
            updatedMeterTransaction.add(meter);
        }
        return updatedMeterTransaction;
    }

    public class ConsolidationReq {
        @InvocableVariable(label = 'RecordId To Keep' description = 'The ID of record that is being kept' required = true)
        public ID recordIdToKeep;

        @InvocableVariable(label = 'RecordId To Consolidate' description = 'The ID of record that is being consolidated' required = true)
        public ID recordIdToConsolidate;
    }
}