force-app/main/default/objects/MUSW__Parcel__c/MUSW__Parcel__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Property parcel information</description>
    <label>Parcel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Parcel__c/fields/External_Parcel__c.field-meta.xml
<CustomField>
    <fullName>External_Parcel__c</fullName>
    <label>External Parcel</label>
    <length>18</length>
    <referenceTo>TEST_Parcels__x</referenceTo>
    <relationshipLabel>Parcels</relationshipLabel>
    <relationshipName>Parcels</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Parcel__c/fields/MUSW__Parcel_Number2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Parcel_Number2__c</fullName>
    <description>Unique parcel identification number.</description>
    <externalId>true</externalId>
    <label>Parcel Number</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MUSW__Parcel__c/fields/UNIQUEID__c.field-meta.xml
<CustomField>
    <fullName>UNIQUEID__c</fullName>
    <externalId>true</externalId>
    <label>UNIQUEID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/MUSW__Permit2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Permit application details</description>
    <label>Permit</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Permit2__c/fields/Avo_Skip_Process_Engine__c.field-meta.xml
<CustomField>
    <fullName>Avo_Skip_Process_Engine__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Process Engine</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Account__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the associated permit account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Permits as Account</relationshipLabel>
    <relationshipName>Permits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Applicant__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The applicant submitting the permit application.</description>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Permits as Applicant</relationshipLabel>
    <relationshipName>Applicant_Permit2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Parcel__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Parcel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated parcel or address of the permit.</description>
    <label>Parcel</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MUSW__Parcel__c.MUSW__Historic__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>MUSW__Parcel__c</referenceTo>
    <relationshipLabel>Permits</relationshipLabel>
    <relationshipName>Permit2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <description>Status of the permit as it moves through the business workflow.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Submitted Documents</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Transaction</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Finaled</fullName>
            </value>
            <value>
                <fullName>Enforcement</fullName>
            </value>
            <value>
                <fullName>Initial Review</fullName>
            </value>
            <value>
                <fullName>LOC Package</fullName>
            </value>
            <value>
                <fullName>LOC Issued</fullName>
            </value>
            <value>
                <fullName>LOC Documents Uploaded</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Form Assessment</fullName>
            </value>
            <value>
                <fullName>Final Evaluation</fullName>
            </value>
            <value>
                <fullName>Permit Approval</fullName>
            </value>
            <value>
                <fullName>Revision Approval</fullName>
            </value>
            <value>
                <fullName>Ready for Issuance</fullName>
            </value>
            <value>
                <fullName>Permit Issued</fullName>
            </value>
            <value>
                <fullName>Revision Issued</fullName>
            </value>
            <value>
                <fullName>Issued</fullName>
            </value>
            <value>
                <fullName>Permit Rejected</fullName>
            </value>
            <value>
                <fullName>Consolidated</fullName>
            </value>
            <value>
                <fullName>Permit Denied</fullName>
            </value>
            <value>
                <fullName>Revision Denied</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Undocumented Source</fullName>
            </value>
            <value>
                <fullName>APPLICATION GIS MAPPING</fullName>
            </value>
            <value>
                <fullName>Undocumented Source Pending Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <description>The permit type. This is typically related to the record type.</description>
    <label>Type (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agricultural Surface Water Pump</fullName>
            </value>
            <value>
                <fullName>Agricultural Water Withdrawal Application</fullName>
            </value>
            <value>
                <fullName>Agricultural Water Withdrawal Permit</fullName>
            </value>
            <value>
                <fullName>Agricultural Well Pump</fullName>
            </value>
            <value>
                <fullName>Application for Permit Consolidation</fullName>
            </value>
            <value>
                <fullName>Revision</fullName>
            </value>
            <value>
                <fullName>Permit Relinquishment</fullName>
            </value>
            <value>
                <fullName>Well and Pump Data</fullName>
            </value>
            <value>
                <fullName>Well Plug and Abandonment</fullName>
            </value>
            <value>
                <fullName>AG Water Metering Installation</fullName>
            </value>
            <value>
                <fullName>Undocumented Source</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/recordTypes/All.recordType-meta.xml
<RecordType>
    <fullName>All</fullName>
    <active>false</active>
    <label>All</label>
</RecordType>

force-app/main/default/objects/MUSW__Permit2__c/recordTypes/Building.recordType-meta.xml
<RecordType>
    <fullName>Building</fullName>
    <active>false</active>
    <description>Permit related to a Building</description>
    <label>Building</label>
</RecordType>

force-app/main/default/objects/MUSW__Permit2__c/recordTypes/Electrical.recordType-meta.xml
<RecordType>
    <fullName>Electrical</fullName>
    <active>false</active>
    <description>Permit related to Electrical work</description>
    <label>Electrical</label>
</RecordType>

force-app/main/default/objects/MUSW__Permit2__c/recordTypes/Plumbing.recordType-meta.xml
<RecordType>
    <fullName>Plumbing</fullName>
    <active>false</active>
    <description>Permit related to Plumbing work</description>
    <label>Plumbing</label>
</RecordType>

force-app/main/default/objects/MUSW__Submission__c/MUSW__Submission__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Tracks online files</description>
    <label>Submission</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Submission__c/fields/MUSW__Permit2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Permit2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Permit</label>
    <referenceTo>MUSW__Permit2__c</referenceTo>
    <relationshipLabel>Submissions</relationshipLabel>
    <relationshipName>Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Submission__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AvoPermitTriggerHandler.cls
/**
 * Description of class
 * trigger proxy for reviews
 * @author Jason Li
 * last modified by Jason Li
 * @date 06/24/2021
 *  
 */
public class AvoPermitTriggerHandler extends AvoTriggerHandler { 

    public override void beforeInsert() {
        for(MUSW__Permit2__c permit : (List<MUSW__Permit2__c>) Trigger.new) { 
           System.debug('before');
           System.debug(permit);
           //moveToSubmittedOnBackofficeCreation(permit);
           //setParkingPermitApplicant(permit);
           setInstanceAccountForPayment(permit);
        }
    }

    public override void afterInsert() {
        for(MUSW__Permit2__c permit : (List<MUSW__Permit2__c>) Trigger.new) { 
            if (permit.Avo_Skip_Process_Engine__c == false) {
                AvoProcessEnginePermit avoProcessPermitEngine = new AvoProcessEnginePermit(permit);
                avoProcessPermitEngine.createPostTransitionActions();
                if (avoProcessPermitEngine.hasError() == true){
                    permit.addError(avoProcessPermitEngine.getError());
                }
            }
          
            System.Debug('trigger from after insert');                  
            handlePermitSubmittedStatusAutoTransition(permit);
        }
    }

    public override void beforeUpdate() {
        for(MUSW__Permit2__c permit : (List<MUSW__Permit2__c>) Trigger.new) { 
            MUSW__Permit2__c oldPermit = (MUSW__Permit2__c)Trigger.oldMap.get(permit.Id);
            string oldPermitStatus =  oldPermit.MUSW__Status__c;
            string newPermitStatus =  permit.MUSW__Status__c;
            //setParkingPermitApplicant(permit);
            System.debug('From ' + oldPermit.MUSW__Status__c + ' ' + permit.MUSW__Status__c);
            if (permit.MUSW__Status__c <> oldPermit.MUSW__Status__c){
                handlePendingStatusSubmissions(permit);
                // permit status has changed
                AvoProcessEnginePermit avoProcessPermitEngine = new AvoProcessEnginePermit(permit);

                system.debug('started the process engine from a permit');
                if (avoProcessPermitEngine.isStatusChangeAllowed() == false){
                     permit.addError('Change from [' + oldPermitStatus + '] to [' + newPermitStatus + '] is not allowed.' + avoProcessPermitEngine.getError());
                }else {
                    system.debug('all conditions are met, starting creating post transition actions');
                    avoProcessPermitEngine.createPostTransitionActions();
                }

            }  
        }
    }   

    public override void afterUpdate() {
        for(MUSW__Permit2__c permit : (List<MUSW__Permit2__c>) Trigger.new) { 
            MUSW__Permit2__c oldPermit = (MUSW__Permit2__c)Trigger.oldMap.get(permit.Id);
           
            if (permit.MUSW__Parcel__c != null && permit.MUSW__Parcel__c != oldPermit.MUSW__Parcel__c) {
                Id parcelId = permit.MUSW__Parcel__c;

                System.debug('parcelId '+ permit.MUSW__Parcel__c);
                
                if (parcelId != null) {
                    try {
                        // get the parcel for lookup in the GIS system
                        System.debug('inside try parcelId ' + parcelId);
                        MUSW__Parcel__c parcel = [
                            SELECT Id, Name, MUSW__Parcel_Number2__c, External_Parcel__c, UNIQUEID__c
                            FROM MUSW__Parcel__C 
                            WHERE Id = :parcelId
                        ];
                        // get the info from the gis system and add it to the permit
                        //AvoAccGis.addGisDataToPermit(parcel.MUSW__Parcel_Number2__c, permit.Id);
    
                    }  catch(Exception e){ 
                        // there is likely no parcel that exists in the parcels yet.
                        //new AvoLogException().Log(new AvoCustomException(e));
                    }
                }
            }

            if (permit.MUSW__Status__c <> oldPermit.MUSW__Status__c){
                handlePermitSubmittedStatusAutoTransition(permit);
                //handlePUDFees(permit);
            }
        }
    }
    

    public void moveToSubmittedOnBackofficeCreation(MUSW__Permit2__c permit) {
        System.debug('Move status');
        System.debug(permit);
       
        //9526: Pending Status is not reelevant, move to submitted when creating from back office
        User userDetails =[SELECT Id, Name, Email, Profile.Name, UserRole.Name FROM User where Id=:permit.OwnerId ];
        System.debug('Profile name: ' + userDetails.Profile.Name);
        System.debug('Profile name Index: ' + userDetails.Profile.Name.indexOf('Community'));
        
        if (!string.isBlank(userDetails.Profile.Name) && userDetails.Profile.Name.indexOf('Community') == -1 ) {

            if (permit.MUSW__Type__c == 'Land Disturbance' ||
            permit.MUSW__Type__c == 'Stormwater Management' ||
            permit.MUSW__Type__c == 'Right of Way Encroachment' ||
            permit.MUSW__Type__c == 'Roadway Construction' ||
            permit.MUSW__Type__c == 'Non-Residential Driveway' ||
            permit.MUSW__Type__c == 'Floodplain Construction') {
                permit.MUSW__Status__c = 'In Review';
            } else {
                permit.MUSW__Status__c = 'Submitted';
            }

        }
    }
    
    public void handlePendingStatusSubmissions(MUSW__Permit2__c permit) {
        if (permit.MUSW__Status__c == 'Pending') {
            List<MUSW__Submission__c> submissions = [
                SELECT Id, (SELECT Id, Title from CombinedAttachments) 
                from MUSW__Submission__c
                Where MUSW__Permit2__c = :permit.id
            ];

            if (submissions.size() > 0) {
                for(MUSW__Submission__c item: submissions) {
                    if (item.CombinedAttachments.size() == 0) {
                        delete item;
                    }
                }
            }
        }
    }

    public void setInstanceAccountForPayment(MUSW__Permit2__c permit) {
        if (permit.MUSW__Applicant__r.AccountId != null && permit.MUSW__Account__c == null) {
            permit.MUSW__Account__c = permit.MUSW__Applicant__r.AccountId;
        }
    }

    public void handlePermitSubmittedStatusAutoTransition(MUSW__Permit2__c permit) {

        MUSW__Permit2__c queryPermit = [SELECT MUSW__Status__c
        FROM MUSW__Permit2__c
        WHERE Id = :permit.id
        LIMIT 1];

        if (queryPermit != null) {

            String applicablePermitTypes = 'Building Relocation Permit;Manufactured Home Permit;Demolition Permit;Electrical Permit;Plumbing Permit;Gas Permit;HVAC Permit;Multi-Family Building Permit;' +
            'Commercial Building Permit;Residential Building Permit;Fireplace Stove;Water and Sewer Permit;Secured Structure Permit;Sign Permit;Swimming Pool Permit;' +
            'Temporary Fire Hydrant;Temporary Secured Structure Permit;Temporary Tent;Multi-Permit Application;PUD Utility Extension;Small Cell;Residential Driveway';

            System.Debug('Passed in: ' + permit.MUSW__Type__c + ' ' + applicablePermitTypes.contains(permit.MUSW__Type__c));
            
            if (applicablePermitTypes.contains(permit.MUSW__Type__c) && permit.MUSW__Status__c == 'Submitted') {
                queryPermit.MUSW__Status__c = 'Initial Review';
                update queryPermit;
            }
        }
    }

        
    }