force-app/main/default/objects/AVO_Process_State_Transition_Stopper__c/AVO_Process_State_Transition_Stopper__c.object-meta.xml
<CustomObject>
    <label>Process State Transition Stopper</label>
    <nameField>
        <displayFormat>TT-{00000}</displayFormat>
        <label>Transition Condition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process State Transition Stoppers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Process_State_Transition_Stopper__c/fields/Avo_Deposit_Status__c.field-meta.xml
<CustomField>
    <fullName>Avo_Deposit_Status__c</fullName>
    <label>Deposit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>fully paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition_Stopper__c/fields/Avo_Fee_Status__c.field-meta.xml
<CustomField>
    <fullName>Avo_Fee_Status__c</fullName>
    <label>Fee Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>fully paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition_Stopper__c/fields/Avo_Inspection_Result__c.field-meta.xml
<CustomField>
    <fullName>Avo_Inspection_Result__c</fullName>
    <label>Inspection Result</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Inspection_Result</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition_Stopper__c/fields/Avo_Milestone_Completed_Action__c.field-meta.xml
<CustomField>
    <fullName>Avo_Milestone_Completed_Action__c</fullName>
    <label>Milestone Completed Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Milestone_Completed_Actions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition_Stopper__c/fields/Avo_Review_Status__c.field-meta.xml
<CustomField>
    <fullName>Avo_Review_Status__c</fullName>
    <label>Review Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Review_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition_Stopper__c/fields/Avo_Status__c.field-meta.xml
<CustomField>
    <fullName>Avo_Status__c</fullName>
    <label>Status / Result</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition_Stopper__c/fields/Avo_Submission_Status__c.field-meta.xml
<CustomField>
    <fullName>Avo_Submission_Status__c</fullName>
    <label>Submission Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Submission_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition_Stopper__c/fields/Avo_Submission_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Submission_Type__c</fullName>
    <label>Submission Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Submission_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Avo_Inspection_Result.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
        <default>true</default>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>All Conditions met, OK to refund deposit</fullName>
    </customValue>
    <customValue>
        <fullName>Conditions outstanding, do not refund deposit until met</fullName>
    </customValue>
    <customValue>
        <fullName>Action needed, do not refund deposit until met</fullName>
    </customValue>
    <customValue>
        <fullName>Penalties/Fines to be assessed</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <masterLabel>Avo Inspection Result</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Avo_Milestone_Completed_Actions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Corrections Required</fullName>
    </customValue>
    <masterLabel>Avo Milestone Completed Actions</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Avo_Review_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Denied</fullName>
    </customValue>
    <customValue>
        <fullName>Required</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Information</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Wavier Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Completed to LOC Package</fullName>
    </customValue>
    <customValue>
        <fullName>Completed to Final Evaluation</fullName>
    </customValue>
    <customValue>
        <fullName>Completed to Form Assessment</fullName>
    </customValue>
    <customValue>
        <fullName>Fail Back</fullName>
    </customValue>
    <masterLabel>Avo Review Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Avo_Submission_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <masterLabel>Submission Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Avo_Submission_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acknowledgment Letter</fullName>
    </customValue>
    <customValue>
        <fullName>Administrative Order</fullName>
    </customValue>
    <customValue>
        <fullName>Aerial Imagery Map</fullName>
    </customValue>
    <customValue>
        <fullName>Agric Water Reuse Feasibility Study</fullName>
    </customValue>
    <customValue>
        <fullName>Agric Water Right Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>AG SW Pump Information Form</fullName>
    </customValue>
    <customValue>
        <fullName>AG Well Data Sheet</fullName>
    </customValue>
    <customValue>
        <fullName>All Submissions</fullName>
    </customValue>
    <customValue>
        <fullName>Any Submission</fullName>
    </customValue>
    <customValue>
        <fullName>Application Attestation Form</fullName>
    </customValue>
    <customValue>
        <fullName>Application Form</fullName>
    </customValue>
    <customValue>
        <fullName>Application Map</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Notes</fullName>
    </customValue>
    <customValue>
        <fullName>Bill of Sale</fullName>
    </customValue>
    <customValue>
        <fullName>Compliance Document</fullName>
    </customValue>
    <customValue>
        <fullName>Consent Order</fullName>
    </customValue>
    <customValue>
        <fullName>Consolidated Conservation Plan</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Photos of the Meter (Including Serial Number)</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Photos of the Meter (Installation with surroudning piping)</fullName>
    </customValue>
    <customValue>
        <fullName>Expired LOC Document</fullName>
    </customValue>
    <customValue>
        <fullName>Expiring LOC Document</fullName>
    </customValue>
    <customValue>
        <fullName>Flow Meter Approval Form</fullName>
    </customValue>
    <customValue>
        <fullName>GeoEval Sheet Page 1</fullName>
    </customValue>
    <customValue>
        <fullName>GeoEval Sheet Page 2</fullName>
    </customValue>
    <customValue>
        <fullName>Incomplete Meter Installation Notice</fullName>
    </customValue>
    <customValue>
        <fullName>Irrigation Efficiency Certification Form</fullName>
    </customValue>
    <customValue>
        <fullName>Irrigation Efficiency Form</fullName>
    </customValue>
    <customValue>
        <fullName>Last Will and Testament</fullName>
    </customValue>
    <customValue>
        <fullName>LOC Document</fullName>
    </customValue>
    <customValue>
        <fullName>LOC No Low Flows</fullName>
    </customValue>
    <masterLabel>Avo Submission Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AvoProcessStopperTriggerHandler.cls
public class AvoProcessStopperTriggerHandler extends AvoTriggerHandler{
    public override void beforeUpdate() {
            for(AVO_Process_State_Transition_Stopper__c stoper : (List<AVO_Process_State_Transition_Stopper__c>) Trigger.new) { 
            recalculateAvoStatus(stoper);
        }
    }        

    public override void beforeInsert() {
        for(AVO_Process_State_Transition_Stopper__c stoper : (List<AVO_Process_State_Transition_Stopper__c>) Trigger.new) { 
            recalculateAvoStatus(stoper);
        }
    }      

    private void recalculateAvoStatus(AVO_Process_State_Transition_Stopper__c stoper)
    {
        stoper.Avo_Status__c = 
        (stoper.Avo_Submission_Type__c== null ? '' : stoper.Avo_Submission_Status__c) +
        (stoper.Avo_Milestone_Name__c== null ? '' : stoper.Avo_Milestone_Completed_Action__c) +
        (stoper.Avo_Review_Status__c == null ? '' : stoper.Avo_Review_Status__c) +
        (stoper.Avo_Inspection_Result__c == null ? '' : stoper.Avo_Inspection_Result__c) +
        (stoper.Avo_Fee_Status__c == null ? '' : stoper.Avo_Fee_Status__c) +
        (stoper.Avo_Deposit_Status__c == null ? '' : stoper.Avo_Deposit_Status__c);
    }
}