force-app/main/default/objects/AVO_Process__c/AVO_Process__c.object-meta.xml
<CustomObject>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Process__c/fields/Avo_Permit_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Permit_Type__c</fullName>
    <label>Permit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Permit_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Process__c/fields/Avo_Planning_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Planning_Application_Type__c</fullName>
    <label>Planning Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Planning_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Avo_Permit_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agricultural Water Withdrawal Application</fullName>
    </customValue>
    <customValue>
        <fullName>Agricultural Water Withdrawal Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Application for Permit Consolidation</fullName>
    </customValue>
    <customValue>
        <fullName>Revision</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation Request</fullName>
    </customValue>
    <customValue>
        <fullName>Permit Relinquishment</fullName>
    </customValue>
    <customValue>
        <fullName>Well and Pump Data</fullName>
    </customValue>
    <customValue>
        <fullName>Well Plug &amp; Abandonment</fullName>
    </customValue>
    <customValue>
        <fullName>AG Water Metering Installation</fullName>
    </customValue>
    <masterLabel>Avo Permit Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Avo_Planning_Application_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Variance</fullName>
    </customValue>
    <customValue>
        <fullName>Development Permit</fullName>
    </customValue>
    <masterLabel>Avo Planning Application Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AvoProcessTriggerHandler.cls
/**
 * Description of class
 * enforce data integrity for the process object
 * @author Jason Li
 * last modified by Jason Li
 * @date 06/18/2021
 *  
 */
public class AvoProcessTriggerHandler extends AvoTriggerHandler { 
    public override void beforeUpdate() {
        for(AVO_Process__c AvoProcess : (List<AVO_Process__c>) Trigger.new) { 
            ValidateData(AvoProcess);           
        }
    }

    public override void beforeInsert() {
        for(AVO_Process__c AvoProcess : (List<AVO_Process__c>) Trigger.new) { 
            ValidateData(AvoProcess);
        }
    }
    
    private void ValidateData(AVO_Process__c AvoProcess)
    {
        If (AvoProcess.AVO_Permit_Type__c != null && AvoProcess.AVO_Planning_Application_Type__c != null ||
            AvoProcess.AVO_Permit_Type__c == null && AvoProcess.AVO_Planning_Application_Type__c == null){
            AvoProcess.addError('Select either Permit Types or Planning Application Typesd');
        }  
    }
}