force-app/main/default/objects/AVO_Process__c/AVO_Process__c.object-meta.xml
<CustomObject>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Process__c/fields/Avo_Active__c.field-meta.xml
<CustomField>
    <fullName>Avo_Active__c</fullName>
    <formula>IF( AND(Avo_Effective_Start_Date__c&lt;TODAY(),
(OR(ISBLANK(Avo_Effective_End_Date__c),
Avo_Effective_End_Date__c&gt; TODAY())
)
),True,False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AVO_Process__c/fields/Avo_Planning_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Planning_Application_Type__c</fullName>
    <label>Planning Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Planning_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Post_Actions__c/AVO_Process_State_Post_Actions__c.object-meta.xml
<CustomObject>
    <label>Process State Transition Post Action</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Post Action ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process State Transition Post Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Process_State_Post_Actions__c/fields/Avo_Active__c.field-meta.xml
<CustomField>
    <fullName>Avo_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Post_Actions__c/fields/Avo_Date_Field__c.field-meta.xml
<CustomField>
    <fullName>Avo_Date_Field__c</fullName>
    <inlineHelpText>name of a date field from the Permit or Application object</inlineHelpText>
    <label>Date Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Post_Actions__c/fields/Avo_Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Event_Type__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Event_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Post_Actions__c/fields/Avo_Formula_Condition__c.field-meta.xml
<CustomField>
    <fullName>Avo_Formula_Condition__c</fullName>
    <inlineHelpText>for example: Avo_Electrical_Type_of_Applicable_Work__c = &apos;Solar&apos;</inlineHelpText>
    <label>Formula Condition</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Post_Actions__c/fields/Avo_Process__c.field-meta.xml
<CustomField>
    <fullName>Avo_Process__c</fullName>
    <formula>Avo_Process_State_Transition__r.Avo_Process__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Process</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Post_Actions__c/fields/Avo_Process_State_Transition__c.field-meta.xml
<CustomField>
    <fullName>Avo_Process_State_Transition__c</fullName>
    <label>Process State Transition</label>
    <referenceTo>AVO_Process_State_Transition__c</referenceTo>
    <relationshipLabel>Process State Transition Post Actions</relationshipLabel>
    <relationshipName>Process_State_Transition_Post_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition__c/AVO_Process_State_Transition__c.object-meta.xml
<CustomObject>
    <label>Process State Transition</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>State Transition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process State Transitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Process_State_Transition__c/fields/Avo_Process__c.field-meta.xml
<CustomField>
    <fullName>Avo_Process__c</fullName>
    <label>Process</label>
    <referenceTo>AVO_Process__c</referenceTo>
    <relationshipLabel>Process State Transitions</relationshipLabel>
    <relationshipName>State_Transitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition_Stopper__c/AVO_Process_State_Transition_Stopper__c.object-meta.xml
<CustomObject>
    <label>Process State Transition Stopper</label>
    <nameField>
        <displayFormat>TT-{00000}</displayFormat>
        <label>Transition Condition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process State Transition Stoppers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Process_State_Transition_Stopper__c/fields/Avo_Inspection_Result__c.field-meta.xml
<CustomField>
    <fullName>Avo_Inspection_Result__c</fullName>
    <label>Inspection Result</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Inspection_Result</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition_Stopper__c/fields/Avo_Process_State_Transition__c.field-meta.xml
<CustomField>
    <fullName>Avo_Process_State_Transition__c</fullName>
    <label>Process State Transition</label>
    <referenceTo>AVO_Process_State_Transition__c</referenceTo>
    <relationshipLabel>Process State Transition Must Met Conditions</relationshipLabel>
    <relationshipName>Process_State_Transition_Stoppers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition_Stopper__c/fields/Avo_Review_Status__c.field-meta.xml
<CustomField>
    <fullName>Avo_Review_Status__c</fullName>
    <label>Review Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Review_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition_Trigger__c/AVO_Process_State_Transition_Trigger__c.object-meta.xml
<CustomObject>
    <label>Process State Transition Trigger</label>
    <nameField>
        <displayFormat>TT-{00000}</displayFormat>
        <label>Transition Trigger ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process State Transition Triggers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Process_State_Transition_Trigger__c/fields/Avo_Formula_Condition__c.field-meta.xml
<CustomField>
    <fullName>Avo_Formula_Condition__c</fullName>
    <label>Formula Condition</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition_Trigger__c/fields/Avo_Inspection_Result__c.field-meta.xml
<CustomField>
    <fullName>Avo_Inspection_Result__c</fullName>
    <label>Avo Inspection Result</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Inspection_Result</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition_Trigger__c/fields/Avo_Process_State_Transition__c.field-meta.xml
<CustomField>
    <fullName>Avo_Process_State_Transition__c</fullName>
    <label>Process State Transition</label>
    <referenceTo>AVO_Process_State_Transition__c</referenceTo>
    <relationshipName>Process_State_Transition_Triggers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Master_Event_List__c/Master_Event_List__c.object-meta.xml
<CustomObject>
    <label>Master Event List</label>
    <nameField>
        <label>Master Event List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Event Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Review_List__c/Master_Review_List__c.object-meta.xml
<CustomObject>
    <label>Master Review List</label>
    <nameField>
        <label>Master Review List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Review Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Review_List__c/fields/Avo_Offset__c.field-meta.xml
<CustomField>
    <fullName>Avo_Offset__c</fullName>
    <label>Offset</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Review_List__c/fields/Avo_Review_Status__c.field-meta.xml
<CustomField>
    <fullName>Avo_Review_Status__c</fullName>
    <label>Review Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Review_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Review_List__c/fields/Manual_Creation_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Manual_Creation_Allowed__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Manual Creation Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Master_Task_List__c/Master_Task_List__c.object-meta.xml
<CustomObject>
    <label>Master Task List</label>
    <nameField>
        <label>Master Task List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Task Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Master_Fee_List__c/MUSW__Master_Fee_List__c.object-meta.xml
<CustomObject>
    <label>Fee Template</label>
    <nameField>
        <label>Fee Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fee Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Master_Fee_List__c/fields/Avo_Planning_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Planning_Application_Type__c</fullName>
    <label>Planning Application Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Planning_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Fee_List__c/recordTypes/Permit.recordType-meta.xml
<RecordType>
    <fullName>Permit</fullName>
    <active>true</active>
    <description>Permit Fees</description>
    <label>Permit</label>
</RecordType>

force-app/main/default/objects/MUSW__Master_Inspection_List__c/MUSW__Master_Inspection_List__c.object-meta.xml
<CustomObject>
    <label>Inspection Template</label>
    <nameField>
        <label>Inspection Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inspection Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Master_Inspection_List__c/fields/Avo_Active__c.field-meta.xml
<CustomField>
    <fullName>Avo_Active__c</fullName>
    <formula>IF( AND(Effective_Start_Date__c&lt;TODAY(),
       (OR(ISBLANK(Effective_End_Date__c),
	       Effective_End_Date__c&gt; TODAY())
		) 
		),True,False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MUSW__Master_Inspection_List__c/fields/Avo_Planning_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Planning_Application_Type__c</fullName>
    <label>Planning Application Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Planning_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Submission_List__c/MUSW__Master_Submission_List__c.object-meta.xml
<CustomObject>
    <label>Submission Template</label>
    <nameField>
        <label>Submission Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Master_Submission_List__c/fields/Avo_Offset__c.field-meta.xml
<CustomField>
    <fullName>Avo_Offset__c</fullName>
    <label>Offset</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MUSW__Master_Submission_List__c/fields/Manual_Creation_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Manual_Creation_Allowed__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Manual Creation Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MUSW__Master_Submission_List__c/recordTypes/Permit.recordType-meta.xml
<RecordType>
    <fullName>Permit</fullName>
    <active>true</active>
    <description>Permit Submissions</description>
    <label>Permit</label>
</RecordType>

force-app/main/default/globalValueSets/Avo_Event_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>30 Day Planning Commission Meeting</fullName>
    </customValue>
    <customValue>
        <fullName>30 Day Planning Commission Meeting for Special Use</fullName>
    </customValue>
    <customValue>
        <fullName>30 Day Planning Commission Meeting for Variance</fullName>
    </customValue>
    <customValue>
        <fullName>90 Day Planning Commission Meeting</fullName>
    </customValue>
    <customValue>
        <fullName>90 Day Planning Commission Meeting for Special Use</fullName>
    </customValue>
    <customValue>
        <fullName>90 Day Planning Commission Meeting for Variance</fullName>
    </customValue>
    <customValue>
        <fullName>HPC Meeting</fullName>
    </customValue>
    <customValue>
        <fullName>M&amp;C Agenda Review Meeting</fullName>
    </customValue>
    <customValue>
        <fullName>M&amp;C Voting Session Meeting</fullName>
    </customValue>
    <customValue>
        <fullName>Mayor and Commission Meeting</fullName>
    </customValue>
    <customValue>
        <fullName>Mayor and Commission Meeting for Special Use</fullName>
    </customValue>
    <customValue>
        <fullName>Mayor and Commission Meeting for Variance</fullName>
    </customValue>
    <customValue>
        <fullName>Planning Commission Meeting</fullName>
    </customValue>
    <customValue>
        <fullName>Plan Review Meeting</fullName>
    </customValue>
    <customValue>
        <fullName>Public Hearing</fullName>
    </customValue>
    <customValue>
        <fullName>Staff Conference</fullName>
    </customValue>
    <masterLabel>Avo Event Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Avo_Inspection_Result.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
        <default>true</default>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>All Conditions met, OK to refund deposit</fullName>
    </customValue>
    <customValue>
        <fullName>Conditions outstanding, do not refund deposit until met</fullName>
    </customValue>
    <customValue>
        <fullName>Action needed, do not refund deposit until met</fullName>
    </customValue>
    <customValue>
        <fullName>Penalties/Fines to be assessed</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <masterLabel>Avo Inspection Result</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Avo_Planning_Application_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Variance</fullName>
    </customValue>
    <customValue>
        <fullName>Development Permit</fullName>
    </customValue>
    <masterLabel>Avo Planning Application Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Avo_Review_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Denied</fullName>
    </customValue>
    <customValue>
        <fullName>Required</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Information</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Wavier Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Completed to LOC Package</fullName>
    </customValue>
    <customValue>
        <fullName>Completed to Final Evaluation</fullName>
    </customValue>
    <customValue>
        <fullName>Completed to Form Assessment</fullName>
    </customValue>
    <customValue>
        <fullName>Fail Back</fullName>
    </customValue>
    <masterLabel>Avo Review Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AvoProcessHelperTest.cls
@isTest
public class AvoProcessHelperTest {

    @isTest
    static void GetProcessSummary_FromProcess_Permit() {

        AVO_Process__c process = AvoProcessEngineTestFactory.SetUpProcess('Permit Relinquishment', '');
        AVO_Process_State_Transition__c transition = AvoProcessEngineTestFactory.SetUpTransition(process.Id, 'Pending', 'Submitted');
        AVO_Process_State_Transition_Trigger__c transitionTrigger = AvoProcessEngineTestFactory.SetUpTrigger(transition.Id, 'Completeness Review', '', '');
        AVO_Process_State_Transition_Stopper__c stopper = AvoProcessEngineTestFactory.SetUpCondition('All Reviews', '', '', transition.Id, 'Approved');

        AVO_Process_State_Post_Actions__c postAction = new AVO_Process_State_Post_Actions__c(
            Avo_Event_Type__c = '30 Day Planning Commission Meeting',
            Avo_Formula_Condition__c = '',
            Avo_Date_Field__c = 'Avo_90_Day_Planning_Commission_Mtg_Date__c',
            Avo_Offset__c = 0,
            Avo_Active__c = true,
            Avo_Process_State_Transition__c = transition.Id
        );
        insert postAction;

        Master_Review_List__c review1 = AvoProcessEngineTestFactory.SetUpMasterReview('Completeness Review', 'Permit Relinquishment', '', 'Avo Review Default');
        review1.Manual_Creation_Allowed__c = true;
        update review1;

        MUSW__Master_Fee_List__c fee1 = AvoProcessEngineTestFactory.SetUpMasterFee('Administrative Action Fee', 'Permit Relinquishment', '', 'Avo Fee Default');
        MUSW__Master_Submission_List__c submisison1 = AvoProcessEngineTestFactory.SetUpMasterSubmission('Site Plan', 'Permit Relinquishment', '', 'Avo Submission Default');
        MUSW__Master_Inspection_List__c inspection1 = AvoProcessEngineTestFactory.SetUpMasterInspection('Final Inspection', 'Permit Relinquishment', '', 'Avo Inspection Default');
      

        List<AvoProcessHelper.item> result = AvoProcessHelper.GetProcessSummary(process.Id, '');

        System.assertEquals(2, result.size());
    }


    @isTest
    static void GetProcessSummary_FromTransition_Permit() {

        AVO_Process__c process = AvoProcessEngineTestFactory.SetUpProcess('Permit Relinquishment', '');
        AVO_Process_State_Transition__c transition = AvoProcessEngineTestFactory.SetUpTransition(process.Id, 'Pending', 'Submitted');
        AVO_Process_State_Transition_Trigger__c transitionTrigger = AvoProcessEngineTestFactory.SetUpTrigger(transition.Id, 'Completeness Review', '', '');
        AVO_Process_State_Transition_Stopper__c stopper = AvoProcessEngineTestFactory.SetUpCondition('All Reviews', '', '', transition.Id, 'Approved');

        AVO_Process_State_Post_Actions__c postAction = new AVO_Process_State_Post_Actions__c(
            Avo_Event_Type__c = '30 Day Planning Commission Meeting',
            Avo_Formula_Condition__c = '',
            Avo_Date_Field__c = 'Avo_90_Day_Planning_Commission_Mtg_Date__c',
            Avo_Offset__c = 0,
            Avo_Active__c = true,
            Avo_Process_State_Transition__c = transition.Id
        );
        insert postAction;

        List<AvoProcessHelper.item> result = AvoProcessHelper.GetProcessSummary(transition.Id, 'AVO_Process_State_Transition__c');

        System.assertEquals(2, result.size());
    }


    @isTest
    static void GetProcessSummary_FromProcess_Application() {

        AVO_Process__c process = AvoProcessEngineTestFactory.SetUpProcess('', 'Development Permit');
        AVO_Process_State_Transition__c transition = AvoProcessEngineTestFactory.SetUpTransition(process.Id, 'Pending', 'Submitted');
        AVO_Process_State_Transition_Trigger__c transitionTrigger = AvoProcessEngineTestFactory.SetUpTrigger(transition.Id, 'Completeness Review', '', '');
        AVO_Process_State_Transition_Stopper__c stopper = AvoProcessEngineTestFactory.SetUpCondition('All Reviews', '', '', transition.Id, 'Approved');

        AVO_Process_State_Post_Actions__c postAction = new AVO_Process_State_Post_Actions__c(
            Avo_Event_Type__c = '30 Day Planning Commission Meeting',
            Avo_Formula_Condition__c = 'a = b',
            Avo_Date_Field__c = 'Avo_90_Day_Planning_Commission_Mtg_Date__c',
            Avo_Offset__c = 0,
            Avo_Active__c = true,
            Avo_Process_State_Transition__c = transition.Id
        );
        insert postAction;

        String eventName = '30 Day Planning Commission Meeting';
        String applicationType = 'Development Permit';
        String recordType = 'Default';
        
        Master_Event_List__c event =  AvoProcessEngineTestFactory.SetUpMasterEvent(eventName, applicationType, recordType);

        Master_Task_List__c task = new Master_Task_List__c(
            Avo_Planning_Application_Type__c = applicationType,
            Name = 'Agenda Update'
        );

        insert task;

        List<AvoProcessHelper.item> result = AvoProcessHelper.GetProcessSummary(process.Id, '');

        System.assertEquals(2, result.size());
    }

    @isTest
    static void GetProcessSummary_FromProcess_Permit_Multiple() {

        AVO_Process__c process = AvoProcessEngineTestFactory.SetUpProcess('Permit Relinquishment', '');
        AVO_Process_State_Transition__c transition = AvoProcessEngineTestFactory.SetUpTransition(process.Id, 'Pending', 'Submitted');
        
        AVO_Process_State_Transition_Trigger__c transitionTrigger1 = AvoProcessEngineTestFactory.SetUpTrigger(transition.Id, 'Completeness Review', '', '');
        transitionTrigger1.Avo_Review_Status__c = 'Approved';
        update transitionTrigger1;

        AVO_Process_State_Transition_Trigger__c transitionTrigger2 = AvoProcessEngineTestFactory.SetUpTrigger(transition.Id, 'Completeness Review', '', '');
        transitionTrigger2.Avo_Review_Status__c = 'Approved';
        update transitionTrigger2;
       
        AVO_Process_State_Transition_Trigger__c transitionTrigger3 = AvoProcessEngineTestFactory.SetUpTrigger(transition.Id, '', '', 'TPA Final Inspection');
        transitionTrigger3.Avo_Inspection_Result__c = 'Completed';
        update transitionTrigger3;

        AVO_Process_State_Transition_Trigger__c transitionTrigger4 = AvoProcessEngineTestFactory.SetUpTrigger(transition.Id, '', 'Any Fee', '');
        
        
        AVO_Process_State_Transition_Stopper__c stopper = AvoProcessEngineTestFactory.SetUpCondition('All Reviews', '', '', transition.Id, 'Approved');
        AVO_Process_State_Transition_Stopper__c stopper1 = AvoProcessEngineTestFactory.SetUpCondition('', 'Any Fee', '', transition.Id, 'fully paid');
        AVO_Process_State_Transition_Stopper__c stopper2 = AvoProcessEngineTestFactory.SetUpCondition('', '', 'TPA Final Inspection', transition.Id, 'Completed');
        AVO_Process_State_Transition_Stopper__c stopper3 = AvoProcessEngineTestFactory.SetUpCondition('', '', 'TPA Final Inspection', transition.Id, 'Completed');


        AVO_Process_State_Post_Actions__c postAction = new AVO_Process_State_Post_Actions__c(
            Avo_Event_Type__c = '30 Day Planning Commission Meeting',
            Avo_Formula_Condition__c = '',
            Avo_Date_Field__c = 'Avo_90_Day_Planning_Commission_Mtg_Date__c',
            Avo_Offset__c = 0,
            Avo_Active__c = true,
            Avo_Process_State_Transition__c = transition.Id
        );
        insert postAction;

        Master_Review_List__c review1 = AvoProcessEngineTestFactory.SetUpMasterReview('Completeness Review', 'Permit Relinquishment', '', 'Avo Review Default');
        review1.Manual_Creation_Allowed__c = true;
        update review1;

        MUSW__Master_Fee_List__c fee1 = AvoProcessEngineTestFactory.SetUpMasterFee('Administrative Action Fee', 'Permit Relinquishment', '', 'Avo Fee Default');
        MUSW__Master_Submission_List__c submisison1 = AvoProcessEngineTestFactory.SetUpMasterSubmission('Site Plan', 'Permit Relinquishment', '', 'Avo Submission Default');
        MUSW__Master_Inspection_List__c inspection1 = AvoProcessEngineTestFactory.SetUpMasterInspection('Final Inspection', 'Permit Relinquishment', '', 'Avo Inspection Default');
      

        List<AvoProcessHelper.item> result = AvoProcessHelper.GetProcessSummary(process.Id, '');

        System.assertEquals(2, result.size());
    }



    @isTest
    static void getReviews() {
        Master_Review_List__c review1 = AvoProcessEngineTestFactory.SetUpMasterReview('Completeness Review', 'Agricultural Water Withdrawal Application', '', 'Avo Review Default');
        List<AvoProcessHelper.item> result = AvoProcessHelper.getReviews('Agricultural Water Withdrawal Application');

        System.assertEquals(1, result.size());

    }

    @isTest
    static void cloneProcess() {

        AVO_Process__c process = AvoProcessEngineTestFactory.SetUpProcess('Agricultural Water Withdrawal Application', '');
        AVO_Process_State_Transition__c transition = AvoProcessEngineTestFactory.SetUpTransition(process.Id, 'Pending', 'Submitted');
        
        AVO_Process_State_Transition_Trigger__c transitionTrigger1 = AvoProcessEngineTestFactory.SetUpTrigger(transition.Id, 'All Reviews', '', '');
        transitionTrigger1.Avo_Review_Status__c = 'Approved';
        update transitionTrigger1;

        AVO_Process_State_Transition_Trigger__c transitionTrigger2 = AvoProcessEngineTestFactory.SetUpTrigger(transition.Id, 'All Reviews', '', '');
        transitionTrigger2.Avo_Review_Status__c = 'Approved';
        update transitionTrigger2;
       
        AVO_Process_State_Transition_Trigger__c transitionTrigger3 = AvoProcessEngineTestFactory.SetUpTrigger(transition.Id, '', '', 'TPA Final Inspection');
        transitionTrigger3.Avo_Inspection_Result__c = 'Completed';
        update transitionTrigger3;

        AVO_Process_State_Transition_Trigger__c transitionTrigger4 = AvoProcessEngineTestFactory.SetUpTrigger(transition.Id, '', 'Any Fee', '');
        
        
        AVO_Process_State_Transition_Stopper__c stopper = AvoProcessEngineTestFactory.SetUpCondition('All Reviews', '', '', transition.Id, 'Approved');
        AVO_Process_State_Transition_Stopper__c stopper1 = AvoProcessEngineTestFactory.SetUpCondition('', 'Any Fee', '', transition.Id, 'fully paid');
        AVO_Process_State_Transition_Stopper__c stopper2 = AvoProcessEngineTestFactory.SetUpCondition('', '', 'All Inspections', transition.Id, 'Completed');
        AVO_Process_State_Transition_Stopper__c stopper3 = AvoProcessEngineTestFactory.SetUpCondition('', '', 'All Inspections', transition.Id, 'Completed');


        AVO_Process_State_Post_Actions__c postAction = new AVO_Process_State_Post_Actions__c(
            Avo_Event_Type__c = '30 Day Planning Commission Meeting',
            Avo_Formula_Condition__c = '',
            Avo_Date_Field__c = 'Avo_90_Day_Planning_Commission_Mtg_Date__c',
            Avo_Offset__c = 0,
            Avo_Active__c = true,
            Avo_Process_State_Transition__c = transition.Id
        );
        insert postAction;

        Master_Review_List__c review1 = AvoProcessEngineTestFactory.SetUpMasterReview('Revision', 'Agricultural Water Withdrawal Application', '', 'Agricultural Water Withdrawal Permit');
        review1.Manual_Creation_Allowed__c = true;
        update review1;

        MUSW__Master_Fee_List__c fee1 = AvoProcessEngineTestFactory.SetUpMasterFee('Administrative Action Fee', 'Permit Relinquishment', '', 'Avo Fee Default');
        MUSW__Master_Submission_List__c submisison1 = AvoProcessEngineTestFactory.SetUpMasterSubmission('Site Plan', 'Permit Relinquishment', '', 'Avo Submission Default');
        MUSW__Master_Inspection_List__c inspection1 = AvoProcessEngineTestFactory.SetUpMasterInspection('Final Inspection', 'Permit Relinquishment', '', 'Avo Inspection Default');
      

        String result = AvoProcessHelper.cloneProcess(process.Id, '', '');

        System.assertNotEquals(null, result);
    }


}