force-app/main/default/objects/AVO_Process__c/AVO_Process__c.object-meta.xml
<CustomObject>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Process__c/fields/Avo_Effective_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Avo_Effective_End_Date__c</fullName>
    <label>Effective End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AVO_Process__c/fields/Avo_Permit_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Permit_Type__c</fullName>
    <label>Permit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Permit_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Process__c/fields/Avo_Planning_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Planning_Application_Type__c</fullName>
    <label>Planning Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Planning_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Process__c/fields/Avo_Process_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Process_Type__c</fullName>
    <label>Process Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Permit Process</fullName>
            </value>
            <value>
                <fullName>Planning Application Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition__c/AVO_Process_State_Transition__c.object-meta.xml
<CustomObject>
    <label>Process State Transition</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>State Transition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process State Transitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Process_State_Transition__c/fields/Avo_From_State__c.field-meta.xml
<CustomField>
    <fullName>Avo_From_State__c</fullName>
    <label>From State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Object_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition__c/fields/Avo_Process__c.field-meta.xml
<CustomField>
    <fullName>Avo_Process__c</fullName>
    <label>Process</label>
    <referenceTo>AVO_Process__c</referenceTo>
    <relationshipLabel>Process State Transitions</relationshipLabel>
    <relationshipName>State_Transitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition__c/fields/Avo_To_State__c.field-meta.xml
<CustomField>
    <fullName>Avo_To_State__c</fullName>
    <label>To State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Object_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition_Stopper__c/AVO_Process_State_Transition_Stopper__c.object-meta.xml
<CustomObject>
    <label>Process State Transition Stopper</label>
    <nameField>
        <displayFormat>TT-{00000}</displayFormat>
        <label>Transition Condition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process State Transition Stoppers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Process_State_Transition_Stopper__c/fields/Avo_Process_State_Transition__c.field-meta.xml
<CustomField>
    <fullName>Avo_Process_State_Transition__c</fullName>
    <label>Process State Transition</label>
    <referenceTo>AVO_Process_State_Transition__c</referenceTo>
    <relationshipLabel>Process State Transition Must Met Conditions</relationshipLabel>
    <relationshipName>Process_State_Transition_Stoppers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition_Stopper__c/fields/Avo_Review_Status__c.field-meta.xml
<CustomField>
    <fullName>Avo_Review_Status__c</fullName>
    <label>Review Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Review_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition_Stopper__c/fields/Avo_Review_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Review_Type__c</fullName>
    <label>Review Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Review_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition_Trigger__c/AVO_Process_State_Transition_Trigger__c.object-meta.xml
<CustomObject>
    <label>Process State Transition Trigger</label>
    <nameField>
        <displayFormat>TT-{00000}</displayFormat>
        <label>Transition Trigger ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process State Transition Triggers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Process_State_Transition_Trigger__c/fields/Avo_Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Fee_Type__c</fullName>
    <label>Fee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Fee_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition_Trigger__c/fields/Avo_Inspection_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Inspection_Type__c</fullName>
    <label>Inspection Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Inspection_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition_Trigger__c/fields/Avo_Process_State_Transition__c.field-meta.xml
<CustomField>
    <fullName>Avo_Process_State_Transition__c</fullName>
    <label>Process State Transition</label>
    <referenceTo>AVO_Process_State_Transition__c</referenceTo>
    <relationshipName>Process_State_Transition_Triggers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Master_Review_List__c/Master_Review_List__c.object-meta.xml
<CustomObject>
    <label>Master Review List</label>
    <nameField>
        <label>Master Review List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Review Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Review_List__c/fields/Avo_Permit_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Permit_Type__c</fullName>
    <label>Permit Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Permit_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Review_List__c/fields/Avo_Review_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Review_Type__c</fullName>
    <label>Review Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Review_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Inspection__c/MUSW__Inspection__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Ensure work is done in compliance with rules and regulations</description>
    <label>Inspection</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Inspection__c/fields/AVO_Review_Type__c.field-meta.xml
<CustomField>
    <fullName>AVO_Review_Type__c</fullName>
    <label>Review Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AVO_Comp_Ref_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Fee_List__c/MUSW__Master_Fee_List__c.object-meta.xml
<CustomObject>
    <label>Fee Template</label>
    <nameField>
        <label>Fee Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fee Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Master_Fee_List__c/fields/Avo_Planning_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Planning_Application_Type__c</fullName>
    <label>Planning Application Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Planning_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Fee_List__c/recordTypes/Permit.recordType-meta.xml
<RecordType>
    <fullName>Permit</fullName>
    <active>true</active>
    <description>Permit Fees</description>
    <label>Permit</label>
</RecordType>

force-app/main/default/objects/MUSW__Master_Inspection_List__c/MUSW__Master_Inspection_List__c.object-meta.xml
<CustomObject>
    <label>Inspection Template</label>
    <nameField>
        <label>Inspection Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inspection Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Master_Inspection_List__c/fields/Avo_Inspection_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Inspection_Type__c</fullName>
    <label>Inspection Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Inspection_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Inspection_List__c/fields/Avo_Permit_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Permit_Type__c</fullName>
    <label>Permit Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Permit_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Inspection_List__c/fields/Avo_Planning_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Planning_Application_Type__c</fullName>
    <label>Planning Application Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Planning_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Submission_List__c/MUSW__Master_Submission_List__c.object-meta.xml
<CustomObject>
    <label>Submission Template</label>
    <nameField>
        <label>Submission Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Master_Submission_List__c/fields/Avo_Permit_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Permit_Type__c</fullName>
    <label>Permit Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Permit_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Submission_List__c/recordTypes/Permit.recordType-meta.xml
<RecordType>
    <fullName>Permit</fullName>
    <active>true</active>
    <description>Permit Submissions</description>
    <label>Permit</label>
</RecordType>

force-app/main/default/objects/MUSW__Permit2__c/MUSW__Permit2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Permit application details</description>
    <label>Permit</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_Permit_Type__c.field-meta.xml
<CustomField>
    <fullName>AVO_Permit_Type__c</fullName>
    <label>Permit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AVO_Withdrawal_Permit_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Avo_Fee_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>All Fees</fullName>
    </customValue>
    <customValue>
        <fullName>Any Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Application Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Fine</fullName>
    </customValue>
    <customValue>
        <fullName>Manual Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Plan Review</fullName>
        <label>	Plan Review</label>
    </customValue>
    <customValue>
        <fullName>Administration Review Fee (Hours)</fullName>
    </customValue>
    <customValue>
        <fullName>Amendment or Extension Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Deposit</fullName>
    </customValue>
    <customValue>
        <fullName>Gate Access Permit (Annual)</fullName>
    </customValue>
    <customValue>
        <fullName>Good Neighbor Access Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Helicopter Landing Zone (Days)</fullName>
    </customValue>
    <customValue>
        <fullName>Inspection Fee (Weeks)</fullName>
    </customValue>
    <customValue>
        <fullName>Large-Scale Project Fees</fullName>
    </customValue>
    <customValue>
        <fullName>Penalty for Unauthorized Access/Encroachment (Days)</fullName>
    </customValue>
    <customValue>
        <fullName>Penalty for Violating Permit Conditions (Days)</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Review Fee (Hours)</fullName>
    </customValue>
    <customValue>
        <fullName>Review Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Staff Cost Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Park Use Fee (Days)</fullName>
    </customValue>
    <customValue>
        <fullName>Review Fee - Major</fullName>
    </customValue>
    <customValue>
        <fullName>Review Fee - Minor</fullName>
    </customValue>
    <masterLabel>Avo Fee Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Avo_Inspection_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>All Inspections</fullName>
    </customValue>
    <customValue>
        <fullName>Any Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>TPA Final Inspection</fullName>
    </customValue>
    <masterLabel>Avo Inspection Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Avo_Object_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Initial Review</fullName>
    </customValue>
    <customValue>
        <fullName>In Review</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Issued</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Finaled</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Enforcement</fullName>
    </customValue>
    <customValue>
        <fullName>LOC Package</fullName>
    </customValue>
    <customValue>
        <fullName>LOC Issued</fullName>
    </customValue>
    <customValue>
        <fullName>LOC Documents Uploaded</fullName>
    </customValue>
    <customValue>
        <fullName>Form Assessment</fullName>
    </customValue>
    <customValue>
        <fullName>Final Evaluation</fullName>
    </customValue>
    <customValue>
        <fullName>Permit Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Revision Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Permit Issued</fullName>
    </customValue>
    <customValue>
        <fullName>Revision Issued</fullName>
    </customValue>
    <customValue>
        <fullName>Ready to Issuance</fullName>
    </customValue>
    <customValue>
        <fullName>New</fullName>
    </customValue>
    <customValue>
        <fullName>In Transaction</fullName>
    </customValue>
    <customValue>
        <fullName>Ready for Issuance</fullName>
    </customValue>
    <customValue>
        <fullName>Ready for Final Inspection</fullName>
        <isActive>false</isActive>
        <label>Ready for Final Inspection</label>
    </customValue>
    <customValue>
        <fullName>In Violation</fullName>
        <isActive>false</isActive>
        <label>In Violation</label>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
        <isActive>false</isActive>
        <label>Closed</label>
    </customValue>
    <masterLabel>Avo Object Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Avo_Permit_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agricultural Water Withdrawal Application</fullName>
    </customValue>
    <customValue>
        <fullName>Agricultural Water Withdrawal Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Application for Permit Consolidation</fullName>
    </customValue>
    <customValue>
        <fullName>Revision</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation Request</fullName>
    </customValue>
    <customValue>
        <fullName>Permit Relinquishment</fullName>
    </customValue>
    <customValue>
        <fullName>Well and Pump Data</fullName>
    </customValue>
    <customValue>
        <fullName>Well Plug &amp; Abandonment</fullName>
    </customValue>
    <customValue>
        <fullName>AG Water Metering Installation</fullName>
    </customValue>
    <masterLabel>Avo Permit Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Avo_Planning_Application_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Variance</fullName>
    </customValue>
    <customValue>
        <fullName>Development Permit</fullName>
    </customValue>
    <masterLabel>Avo Planning Application Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Avo_Review_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Denied</fullName>
    </customValue>
    <customValue>
        <fullName>Required</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Information</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Wavier Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Completed to LOC Package</fullName>
    </customValue>
    <customValue>
        <fullName>Completed to Final Evaluation</fullName>
    </customValue>
    <customValue>
        <fullName>Completed to Form Assessment</fullName>
    </customValue>
    <customValue>
        <fullName>Fail Back</fullName>
    </customValue>
    <masterLabel>Avo Review Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Avo_Review_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>All Reviews</fullName>
    </customValue>
    <customValue>
        <fullName>Any Review</fullName>
    </customValue>
    <customValue>
        <fullName>AG Program Manager Review</fullName>
    </customValue>
    <customValue>
        <fullName>Director Office Review</fullName>
    </customValue>
    <customValue>
        <fullName>Evaluation of Withdrawal 1st Cut</fullName>
    </customValue>
    <customValue>
        <fullName>Evaluation of Withdrawal 2nd Cut</fullName>
    </customValue>
    <customValue>
        <fullName>Irrigation Efficiency Cert Review</fullName>
    </customValue>
    <customValue>
        <fullName>Low Flow Protection Plan Review</fullName>
    </customValue>
    <customValue>
        <fullName>Special Appraisal</fullName>
    </customValue>
    <customValue>
        <fullName>Water Conservation Plan Review</fullName>
    </customValue>
    <customValue>
        <fullName>Water Reuse Visibility Study Review</fullName>
    </customValue>
    <customValue>
        <fullName>Water Shed Manager Review</fullName>
    </customValue>
    <customValue>
        <fullName>Water Supply Manager Review</fullName>
    </customValue>
    <customValue>
        <fullName>Well Data Form Review</fullName>
    </customValue>
    <customValue>
        <fullName>Completeness Review</fullName>
    </customValue>
    <customValue>
        <fullName>Form Assessment Review</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrawal LOC Review</fullName>
    </customValue>
    <customValue>
        <fullName>Final Evaluation Review</fullName>
    </customValue>
    <customValue>
        <fullName>Waiver Review</fullName>
    </customValue>
    <customValue>
        <fullName>Metering Review</fullName>
    </customValue>
    <customValue>
        <fullName>Ready for Approval Review</fullName>
    </customValue>
    <customValue>
        <fullName>Meter Installation Review</fullName>
    </customValue>
    <customValue>
        <fullName>GIS Review</fullName>
    </customValue>
    <customValue>
        <fullName>Pemit Management Review</fullName>
    </customValue>
    <masterLabel>Avo Review Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/AVO_Withdrawal_Permit_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Groundwater</fullName>
    </customValue>
    <customValue>
        <fullName>Surface Water</fullName>
    </customValue>
    <customValue>
        <fullName>Well to Pond</fullName>
    </customValue>
    <customValue>
        <fullName>Undocumented Source</fullName>
        <isActive>false</isActive>
        <label>Undocumented Source</label>
    </customValue>
    <masterLabel>AVO Withdrawal Permit Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AvoProcessEngineTestFactory.cls
@isTest
public class AvoProcessEngineTestFactory {

    public static AVO_Process__c SetUpProcess(String permitType, String applicationType) {
        AVO_Process__c entity = new AVO_Process__c(
            Name = 'Unit Test',
            Avo_Effective_End_Date__c = Date.newInstance(2021, 1, 1),
            Avo_Permit_Type__c = permitType,
            Avo_Planning_Application_Type__c = (!String.isblank(applicationType)) ? applicationType : ' '
        );

        if (!String.isblank(permitType)) {
            //entity.RecordTypeId = '012050000004SgXAAU';
            ID PermitProcessRecordTypeID = Schema.SObjectType.AVO_Process__c.getRecordTypeInfosByName().get('Permit Process').getRecordTypeId();
            entity.RecordTypeId = PermitProcessRecordTypeID;
            entity.Avo_Process_Type__c = 'Permit Process';
        }

        if (!string.isblank(applicationType)) {
            ID PlanningApplicationProcessRecordTypeID = Schema.SObjectType.AVO_Process__c.getRecordTypeInfosByName().get('Planning Application Process').getRecordTypeId();
            entity.RecordTypeId = PlanningApplicationProcessRecordTypeID;
            //entity.RecordTypeId = '012050000004SgcAAE';
            entity.Avo_Process_Type__c = 'Planning Application Process';
        }

        insert entity;

        return entity;
    }

    public static AVO_Process_State_Transition__c SetUpTransition(Id processId, String fromState, String toState) {

        AVO_Process_State_Transition__c entity = new AVO_Process_State_Transition__c(
            Avo_Process__c = processId,
            Avo_From_State__c = fromState,
            Avo_To_State__c = toState
        );

        insert entity;

        return entity;
    }

    public static AVO_Process_State_Transition_Trigger__c SetUpTrigger(Id transitionId, String reviewType, String feeType, String inspectionType) {

        AVO_Process_State_Transition_Trigger__c entity = new AVO_Process_State_Transition_Trigger__c(
            AVO_Process_State_Transition__c = transitionId,
            Avo_Review_Type__c = reviewType,
            Avo_Fee_Type__c = feeType,
            Avo_Inspection_Type__c = inspectionType
        );

        insert entity;

        return entity;
    }

    public static AVO_Process_State_Transition_Stopper__c SetUpCondition(String reviewType, String feeType, String inspectionType, 
    Id transitionId, String expectedResult) {

        AVO_Process_State_Transition_Stopper__c entity = new AVO_Process_State_Transition_Stopper__c(
            Avo_Process_State_Transition__c = transitionId
        );

        if (!String.isblank(reviewType)) {
            Id ReviewConditionRecordTypeID = Schema.SObjectType.AVO_Process_State_Transition_Stopper__c.getRecordTypeInfosByName().get('Review Condition').getRecordTypeId();
            entity.RecordTypeId = ReviewConditionRecordTypeID;
            //entity.RecordTypeId = '012050000004SnnAAE';
            entity.Avo_Review_Type__c = reviewType;
            entity.Avo_Review_Status__c = expectedResult;
        }

        if (!String.isblank(feeType)) {
            Id FeeConditionRecordTypeID = Schema.SObjectType.AVO_Process_State_Transition_Stopper__c.getRecordTypeInfosByName().get('Fee Condition').getRecordTypeId();
            entity.RecordTypeId = FeeConditionRecordTypeID;
            //entity.RecordTypeId = '012050000004SnoAAE';
            entity.Avo_Fee_Type__c = feeType;
            entity.Avo_Fee_Status__c = expectedResult;
        }

        if (!String.isblank(inspectionType)) {
            Id InspectionConditionRecordTypeID = Schema.SObjectType.AVO_Process_State_Transition_Stopper__c.getRecordTypeInfosByName().get('Inspection Condition').getRecordTypeId();
            //entity.RecordTypeId = '012050000004SnpAAE';
            entity.RecordTypeId = InspectionConditionRecordTypeID;
            entity.Avo_Inspection_Type__c = inspectionType;
            entity.Avo_Inspection_Result__c = expectedResult;
        }

        insert entity;

        return entity;
    }

    
// Code Changes Made By Shalini 22-06-22
    public static MUSW__Permit2__c SetUpPermit(String type, String status, String lastName, String accountId) {
        Contact contact = new Contact(
            LastName = lastName,
            AccountId = (id) accountId
        );
        insert contact;
        
        
        MUSW__Permit2__c entity = new MUSW__Permit2__c(
            MUSW__Type__c = type,
            MUSW__Status__c = status,
            MUSW__Account__c = contact.AccountId,
            MUSW__Applicant__c = contact.id
        );

        insert entity;

        return entity;
    }

    public static MUSW__Permit2__c SetUpPermit() {
        MUSW__Permit2__c entity = new MUSW__Permit2__c();
			entity.AVO_Volumetric_Limits__c = 8.0;
        insert entity;

        return entity;
    }    

    public static MUSW__Application2__c SetUpApplication(String type, String recordTypeId) {
        MUSW__Application2__c entity = new MUSW__Application2__c(
            MUSW__Type__c = type
            //RecordTypeId = recordTypeId

        );

        insert entity;

        return entity;
    }

    public static MUSW__Review__c SetUpReview(Id permitId, Id applicationId, String type, String status) {

        MUSW__Review__c entity = new MUSW__Review__c(
            MUSW__Type__c = type,
            MUSW__Status__c = status
        );

        if (permitId != null)
        {
            entity.MUSW__Permit2__c = permitId;
        }

        if (applicationId != null) {
            entity.MUSW__Application2__c = applicationId;
        }

        insert entity;

        return entity;
    }

    public static MUSW__Inspection__c SetUpInspection(Id permitId, Id applicationId, String type, String status) {

        MUSW__Inspection__c entity = new MUSW__Inspection__c(
            MUSW__Type__c = type,
            MUSW__Status__c= status
        );

        if (permitId != null)
        {
            entity.MUSW__Permit__c = permitId;
        }

        if (applicationId != null) {
            entity.Avo_Application__c = applicationId;
        }

        insert entity;

        return entity;
    }

    public static MUSW__Fee__c SetUpFee(Id permitId, Id applicationId, String type, Decimal amount, Decimal amountPaid) {

        MUSW__Fee__c entity = new MUSW__Fee__c(
            MUSW__Type__c = type,
            MUSW__Amount__c = amount,
            MUSW__Amount_Paid__c = amountPaid
        );

        if (permitId != null)
        {
            entity.MUSW__Permit2__c = permitId;
        }

        if (applicationId != null) {
            entity.MUSW__Application2__c = applicationId;
        }

        insert entity;

        return entity;
    }

    public static MUSW__Submission__c SetUpSubmission(Id permitId, Id applicationId, String type, String status) {

        MUSW__Submission__c entity = new MUSW__Submission__c(
        );

        if (permitId != null)
        {
            entity.MUSW__Permit2__c = permitId;
        }

        if (applicationId != null) {
            entity.MUSW__Application2__c = applicationId;
        }

        insert entity;

        return entity;
    }

    public static Master_Event_List__c SetUpMasterEvent(String name, String type, String recordType) {

        Master_Event_List__c entity = new Master_Event_List__c(
            Name = name,
            Avo_Planning_Application_Type__c = type,
            Record_Type__c = recordType,
            Effective_Start_Date__c = Date.today().addDays(-1)
        );

        insert entity;

        return entity;
    }

    public static Master_Review_List__c SetUpMasterReview(String name, string permitType, String applicationType, String recordType) {

        Master_Review_List__c entity = new Master_Review_List__c(
            Name = name,
            Avo_Planning_Application_Type__c = applicationType,
            Avo_Permit_Type__c = permitType,
            Record_Type__c = recordType,
            Effective_Start_Date__c = Date.today().addDays(-1)
        );

        insert entity;

        return entity;
    }

    public static MUSW__Master_Fee_List__c SetUpMasterFee(String name, string permitType, String applicationType, String recordType) {

        MUSW__Master_Fee_List__c entity = new MUSW__Master_Fee_List__c(
            Name = name,
            Avo_Planning_Application_Type__c = applicationType,
            Avo_Permit_Type__c = permitType,
            Record_Type__c = recordType,
            Effective_Start_Date__c = Date.today().addDays(-1)
        );

        insert entity;

        return entity;
    }

    public static MUSW__Master_Inspection_List__c SetUpMasterInspection(String name, string permitType, String applicationType, String recordType) {

        MUSW__Master_Inspection_List__c entity = new MUSW__Master_Inspection_List__c(
            Name = name,
            Avo_Planning_Application_Type__c = applicationType,
            Avo_Permit_Type__c = permitType,
            Record_Type__c = recordType,
            Effective_Start_Date__c = Date.today().addDays(-1)
        );

        insert entity;

        return entity;
    }

    public static MUSW__Master_Submission_List__c SetUpMasterSubmission(String name, string permitType, String applicationType, String recordType) {

        MUSW__Master_Submission_List__c entity = new MUSW__Master_Submission_List__c(
            Name = name,
            Avo_Planning_Application_Type__c = applicationType,
            Avo_Permit_Type__c = permitType,
            Record_Type__c = recordType,
            Effective_Start_Date__c = Date.today().addDays(-1)
        );

        insert entity;

        return entity;
    }

  

    public static Contact SetUpContact(String name, String email) {

        Contact entity = new Contact(
            FirstName = name,
            LastName = name,
            Email = email
        );

        insert entity;

        return entity;
    }


}