force-app/main/default/objects/AVO_Withdrawals__c/AVO_Withdrawals__c.object-meta.xml
<CustomObject>
    <label>Withdrawals</label>
    <nameField>
        <label>Withdrawals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Withdrawals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Withdrawals__c/fields/AVO_GIS_UNIQUE__c.field-meta.xml
<CustomField>
    <fullName>AVO_GIS_UNIQUE__c</fullName>
    <description>Unique Identifier for the table.</description>
    <label>GIS Unique ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AVO_Withdrawals__c/fields/AVO_Low_Flow_cfs__c.field-meta.xml
<CustomField>
    <fullName>AVO_Low_Flow_cfs__c</fullName>
    <label>Low Flow cfs</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AVO_Withdrawals__c/fields/AVO_Low_Flow_gpm__c.field-meta.xml
<CustomField>
    <fullName>AVO_Low_Flow_gpm__c</fullName>
    <label>Low Flow gpm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AVO_Withdrawals__c/fields/AVO_Permit__c.field-meta.xml
<CustomField>
    <fullName>AVO_Permit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Permit</label>
    <referenceTo>MUSW__Permit2__c</referenceTo>
    <relationshipLabel>Withdrawals</relationshipLabel>
    <relationshipName>Withdrawals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AVO_Withdrawals__c/fields/AVO_Type__c.field-meta.xml
<CustomField>
    <fullName>AVO_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ground Water Withdrawal</fullName>
            </value>
            <value>
                <fullName>Surface Water Withdrawal</fullName>
            </value>
            <value>
                <fullName>Ground Water Withdrawal Application</fullName>
            </value>
            <value>
                <fullName>Surface Water Withdrawal Application</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/MUSW__Permit2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Permit application details</description>
    <label>Permit</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Permit2__c/fields/Avo_Withdrawals__c.field-meta.xml
<CustomField>
    <fullName>Avo_Withdrawals__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Withdrawals</label>
    <referenceTo>AVO_Withdrawals__c</referenceTo>
    <relationshipLabel>Permits (Withdrawals)</relationshipLabel>
    <relationshipName>Permits1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Submission__c/MUSW__Submission__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Tracks online files</description>
    <label>Submission</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Submission__c/fields/MUSW__Permit2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Permit2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Permit</label>
    <referenceTo>MUSW__Permit2__c</referenceTo>
    <relationshipLabel>Submissions</relationshipLabel>
    <relationshipName>Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Submission__c/fields/MUSW__Submission_DateTime__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Submission_DateTime__c</fullName>
    <label>Submission Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/AvoWithdrawalTriggerHandler.cls
public class AvoWithdrawalTriggerHandler extends AvoTriggerHandler { 
  
    public override void beforeUpdate() {
        // Use map to avoid SOQL in loop
        for(AVO_Withdrawals__c withdrawal : (List<AVO_Withdrawals__c>) Trigger.new) { 
            String errorMessage = '';
            Boolean errorFound = false;
        	if ((withdrawal.AVO_Type__c == 'Surface Water Withdrawal Application' || withdrawal.AVO_Type__c == 'Surface Water Withdrawal') && withdrawal.AVO_Permit__c != null 
                && !String.isBlank(withdrawal.AVO_GIS_UNIQUE__c) && withdrawal.AVO_Low_Flow_cfs__c > 0 && withdrawal.AVO_Low_Flow_gpm__c > 0){
                List<MUSW__Submission__c> lowFlowPlans = [SELECT Id, Name, MUSW__Submission_DateTime__c FROM MUSW__Submission__c WHERE MUSW__Permit2__c = :withdrawal.AVO_Permit__c AND Name = 'Low Flow Guidance'];
                if (!lowFlowPlans.isEmpty()) {
                    MUSW__Submission__c lowFlowPlan = lowFlowPlans[0];
                    if (lowFlowPlan.MUSW__Submission_DateTime__c != null) {
                        withdrawal.addError('LF cfs and/or LF gpm >0 and LF Plan not marked as on file.');
                    }
                }
            }
        }
    }  

}