force-app/main/default/objects/Account/fields/MUSW__Total_Balance__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Total_Balance__c</fullName>
    <label>Total Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MUSW__Inspection__c/MUSW__Inspection__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Ensure work is done in compliance with rules and regulations</description>
    <label>Inspection</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Inspection__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Inspection__c/fields/AVO_App_ID__c.field-meta.xml
<CustomField>
    <fullName>AVO_App_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>App ID</label>
    <referenceTo>MUSW__Permit2__c</referenceTo>
    <relationshipLabel>Inspections (App ID)</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Inspection__c/fields/AVO_Farmer_Initiated_Online_Request__c.field-meta.xml
<CustomField>
    <fullName>AVO_Farmer_Initiated_Online_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Farmer Initiated Online Request</label>
    <referenceTo>MUSW__Inspection__c</referenceTo>
    <relationshipLabel>Site Visit Requests</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Inspection__c/fields/IsClosed__c.field-meta.xml
<CustomField>
    <fullName>IsClosed__c</fullName>
    <formula>CASE( MUSW__Status__c , 

&quot;Pending&quot;,&quot;No&quot;, 
&quot;Scheduled&quot;,&quot;No&quot;, 
&quot;Not Requested&quot;,&quot;No&quot;, 
&quot;Requested&quot;,&quot;No&quot;, 

&quot;Yes&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Closed</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__Inspection__c/fields/MUSW__Parcel__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Parcel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated Parcel (Address).</description>
    <label>Parcel</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MUSW__Parcel__c.MUSW__Historic__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>MUSW__Parcel__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Inspection__c/fields/MUSW__Permit__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Permit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated Permit.</description>
    <label>Permit</label>
    <referenceTo>MUSW__Permit2__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Inspection__c/fields/Requested_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Requested_DateTime__c</fullName>
    <label>Requested Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MUSW__Parcel__c/MUSW__Parcel__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Property parcel information</description>
    <label>Parcel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Permit2__c/MUSW__Permit2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Permit application details</description>
    <label>Permit</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Parcel__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Parcel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated parcel or address of the permit.</description>
    <label>Parcel</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MUSW__Parcel__c.MUSW__Historic__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>MUSW__Parcel__c</referenceTo>
    <relationshipLabel>Permits</relationshipLabel>
    <relationshipName>Permit2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Total_Balance__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Total_Balance__c</fullName>
    <description>Formula field that calculates the difference between total fees and total payments.</description>
    <formula>MUSW__Total_Fees__c - MUSW__Total_Payments__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit__c/MUSW__Permit__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Deprecated. Permit application details including process dates and status</description>
    <label>Permit (Deprecated)</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permits (Deprecated)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Permit__c/fields/IsClosed__c.field-meta.xml
<CustomField>
    <fullName>IsClosed__c</fullName>
    <formula>IF(OR(NOT(ISNULL( MUSW__Certificate_Issued__c )), NOT(ISNULL(MUSW__DateCompleted__c )), MUSW__Expiration_Date__c &gt;TODAY()),1,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Closed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit__c/fields/MUSW__Parcel__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Parcel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parcel</label>
    <referenceTo>MUSW__Parcel__c</referenceTo>
    <relationshipName>Permits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InspectionRequestController.cls
public with sharing class InspectionRequestController
{
    public String parentName { get; private set; }
    public MUSW__Inspection__c[] ins { get; set; }
    public Boolean hasBalance { get; private set; }
    public Integer insSelectIndex { get; set; }
    private Id pid;
    
    public void initSetIEMode()
    {
        ApexPages.currentPage().getHeaders().put('X-UA-Compatible', 'IE=10');
    }
    
    public InspectionRequestController()
    {
        insSelectIndex = null;
        pid = System.currentPageReference().getParameters().get('pid');
        
        String parcelId, rtName;
        if (String.valueOf(pid.getSobjectType()) == 'MUSW__Permit2__c')
        {
            MUSW__Permit2__c p = database.query('select Id, Name, MUSW__Parcel__c, RecordType.Name, MUSW__Total_Balance__c, (select ' + MUSW.UtilityDb.getFieldsFor_Str('MUSW__Inspection__c', false) + ' from MUSW__Inspections__r where Requested_DateTime__c = null and IsClosed__c = \'No\') from MUSW__Permit2__c where Id = :pid');
            parcelId = p.MUSW__Parcel__c;
            rtName = p.RecordType.Name;
            parentName = 'Permit: ' + p.Name;
            hasBalance = p.MUSW__Total_Balance__c > 0;
            ins = p.MUSW__Inspections__r;
        }
        else
        {
            Account a = database.query('select Id, Name, (select ' + MUSW.UtilityDb.getFieldsFor_Str('MUSW__Inspection__c', false) + ' from Inspections__r where Requested_DateTime__c = null and IsClosed__c = \'No\') from Account where Id = :pid');
            parcelId = null;
            rtName = '';
            parentName = 'Account: ' + a.Name;
            hasBalance = false;
            ins = a.Inspections__r;
        }
        
        RecordType[] rt = [select Id from RecordType where Name = :rtName and SobjectType = 'MUSW__Inspection__c'];
        
        MUSW__Inspection__c newIns = new MUSW__Inspection__c(MUSW__Parcel__c=parcelId);
        if (rt.size() > 0) newIns.RecordTypeId = rt[0].Id;
        if (String.valueOf(pid.getSobjectType()) == 'MUSW__Permit2__c') newIns.MUSW__Permit__c = pid;
        else newIns.Account__c = pid;
        
        ins.add(newIns);
    }
    
    public pageReference save()
    {
        try
        {
            if(insSelectIndex != null)
            {
                ins[insSelectIndex].Requested_DateTime__c = system.now();
                upsert ins[insSelectIndex];
            } else
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Please select Inspections first.'));
                return null;
            }
        }
        catch (Exception e)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, e.getMessage()));
            return null;
        }
        return cancel();
    }
    
    public pageReference cancel()
    {
        pageReference pr = new pageReference('/'+ pid);
        pr.setredirect(true);
        return pr;  
    }

}