force-app/main/default/objects/AVO_Process_State_Transition_Trigger__c/AVO_Process_State_Transition_Trigger__c.object-meta.xml
<CustomObject>
    <label>Process State Transition Trigger</label>
    <nameField>
        <displayFormat>TT-{00000}</displayFormat>
        <label>Transition Trigger ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process State Transition Triggers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Process_State_Transition_Trigger__c/fields/Avo_Deposit_Status__c.field-meta.xml
<CustomField>
    <fullName>Avo_Deposit_Status__c</fullName>
    <label>Deposit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>fully paid</fullName>
                <default>true</default>
                <label>fully paid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition_Trigger__c/fields/Avo_Fee_Status__c.field-meta.xml
<CustomField>
    <fullName>Avo_Fee_Status__c</fullName>
    <label>Fee Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>fully paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition_Trigger__c/fields/Avo_Inspection_Result__c.field-meta.xml
<CustomField>
    <fullName>Avo_Inspection_Result__c</fullName>
    <label>Avo Inspection Result</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Inspection_Result</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition_Trigger__c/fields/Avo_Inspection_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Inspection_Type__c</fullName>
    <label>Inspection Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Inspection_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition_Trigger__c/fields/Avo_Milestone_Name__c.field-meta.xml
<CustomField>
    <fullName>Avo_Milestone_Name__c</fullName>
    <label>Milestone Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Milestone_Names</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Process_State_Transition_Trigger__c/fields/Avo_Status__c.field-meta.xml
<CustomField>
    <fullName>Avo_Status__c</fullName>
    <label>Status</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Avo_Inspection_Result.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
        <default>true</default>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>All Conditions met, OK to refund deposit</fullName>
    </customValue>
    <customValue>
        <fullName>Conditions outstanding, do not refund deposit until met</fullName>
    </customValue>
    <customValue>
        <fullName>Action needed, do not refund deposit until met</fullName>
    </customValue>
    <customValue>
        <fullName>Penalties/Fines to be assessed</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <masterLabel>Avo Inspection Result</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Avo_Inspection_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>All Inspections</fullName>
    </customValue>
    <customValue>
        <fullName>Any Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>TPA Final Inspection</fullName>
    </customValue>
    <masterLabel>Avo Inspection Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Avo_Milestone_Names.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Any Milestone</fullName>
    </customValue>
    <customValue>
        <fullName>All Milestones</fullName>
    </customValue>
    <customValue>
        <fullName>Initial Review</fullName>
    </customValue>
    <customValue>
        <fullName>Admin Review</fullName>
    </customValue>
    <customValue>
        <fullName>Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>Plan Review</fullName>
    </customValue>
    <masterLabel>Avo Milestone Names</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AvoProcessStateTransitionTriggerHandler.cls
/**
 * Description of class
 * trigger proxy for Process State Transition Trigger
 * @author Jason Li
 * last modified by Jason Li
 * @date 06/20/2021
 *  
 */
public class AvoProcessStateTransitionTriggerHandler extends AvoTriggerHandler { 
    public override void beforeUpdate() {
        for(AVO_Process_State_Transition_Trigger__c transitionTrigger : (List<AVO_Process_State_Transition_Trigger__c>) Trigger.new) { 
            recalculateAvoStatus(transitionTrigger);
        }
    }        

    public override void beforeInsert() {
        for(AVO_Process_State_Transition_Trigger__c transitionTrigger : (List<AVO_Process_State_Transition_Trigger__c>) Trigger.new) { 
            recalculateAvoStatus(transitionTrigger);
        }
    }      
    
    private void recalculateAvoStatus(AVO_Process_State_Transition_Trigger__c transitionTrigger)
    {
        transitionTrigger.Avo_Status__c = 
        (transitionTrigger.Avo_Submission_Type__c== null ? '' : transitionTrigger.Avo_Submission_Status__c) +
        (transitionTrigger.Avo_Milestone_Name__c== null ? '' : transitionTrigger.Avo_Milestone_Completed_Action__c) +
        (transitionTrigger.Avo_Review_Status__c == null ? '' : transitionTrigger.Avo_Review_Status__c) +
        (transitionTrigger.Avo_Inspection_Result__c == null ? '' : transitionTrigger.Avo_Inspection_Result__c) +
        (transitionTrigger.Avo_Fee_Status__c == null ? '' : transitionTrigger.Avo_Fee_Status__c) +
        (transitionTrigger.Avo_Deposit_Status__c == null ? '' : transitionTrigger.Avo_Deposit_Status__c) ;  
        
        system.debug('Test Status Submission ' + transitionTrigger.Avo_Submission_Status__c);
        system.debug('Test Status Milestone ' + transitionTrigger.Avo_Milestone_Completed_Action__c);
        system.debug('Test Status Review ' + transitionTrigger.Avo_Review_Status__c);
        system.debug('Test Status Inspection type' + transitionTrigger.Avo_Inspection_Type__c);
        system.debug('Test Status Inspection ' + transitionTrigger.Avo_Inspection_Result__c);
        system.debug('Test Status Fee ' + transitionTrigger.Avo_Fee_Status__c);
        system.debug('Test Status Deposit ' + transitionTrigger.Avo_Deposit_Status__c);
    }

}