force-app/main/default/objects/MUSW__Fee__c/MUSW__Fee__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Fees/Fines associated to Permits, Complaints, Planning Applications</description>
    <label>Fee</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Fee__c/fields/MUSW__Amount__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Amount__c</fullName>
    <description>An obligation amount (fee) that needs to be paid.</description>
    <inlineHelpText>Leave blank for default value (set after Save)</inlineHelpText>
    <label>Total</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MUSW__Fee__c/fields/MUSW__Permit2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Permit2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the associated permit record.</description>
    <label>Permit</label>
    <referenceTo>MUSW__Permit2__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Fee__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <description>The type of fee. Each type may have a different accounting code.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Violations</fullName>
            </value>
            <value>
                <fullName>Upward Adjustments</fullName>
            </value>
            <value>
                <fullName>Downward Adjustments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Parcel__c/MUSW__Parcel__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Property parcel information</description>
    <label>Parcel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Permit2__c/MUSW__Permit2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Permit application details</description>
    <label>Permit</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_Volumetric_Limits__c.field-meta.xml
<CustomField>
    <fullName>AVO_Volumetric_Limits__c</fullName>
    <label>Volumetric Limits</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Applicant__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The applicant submitting the permit application.</description>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Permits as Applicant</relationshipLabel>
    <relationshipName>Applicant_Permit2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Parcel__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Parcel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated parcel or address of the permit.</description>
    <label>Parcel</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MUSW__Parcel__c.MUSW__Historic__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>MUSW__Parcel__c</referenceTo>
    <relationshipLabel>Permits</relationshipLabel>
    <relationshipName>Permit2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <description>Status of the permit as it moves through the business workflow.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Submitted Documents</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Transaction</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Finaled</fullName>
            </value>
            <value>
                <fullName>Enforcement</fullName>
            </value>
            <value>
                <fullName>Initial Review</fullName>
            </value>
            <value>
                <fullName>LOC Package</fullName>
            </value>
            <value>
                <fullName>LOC Issued</fullName>
            </value>
            <value>
                <fullName>LOC Documents Uploaded</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Form Assessment</fullName>
            </value>
            <value>
                <fullName>Final Evaluation</fullName>
            </value>
            <value>
                <fullName>Permit Approval</fullName>
            </value>
            <value>
                <fullName>Revision Approval</fullName>
            </value>
            <value>
                <fullName>Ready for Issuance</fullName>
            </value>
            <value>
                <fullName>Permit Issued</fullName>
            </value>
            <value>
                <fullName>Revision Issued</fullName>
            </value>
            <value>
                <fullName>Issued</fullName>
            </value>
            <value>
                <fullName>Permit Rejected</fullName>
            </value>
            <value>
                <fullName>Consolidated</fullName>
            </value>
            <value>
                <fullName>Permit Denied</fullName>
            </value>
            <value>
                <fullName>Revision Denied</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Undocumented Source</fullName>
            </value>
            <value>
                <fullName>APPLICATION GIS MAPPING</fullName>
            </value>
            <value>
                <fullName>Undocumented Source Pending Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Total_Fees__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Total_Fees__c</fullName>
    <description>Total Fees represents the sum of all fees associated with this record, adjusted for any amended or waived amounts. This field is automatically calculated after updates.</description>
    <inlineHelpText>Automatically Refreshed after Fee updates</inlineHelpText>
    <label>Total Fees</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <description>The permit type. This is typically related to the record type.</description>
    <label>Type (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agricultural Surface Water Pump</fullName>
            </value>
            <value>
                <fullName>Agricultural Water Withdrawal Application</fullName>
            </value>
            <value>
                <fullName>Agricultural Water Withdrawal Permit</fullName>
            </value>
            <value>
                <fullName>Agricultural Well Pump</fullName>
            </value>
            <value>
                <fullName>Application for Permit Consolidation</fullName>
            </value>
            <value>
                <fullName>Revision</fullName>
            </value>
            <value>
                <fullName>Permit Relinquishment</fullName>
            </value>
            <value>
                <fullName>Well and Pump Data</fullName>
            </value>
            <value>
                <fullName>Well Plug and Abandonment</fullName>
            </value>
            <value>
                <fullName>AG Water Metering Installation</fullName>
            </value>
            <value>
                <fullName>Undocumented Source</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Valuation__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Valuation__c</fullName>
    <description>Dollar estimation of the construction value.</description>
    <label>Valuation</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Work_Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Work_Type__c</fullName>
    <description>Type of work that this permit has requested for approval.</description>
    <label>Work Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Addition</fullName>
            </value>
            <value>
                <fullName>Alteration</fullName>
            </value>
            <value>
                <fullName>Demolition</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/recordTypes/Electrical.recordType-meta.xml
<RecordType>
    <fullName>Electrical</fullName>
    <active>false</active>
    <description>Permit related to Electrical work</description>
    <label>Electrical</label>
</RecordType>

force-app/main/default/classes/PermitViewControllerTest.cls
@isTest
public class PermitViewControllerTest {
    @isTest(seeAllData=true)
    static void testLicenseView()
    {
        MUSW__Parcel__c p = new MUSW__Parcel__c(Name = '123 Ork Street');
        insert p;
        Contact c = new Contact(Firstname = 'User', Lastname='Test', Email='abc@basicgov.com');
        insert c;
        
        BGBK.RulesEngineState.setLock();
        
        MUSW__Permit2__c per = new MUSW__Permit2__c(Name= '0001', MUSW__Applicant__c = c.id, MUSW__Type__c = 'Electrical', MUSW__Parcel__c = p.id, MUSW__Status__c = 'Pending', MUSW__Work_Type__c = 'New Service', MUSW__Valuation__c = 1000, AVO_Volumetric_Limits__c= 10);
        insert per;
        
        MUSW__Fee__c fee1 = new MUSW__Fee__c(MUSW__Type__c = 'Electrical - Permit Fee', MUSW__Permit2__c = per.Id, MUSW__Amount__c = 80);
        insert fee1;
        
        MUSW__Fee__c fee2 = new MUSW__Fee__c(MUSW__Type__c = 'Electrical - Permit Fee Assessment', MUSW__Permit2__c = per.Id, MUSW__Amount__c = 1040);
        insert fee2;
        
        BGBK.RulesEngineState.releaseLock();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(per);
        PermitViewController pvc = new PermitViewController(sc);
        pvc.init();
        MUSW__Permit2__c per1 = [select MUSW__Total_Fees__c from MUSW__Permit2__c where id =: per.id];
        system.assert(per1.MUSW__Total_Fees__c == 1120 , per1.MUSW__Total_Fees__c);  
    }
}