force-app/main/default/objects/MUSW__Fee__c/MUSW__Fee__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Fees/Fines associated to Permits, Complaints, Planning Applications</description>
    <label>Fee</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Fee__c/fields/MUSW__Amended_Amount__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Amended_Amount__c</fullName>
    <description>Optional. This is used in case the Fee amount needs to be changed and the system needs to keep track of the original amount.</description>
    <label>Amended Amount</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MUSW__Fee__c/fields/MUSW__Amount__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Amount__c</fullName>
    <description>An obligation amount (fee) that needs to be paid.</description>
    <inlineHelpText>Leave blank for default value (set after Save)</inlineHelpText>
    <label>Total</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MUSW__Fee__c/fields/MUSW__Amount_Waived__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Amount_Waived__c</fullName>
    <description>Amount that needs to be waived. This impacts the outstanding amount of the fee.</description>
    <label>Waived</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MUSW__Fee__c/fields/MUSW__Permit2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Permit2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the associated permit record.</description>
    <label>Permit</label>
    <referenceTo>MUSW__Permit2__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/MUSW__Permit2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Permit application details</description>
    <label>Permit</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Total_Fees__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Total_Fees__c</fullName>
    <description>Total Fees represents the sum of all fees associated with this record, adjusted for any amended or waived amounts. This field is automatically calculated after updates.</description>
    <inlineHelpText>Automatically Refreshed after Fee updates</inlineHelpText>
    <label>Total Fees</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PermitViewController.cls
public with sharing class PermitViewController
{
    private Id m_pid;
    
    public PermitViewController(ApexPages.StandardController con)
    {
        m_pid = con.getRecord().Id;
    }
    
    /** Fill in Total Fees on Permit **/
    public void init()
    {
        if(m_pid != null)
        {
            Decimal oldTotalFees = 0;
            Decimal totalFees = 0;
            
            MUSW__Permit2__c per  = [select Id, MUSW__Total_Fees__c from MUSW__Permit2__c where Id=:m_pid];
            
            if(per.MUSW__Total_Fees__c != null)
            {
                oldTotalFees = per.MUSW__Total_Fees__c;
            }
            
            MUSW__Fee__c[] fees = [select Id, MUSW__Amount__c, MUSW__Amount_Waived__c, MUSW__Amended_Amount__c from MUSW__Fee__c where MUSW__Permit2__c =: m_pid];
                        
            for(MUSW__Fee__c fee: fees)
            {                
                if(fee.MUSW__Amount__c != null){
                    Decimal otherAmount = 0;
                    if (fee.MUSW__Amount_Waived__c != null) otherAmount -= fee.MUSW__Amount_Waived__c;
                    if (fee.MUSW__Amended_Amount__c != null) otherAmount -= fee.MUSW__Amended_Amount__c;
                    
                    totalFees += fee.MUSW__Amount__c + otherAmount; 
                }
            }
                        
            if(totalFees != oldTotalFees)
            {
                per.MUSW__Total_Fees__c = totalFees;
                try{
                    update per;
                } catch (DmlException e)
                {
                    if(!e.getMessage().contains('ENTITY_IS_LOCKED')) throw e;
                }
            }
        }
    }
}