force-app/main/default/objects/MUSW__Fee__c/MUSW__Fee__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Fees/Fines associated to Permits, Complaints, Planning Applications</description>
    <label>Fee</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Fee__c/fields/MUSW__Fee_Paid__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Fee_Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The system sets this value to true when the outstanding amount is $0.</description>
    <label>Paid in Full</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MUSW__Fee__c/fields/MUSW__Outstanding_Fee__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Outstanding_Fee__c</fullName>
    <description>Amount outstanding based on the following formula: (Amount) - (Amended Amount) - (Waived Amount) - (Paid Amount).</description>
    <formula>If(MUSW__Amount__c - MUSW__Amount_Waived__c - MUSW__Amount_Paid__c - MUSW__Amended_Amount__c &lt; 0, 0, MUSW__Amount__c - MUSW__Amount_Waived__c - MUSW__Amount_Paid__c - MUSW__Amended_Amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Outstanding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AvoFeeTriggerHandler.cls
/**
 * Description of class
 * trigger proxy for fees
 * @author Jason Li
 * last modified by Jason Li
 * @date 06/28/2021
 *  
 */
public class AvoFeeTriggerHandler extends AvoTriggerHandler { 
    
    public override void afterUpdate() {
        system.debug('fee trigger after update');

        for(MUSW__Fee__c fee : (List<MUSW__Fee__c>) Trigger.new) { 
            MUSW__Fee__c oldfee = (MUSW__Fee__c)Trigger.oldMap.get(fee.Id);
            system.debug('old fee:' + oldfee.MUSW__Outstanding_Fee__c);
            system.debug('new fee:' + fee.MUSW__Outstanding_Fee__c);
            system.debug('old MUSW__Fee_Paid__c:' + oldfee.MUSW__Fee_Paid__c);
            system.debug('new MUSW__Fee_Paid__c:' + fee.MUSW__Fee_Paid__c);
            if (oldfee.MUSW__Outstanding_Fee__c != 0 && fee.MUSW__Outstanding_Fee__c == 0  && fee.MUSW__Fee_Paid__c ==true ){
                system.debug('fee:' + fee);
                system.debug('a fee with zero outstanding fee dectected');
            	AvoProcessEngineFee avoProcessEngineFee = new AvoProcessEngineFee(fee);
            	avoProcessEngineFee.run(); 
            }
        }
    }

    public override void afterInsert() {

        // System.debug('recalcuating fee trigger');
        // for(MUSW__Fee__c fee : (List<MUSW__Fee__c>) Trigger.new) { 
        //     AvoFeeManager.recalcuatedCombinedWorkItem(fee);
        // }
    }
}