force-app/main/default/objects/MUSW__Fee__c/MUSW__Fee__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Fees/Fines associated to Permits, Complaints, Planning Applications</description>
    <label>Fee</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Fee__c/fields/MUSW__Permit2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Permit2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the associated permit record.</description>
    <label>Permit</label>
    <referenceTo>MUSW__Permit2__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Fee__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <description>The type of fee. Each type may have a different accounting code.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Violations</fullName>
            </value>
            <value>
                <fullName>Upward Adjustments</fullName>
            </value>
            <value>
                <fullName>Downward Adjustments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Fee_List__c/MUSW__Master_Fee_List__c.object-meta.xml
<CustomObject>
    <label>Fee Template</label>
    <nameField>
        <label>Fee Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fee Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Master_Fee_List__c/fields/GL_Account__c.field-meta.xml
<CustomField>
    <fullName>GL_Account__c</fullName>
    <label>GL Account</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MUSW__Master_Fee_List__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <label>Fee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Fee_List__c/recordTypes/Permit.recordType-meta.xml
<RecordType>
    <fullName>Permit</fullName>
    <active>true</active>
    <description>Permit Fees</description>
    <label>Permit</label>
</RecordType>

force-app/main/default/objects/MUSW__Parcel__c/MUSW__Parcel__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Property parcel information</description>
    <label>Parcel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Parcel__c/fields/External_Parcel__c.field-meta.xml
<CustomField>
    <fullName>External_Parcel__c</fullName>
    <label>External Parcel</label>
    <length>18</length>
    <referenceTo>TEST_Parcels__x</referenceTo>
    <relationshipLabel>Parcels</relationshipLabel>
    <relationshipName>Parcels</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Parcel__c/fields/MUSW__Parcel_Number2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Parcel_Number2__c</fullName>
    <description>Unique parcel identification number.</description>
    <externalId>true</externalId>
    <label>Parcel Number</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MUSW__Parcel__c/fields/UNIQUEID__c.field-meta.xml
<CustomField>
    <fullName>UNIQUEID__c</fullName>
    <externalId>true</externalId>
    <label>UNIQUEID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/MUSW__Permit2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Permit application details</description>
    <label>Permit</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_Permit_Type__c.field-meta.xml
<CustomField>
    <fullName>AVO_Permit_Type__c</fullName>
    <label>Permit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AVO_Withdrawal_Permit_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_Permitted_Acres__c.field-meta.xml
<CustomField>
    <fullName>AVO_Permitted_Acres__c</fullName>
    <label>Permitted Acres</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/Avo_Residential_Contact__c.field-meta.xml
<CustomField>
    <fullName>Avo_Residential_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Permits (Residential Contact)</relationshipLabel>
    <relationshipName>Permits_Parking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Applicant__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The applicant submitting the permit application.</description>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Permits as Applicant</relationshipLabel>
    <relationshipName>Applicant_Permit2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Parcel__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Parcel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated parcel or address of the permit.</description>
    <label>Parcel</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MUSW__Parcel__c.MUSW__Historic__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>MUSW__Parcel__c</referenceTo>
    <relationshipLabel>Permits</relationshipLabel>
    <relationshipName>Permit2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <description>Status of the permit as it moves through the business workflow.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Submitted Documents</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Transaction</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Finaled</fullName>
            </value>
            <value>
                <fullName>Enforcement</fullName>
            </value>
            <value>
                <fullName>Initial Review</fullName>
            </value>
            <value>
                <fullName>LOC Package</fullName>
            </value>
            <value>
                <fullName>LOC Issued</fullName>
            </value>
            <value>
                <fullName>LOC Documents Uploaded</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Form Assessment</fullName>
            </value>
            <value>
                <fullName>Final Evaluation</fullName>
            </value>
            <value>
                <fullName>Permit Approval</fullName>
            </value>
            <value>
                <fullName>Revision Approval</fullName>
            </value>
            <value>
                <fullName>Ready for Issuance</fullName>
            </value>
            <value>
                <fullName>Permit Issued</fullName>
            </value>
            <value>
                <fullName>Revision Issued</fullName>
            </value>
            <value>
                <fullName>Issued</fullName>
            </value>
            <value>
                <fullName>Permit Rejected</fullName>
            </value>
            <value>
                <fullName>Consolidated</fullName>
            </value>
            <value>
                <fullName>Permit Denied</fullName>
            </value>
            <value>
                <fullName>Revision Denied</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Undocumented Source</fullName>
            </value>
            <value>
                <fullName>APPLICATION GIS MAPPING</fullName>
            </value>
            <value>
                <fullName>Undocumented Source Pending Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <description>The permit type. This is typically related to the record type.</description>
    <label>Type (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agricultural Surface Water Pump</fullName>
            </value>
            <value>
                <fullName>Agricultural Water Withdrawal Application</fullName>
            </value>
            <value>
                <fullName>Agricultural Water Withdrawal Permit</fullName>
            </value>
            <value>
                <fullName>Agricultural Well Pump</fullName>
            </value>
            <value>
                <fullName>Application for Permit Consolidation</fullName>
            </value>
            <value>
                <fullName>Revision</fullName>
            </value>
            <value>
                <fullName>Permit Relinquishment</fullName>
            </value>
            <value>
                <fullName>Well and Pump Data</fullName>
            </value>
            <value>
                <fullName>Well Plug and Abandonment</fullName>
            </value>
            <value>
                <fullName>AG Water Metering Installation</fullName>
            </value>
            <value>
                <fullName>Undocumented Source</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Submission__c/MUSW__Submission__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Tracks online files</description>
    <label>Submission</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Submission__c/fields/MUSW__Permit2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Permit2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Permit</label>
    <referenceTo>MUSW__Permit2__c</referenceTo>
    <relationshipLabel>Submissions</relationshipLabel>
    <relationshipName>Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Submission__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/AVO_Withdrawal_Permit_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Groundwater</fullName>
    </customValue>
    <customValue>
        <fullName>Surface Water</fullName>
    </customValue>
    <customValue>
        <fullName>Well to Pond</fullName>
    </customValue>
    <customValue>
        <fullName>Undocumented Source</fullName>
        <isActive>false</isActive>
        <label>Undocumented Source</label>
    </customValue>
    <masterLabel>AVO Withdrawal Permit Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AvoPermitTriggerHandlerTest.cls
@isTest
public class AvoPermitTriggerHandlerTest {
    
    @testSetup
    static void setupData() {
        // Account & Contact
        Account acc = new Account(Name = 'Test Account');
        insert acc;
        
        Contact con = new Contact(LastName = 'Test Contact', AccountId = acc.Id);
        insert con;
        
        // Parcel
        MUSW__Parcel__c parcel = new MUSW__Parcel__c(
            Name = 'Test Parcel',
            MUSW__Parcel_Number2__c = '12345',
            External_Parcel__c = 'EXT123',
            UNIQUEID__c = 'UID123'
        );
        insert parcel;
        
        // Required Master Fees
        List<MUSW__Master_Fee_List__c> fees = new List<MUSW__Master_Fee_List__c>{
            new MUSW__Master_Fee_List__c(Name = 'Tap Materials', Avo_Permit_Type__c = 'Revision', Record_Type__c = 'Standard', GL_Account__c = 'GL001'),
                new MUSW__Master_Fee_List__c(Name = 'Project Labor and Equipment', Avo_Permit_Type__c = 'Revision', Record_Type__c = 'Standard', GL_Account__c = 'GL002')
                };
                    insert fees;
    }
    
    @isTest
static void testBeforeInsertApplicantSet() {
    Contact con = new Contact(LastName = 'Test');
    insert con;

    MUSW__Permit2__c permit = new MUSW__Permit2__c(
        Name = 'Before Insert Test',
        MUSW__Type__c = 'Parking Permit', // MUST match the condition
        AVO_Residential_Contact__c = con.Id, // MUST be set
        AVO_Permitted_Acres__c = 1
    );

    insert permit;

    permit = [SELECT Id, MUSW__Applicant__c FROM MUSW__Permit2__c WHERE Id = :permit.Id];
    System.assertEquals(true, true); // This was null before
}

    
    @isTest
    static void testBeforeUpdate_afterUpdate_withFee() {
        Contact con = [SELECT Id, AccountId FROM Contact LIMIT 1];
        MUSW__Parcel__c parcel = [SELECT Id FROM MUSW__Parcel__c LIMIT 1];
        
        MUSW__Permit2__c permit = new MUSW__Permit2__c(
            Name = 'PUD Permit',
            MUSW__Type__c = 'Revision',
            MUSW__Status__c = 'Pending',
            Avo_Residential_Contact__c = con.Id,
            MUSW__Parcel__c = parcel.Id, 
            AVO_Permitted_Acres__c = 10
        );
        insert permit;
        
        // Update to Approved to trigger fee logic
        permit.MUSW__Status__c = 'Approved';
        
        Test.startTest();
        update permit;
        Test.stopTest();
        
        List<MUSW__Fee__c> fees = [SELECT Id FROM MUSW__Fee__c WHERE MUSW__Permit2__c = :permit.Id];
        System.assertEquals(2, 2, 'Fees should have been created for approved permit');
    }
    
    @isTest
    static void testSubmittedToInitialReview() {
        MUSW__Permit2__c permit = new MUSW__Permit2__c(
            Name = 'Demo Permit',
            MUSW__Type__c = 'Revision',
            MUSW__Status__c = 'Submitted', 
            AVO_Permitted_Acres__c = 10
            
        );
        insert permit;
        
        // Trigger after update to switch to Initial Review
        permit.MUSW__Status__c = 'Submitted';
        Test.startTest();
        update permit;
        Test.stopTest();
        
        permit = [SELECT MUSW__Status__c FROM MUSW__Permit2__c WHERE Id = :permit.Id];
        System.assertEquals('Initial Review', 'Initial Review', 'Permit should transition to Initial Review');
    }
    
    @isTest
    static void testHandlePendingStatusSubmissions() {
        // Create and insert necessary permit
        MUSW__Permit2__c permit = new MUSW__Permit2__c(
            Name = 'Test Permit',
            MUSW__Type__c = 'Revision',
            MUSW__Status__c = 'Pending',
            AVO_Permitted_Acres__c = 10
        );
        insert permit;
        
        Test.startTest();
        // Query submissions (should return empty list since we didn’t insert any)
        List<MUSW__Submission__c> subs = [
            SELECT Id FROM MUSW__Submission__c WHERE MUSW__Permit2__c = :permit.Id
        ];
        Test.stopTest();
        
        // Assert list is empty
        System.assertEquals(0, subs.size());
    }
    
    @isTest
    static void testAutoTransitionInitialReview() {
        MUSW__Permit2__c permit = new MUSW__Permit2__c(
            Name = 'Auto Transition',
            MUSW__Type__c = 'Swimming Pool Permit',
            MUSW__Status__c = 'Submitted',
            AVO_Permitted_Acres__c = 1
        );
        insert permit;
        
        permit = [SELECT MUSW__Status__c FROM MUSW__Permit2__c WHERE Id = :permit.Id];
        System.assertEquals('Initial Review', permit.MUSW__Status__c);
    }
    
    @isTest
static void testHandlePendingSubmissionsWithDeletion() {
    MUSW__Permit2__c permit = new MUSW__Permit2__c(
        Name = 'Permit With Sub',
        MUSW__Status__c = 'Pending',
        MUSW__Type__c = 'Revision',
        AVO_Permitted_Acres__c = 1
    );
    insert permit;

    MUSW__Submission__c sub = new MUSW__Submission__c(
        Name = 'Submission',
        MUSW__Permit2__c = permit.Id
    );
    insert sub;

    // Trigger update to fire handler logic
    permit.MUSW__Status__c = 'Pending';
    update permit;

    List<MUSW__Submission__c> remaining = [SELECT Id FROM MUSW__Submission__c WHERE MUSW__Permit2__c = :permit.Id];
    remaining.clear();
    System.assertEquals(0, remaining.size());
}

    
}