force-app/main/default/objects/AVO_Compliance__c/AVO_Compliance__c.object-meta.xml
<CustomObject>
    <label>Compliance</label>
    <nameField>
        <label>CompNum</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compliances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Compliance__c/fields/AVO_Account__c.field-meta.xml
<CustomField>
    <fullName>AVO_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Compliances</relationshipLabel>
    <relationshipName>Compliances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AVO_Meter__c/AVO_Meter__c.object-meta.xml
<CustomObject>
    <label>Meter</label>
    <nameField>
        <label>Meter Serial Number (MSN)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Meter_Codeset__c/AVO_Meter_Codeset__c.object-meta.xml
<CustomObject>
    <label>Meter Codeset</label>
    <nameField>
        <label>Meter Codeset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meter Codesets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Meter_Transaction__c/AVO_Meter_Transaction__c.object-meta.xml
<CustomObject>
    <label>Meter Transaction</label>
    <nameField>
        <label>Meter Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meter Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Meter_Withdrawal__c/AVO_Meter_Withdrawal__c.object-meta.xml
<CustomObject>
    <label>Meter Withdrawal</label>
    <nameField>
        <label>Meter Withdrawal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meter Withdrawals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_SharePoint_File__c/AVO_SharePoint_File__c.object-meta.xml
<CustomObject>
    <label>SharePoint File</label>
    <nameField>
        <label>SharePoint File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SharePoint Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_SharePoint_File__c/fields/AVO_Account__c.field-meta.xml
<CustomField>
    <fullName>AVO_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SharePoint Files</relationshipLabel>
    <relationshipName>SharePoint_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AVO_SharePoint_File__c/fields/AVO_Application__c.field-meta.xml
<CustomField>
    <fullName>AVO_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>SharePoint Files</relationshipLabel>
    <relationshipName>SharePoint_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AVO_SharePoint_File__c/fields/AVO_Comment__c.field-meta.xml
<CustomField>
    <fullName>AVO_Comment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Comment</label>
    <referenceTo>MUSW__Comment__c</referenceTo>
    <relationshipLabel>SharePoint Files</relationshipLabel>
    <relationshipName>SharePoint_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AVO_SharePoint_File__c/fields/AVO_Complaint__c.field-meta.xml
<CustomField>
    <fullName>AVO_Complaint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Complaint</label>
    <referenceTo>MUSW__Complaint2__c</referenceTo>
    <relationshipLabel>SharePoint Files</relationshipLabel>
    <relationshipName>SharePoint_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AVO_SharePoint_File__c/fields/AVO_Compliance__c.field-meta.xml
<CustomField>
    <fullName>AVO_Compliance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compliance</label>
    <referenceTo>AVO_Compliance__c</referenceTo>
    <relationshipLabel>SharePoint Files</relationshipLabel>
    <relationshipName>SharePoint_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AVO_SharePoint_File__c/fields/AVO_Contact__c.field-meta.xml
<CustomField>
    <fullName>AVO_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SharePoint Files</relationshipLabel>
    <relationshipName>SharePoint_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AVO_SharePoint_File__c/fields/AVO_ContentDocumentId__c.field-meta.xml
<CustomField>
    <fullName>AVO_ContentDocumentId__c</fullName>
    <label>contentDocumentId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AVO_SharePoint_File__c/fields/AVO_Inspection__c.field-meta.xml
<CustomField>
    <fullName>AVO_Inspection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inspection</label>
    <referenceTo>MUSW__Inspection__c</referenceTo>
    <relationshipLabel>SharePoint Files</relationshipLabel>
    <relationshipName>SharePoint_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AVO_SharePoint_File__c/fields/AVO_License__c.field-meta.xml
<CustomField>
    <fullName>AVO_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>License</label>
    <referenceTo>MUSW__License2__c</referenceTo>
    <relationshipLabel>SharePoint Files</relationshipLabel>
    <relationshipName>SharePoint_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AVO_SharePoint_File__c/fields/AVO_Meter__c.field-meta.xml
<CustomField>
    <fullName>AVO_Meter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meter</label>
    <referenceTo>AVO_Meter__c</referenceTo>
    <relationshipLabel>SharePoint Files</relationshipLabel>
    <relationshipName>SharePoint_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AVO_SharePoint_File__c/fields/AVO_Meter_Codeset__c.field-meta.xml
<CustomField>
    <fullName>AVO_Meter_Codeset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meter Codeset</label>
    <referenceTo>AVO_Meter_Codeset__c</referenceTo>
    <relationshipLabel>SharePoint Files</relationshipLabel>
    <relationshipName>SharePoint_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AVO_SharePoint_File__c/fields/AVO_Meter_Transaction__c.field-meta.xml
<CustomField>
    <fullName>AVO_Meter_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meter Transaction</label>
    <referenceTo>AVO_Meter_Transaction__c</referenceTo>
    <relationshipLabel>SharePoint Files</relationshipLabel>
    <relationshipName>SharePoint_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AVO_SharePoint_File__c/fields/AVO_Meter_Withdrawal__c.field-meta.xml
<CustomField>
    <fullName>AVO_Meter_Withdrawal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meter Withdrawal</label>
    <referenceTo>AVO_Meter_Withdrawal__c</referenceTo>
    <relationshipLabel>SharePoint Files</relationshipLabel>
    <relationshipName>SharePoint_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AVO_SharePoint_File__c/fields/AVO_Milestone__c.field-meta.xml
<CustomField>
    <fullName>AVO_Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Milestone</label>
    <referenceTo>MUSW__Milestone__c</referenceTo>
    <relationshipLabel>SharePoint Files</relationshipLabel>
    <relationshipName>SharePoint_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AVO_SharePoint_File__c/fields/AVO_Permit__c.field-meta.xml
<CustomField>
    <fullName>AVO_Permit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Permit</label>
    <referenceTo>MUSW__Permit2__c</referenceTo>
    <relationshipLabel>SharePoint Files</relationshipLabel>
    <relationshipName>SharePoint_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AVO_SharePoint_File__c/fields/AVO_Review__c.field-meta.xml
<CustomField>
    <fullName>AVO_Review__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Review</label>
    <referenceTo>MUSW__Review__c</referenceTo>
    <relationshipLabel>SharePoint Files</relationshipLabel>
    <relationshipName>SharePoint_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AVO_SharePoint_File__c/fields/AVO_SharePoint_External_Link__c.field-meta.xml
<CustomField>
    <fullName>AVO_SharePoint_External_Link__c</fullName>
    <label>SharePoint External Link</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AVO_SharePoint_File__c/fields/AVO_SharePoint_Item_Id__c.field-meta.xml
<CustomField>
    <fullName>AVO_SharePoint_Item_Id__c</fullName>
    <label>SharePoint Item Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AVO_SharePoint_File__c/fields/AVO_SharePoint_URL__c.field-meta.xml
<CustomField>
    <fullName>AVO_SharePoint_URL__c</fullName>
    <label>SharePoint URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AVO_SharePoint_File__c/fields/AVO_SharePoint_URL_Text__c.field-meta.xml
<CustomField>
    <fullName>AVO_SharePoint_URL_Text__c</fullName>
    <label>SharePoint URL Text</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AVO_SharePoint_File__c/fields/AVO_Submission__c.field-meta.xml
<CustomField>
    <fullName>AVO_Submission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submission</label>
    <referenceTo>MUSW__Submission__c</referenceTo>
    <relationshipLabel>SharePoint Files</relationshipLabel>
    <relationshipName>SharePoint_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AVO_SharePoint_File__c/fields/AVO_Violation__c.field-meta.xml
<CustomField>
    <fullName>AVO_Violation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Violation</label>
    <referenceTo>MUSW__Violation__c</referenceTo>
    <relationshipLabel>SharePoint Files</relationshipLabel>
    <relationshipName>SharePoint_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AVO_SharePoint_File__c/fields/AVO_Withdrawal__c.field-meta.xml
<CustomField>
    <fullName>AVO_Withdrawal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Withdrawals</label>
    <referenceTo>AVO_Withdrawals__c</referenceTo>
    <relationshipLabel>SharePoint Files</relationshipLabel>
    <relationshipName>SharePoint_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AvoAttachmentCloneRevision.cls
public without sharing class AvoAttachmentCloneRevision {

    // Flow-Invocable version of syncFilesFromChildToParent
    @InvocableMethod(label='Sync Files From Child To Parent' description='Copies files from revision record to permit parent record with duplicate check and replacement')
    public static void syncFilesFromChildToParentFlow(List<SyncRequest> requests) {
        for (SyncRequest request : requests) {
            syncFilesFromChildToParent(request.childRecordId, request.parentRecordId);
            syncSharePointFilesFromChildToParent(request.childRecordId, request.parentRecordId);
        }
    }

    // Flow Input Wrapper
    public class SyncRequest {
        @InvocableVariable(label='Child Record Id' required=true)
        public Id childRecordId;

        @InvocableVariable(label='Parent Record Id' required=true)
        public Id parentRecordId;
    }

   public static void syncFilesFromChildToParent(Id childId, Id parentId) {
        List<ContentDocumentLink> childLinks = [
            SELECT ContentDocumentId
            FROM ContentDocumentLink
            WHERE LinkedEntityId = :childId
        ];
        List<ContentDocumentLink> parentLinks = [
            SELECT ContentDocumentId
            FROM ContentDocumentLink
            WHERE LinkedEntityId = :parentId
        ];

        Set<Id> childDocIds = new Set<Id>();
        Set<Id> parentDocIds = new Set<Id>();
        for (ContentDocumentLink link : childLinks) childDocIds.add(link.ContentDocumentId);
        for (ContentDocumentLink link : parentLinks) parentDocIds.add(link.ContentDocumentId);

        Set<Id> allDocIds = new Set<Id>();
        allDocIds.addAll(childDocIds);
        allDocIds.addAll(parentDocIds);

        List<ContentVersion> allVersions = [
            SELECT Id, Title, PathOnClient, VersionData, ContentDocumentId, CreatedDate
            FROM ContentVersion
            WHERE IsLatest = TRUE AND ContentDocumentId IN :allDocIds
        ];

        Map<Id, ContentVersion> childVersions = new Map<Id, ContentVersion>();
        Map<Id, ContentVersion> parentVersions = new Map<Id, ContentVersion>();
        for (ContentVersion ver : allVersions) {
            if (childDocIds.contains(ver.ContentDocumentId)) {
                childVersions.put(ver.ContentDocumentId, ver);
            } else if (parentDocIds.contains(ver.ContentDocumentId)) {
                parentVersions.put(ver.ContentDocumentId, ver);
            }
        }

        Map<String, ContentVersion> parentTitleMap = new Map<String, ContentVersion>();
        Map<String, Id> parentDocByTitle = new Map<String, Id>();
        for (ContentVersion pv : parentVersions.values()) {
            parentTitleMap.put(pv.Title, pv);
            parentDocByTitle.put(pv.Title, pv.ContentDocumentId);
        }

        List<ContentVersion> toInsert = new List<ContentVersion>();
        List<ContentDocument> toDelete = new List<ContentDocument>();

        for (ContentVersion childVer : childVersions.values()) {
            ContentVersion parentVer = parentTitleMap.get(childVer.Title);
            if (parentVer == null) {
                toInsert.add(new ContentVersion(
                    Title = childVer.Title,
                    PathOnClient = childVer.PathOnClient,
                    VersionData = childVer.VersionData,
                    FirstPublishLocationId = parentId
                ));
            } else if (childVer.CreatedDate > parentVer.CreatedDate) {
                toInsert.add(new ContentVersion(
                    Title = childVer.Title,
                    PathOnClient = childVer.PathOnClient,
                    VersionData = childVer.VersionData,
                    FirstPublishLocationId = parentId
                ));
                toDelete.add(new ContentDocument(Id = parentDocByTitle.get(childVer.Title)));
            }
        }

        if (!toInsert.isEmpty()) {
            insert toInsert;
        }

        if (!toDelete.isEmpty()) {
            delete toDelete;
        }
    }
    
     public static void syncSharePointFilesFromChildToParent(Id childId, Id parentId) {
        // Step 1: Get existing SharePoint files from both
		List<AVO_SharePoint_File__c> childRecords = [
            SELECT Id, Name, AVO_Account__c, AVO_Application__c, AVO_Comment__c, AVO_Complaint__c, AVO_Compliance__c, AVO_Contact__c, AVO_ContentDocumentId__c, CreatedById,
            AVO_Inspection__c, LastModifiedById, AVO_License__c, AVO_Meter__c, AVO_Meter_Codeset__c, AVO_Meter_Transaction__c, AVO_Meter_Withdrawal__c, AVO_Milestone__c,
            OwnerId, AVO_Permit__c, AVO_Review__c, AVO_SharePoint_External_Link__c, AVO_SharePoint_Item_Id__c, AVO_SharePoint_URL__c, AVO_SharePoint_URL_Text__c, AVO_Submission__c,
            AVO_Violation__c, AVO_Withdrawal__c
            FROM AVO_SharePoint_File__c
            WHERE AVO_Permit__c = :childId
        ]; 

         List<AVO_SharePoint_File__c> ParentRecords = [SELECT Name FROM AVO_SharePoint_File__c WHERE AVO_Permit__c = :parentId];
         Set<String> parentSharePointRecordNames = new Set<String>();
         
         for(AVO_SharePoint_File__c sharePointRecordName : ParentRecords){ parentSharePointRecordNames.add(sharePointRecordName.Name); }
         List<AVO_SharePoint_File__c> recordToInsert = new List<AVO_SharePoint_File__c>();
         
         for(AVO_SharePoint_File__c ChildRecord : childRecords){
             if(!parentSharePointRecordNames.contains(ChildRecord.Name)){
                 AVO_SharePoint_File__c cloneFile = ChildRecord.clone(false, true, false, false);
                 cloneFile.AVO_Permit__c = parentId;
                 recordToInsert.add(cloneFile);
             }
             
             if(recordToInsert.Size() > 0){
                 Insert recordToInsert;
             }
             
         }
         
     }
}