force-app/main/default/objects/AVO_Compliance__c/AVO_Compliance__c.object-meta.xml
<CustomObject>
    <label>Compliance</label>
    <nameField>
        <label>CompNum</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compliances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Compliance__c/fields/AVO_CompStatus__c.field-meta.xml
<CustomField>
    <fullName>AVO_CompStatus__c</fullName>
    <label>CompStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initialised</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Tracking</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <isActive>false</isActive>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Under Review</fullName>
                <isActive>false</isActive>
                <label>Under Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Compliance__c/fields/AVO_ResolvedDt__c.field-meta.xml
<CustomField>
    <fullName>AVO_ResolvedDt__c</fullName>
    <label>ResolvedDt</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AVO_Compliance__c/fields/AVO_ResTypeCode__c.field-meta.xml
<CustomField>
    <fullName>AVO_ResTypeCode__c</fullName>
    <label>ResTypeCode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active Meter Installed &amp; Approved for GW Withdrawal(s)</fullName>
            </value>
            <value>
                <fullName>Active Meter Installed &amp; Approved for SW Withdrawal(s)</fullName>
            </value>
            <value>
                <fullName>Active Meters Installed &amp; Approved For All Withdrawals on this Permit</fullName>
            </value>
            <value>
                <fullName>Add GW Withdrawal(s) To Existing Permit</fullName>
            </value>
            <value>
                <fullName>Add SW Withdrawal(s) To Existing Permit</fullName>
            </value>
            <value>
                <fullName>Ag Permit Revoked/Relinquished</fullName>
            </value>
            <value>
                <fullName>Ag Unpermitted Acres Not Currently In Use</fullName>
            </value>
            <value>
                <fullName>Already Plugged &amp; Abandoned Floridan Well</fullName>
            </value>
            <value>
                <fullName>Already Plugged &amp; Abandoned Non-Floridan Well</fullName>
            </value>
            <value>
                <fullName>Application Received for Undocumented Withdrawal(s)</fullName>
            </value>
            <value>
                <fullName>Capped Floridan Well / Not In Use</fullName>
            </value>
            <value>
                <fullName>Capped Non-Floridan Well / Not In Use</fullName>
            </value>
            <value>
                <fullName>Case Created In Error / Close Case</fullName>
            </value>
            <value>
                <fullName>Contractor Refunded Customer</fullName>
            </value>
            <value>
                <fullName>Contractor Resolved Customer’s Issues</fullName>
            </value>
            <value>
                <fullName>Corrected Permit</fullName>
            </value>
            <value>
                <fullName>Decrease Permitted Acres</fullName>
            </value>
            <value>
                <fullName>Decrease Permitted GW GPMs</fullName>
            </value>
            <value>
                <fullName>Decrease Permitted SW GPMs</fullName>
            </value>
            <value>
                <fullName>GW Withdrawal Activated/Use Established</fullName>
            </value>
            <value>
                <fullName>GW Withdrawal(s) Already Permitted</fullName>
            </value>
            <value>
                <fullName>Incomplete Construction of Floridan Well / Not in Use</fullName>
            </value>
            <value>
                <fullName>Incomplete Construction of Non-Floridan Well / Not In Use</fullName>
            </value>
            <value>
                <fullName>Increase Permitted Acres</fullName>
            </value>
            <value>
                <fullName>Increase Permitted GW GPMs</fullName>
            </value>
            <value>
                <fullName>Increase Permitted SW GPMs</fullName>
            </value>
            <value>
                <fullName>Irrigated Acres Already Permitted</fullName>
            </value>
            <value>
                <fullName>Irrigated Acres Taken Out of Use / Unable to Permit Acres</fullName>
            </value>
            <value>
                <fullName>LOC Requirements Complete</fullName>
            </value>
            <value>
                <fullName>Modification Requirements Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Submission_List__c/MUSW__Master_Submission_List__c.object-meta.xml
<CustomObject>
    <label>Submission Template</label>
    <nameField>
        <label>Submission Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Master_Submission_List__c/fields/Avo_Offset__c.field-meta.xml
<CustomField>
    <fullName>Avo_Offset__c</fullName>
    <label>Offset</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MUSW__Master_Submission_List__c/fields/Manual_Creation_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Manual_Creation_Allowed__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Manual Creation Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/MUSW__Permit2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Permit application details</description>
    <label>Permit</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_Operator_Manager__c.field-meta.xml
<CustomField>
    <fullName>AVO_Operator_Manager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Operator/Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Permits (Operator/Manager)</relationshipLabel>
    <relationshipName>Permits2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_Planned_Date_of_Pump_Installation__c.field-meta.xml
<CustomField>
    <fullName>AVO_Planned_Date_of_Pump_Installation__c</fullName>
    <label>Planned Date of Pump Installation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_Planned_Date_of_Well_Install__c.field-meta.xml
<CustomField>
    <fullName>AVO_Planned_Date_of_Well_Install__c</fullName>
    <label>Planned Date of Well Installation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_Property_Owner__c.field-meta.xml
<CustomField>
    <fullName>AVO_Property_Owner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Property Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Permits (Property Owner)</relationshipLabel>
    <relationshipName>Permits1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_PurIR__c.field-meta.xml
<CustomField>
    <fullName>AVO_PurIR__c</fullName>
    <label>Irrigation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_Volumetric_Limits__c.field-meta.xml
<CustomField>
    <fullName>AVO_Volumetric_Limits__c</fullName>
    <label>Volumetric Limits</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_ZeroAcreage__c.field-meta.xml
<CustomField>
    <fullName>AVO_ZeroAcreage__c</fullName>
    <label>Zero Acre Permit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Account__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the associated permit account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Permits as Account</relationshipLabel>
    <relationshipName>Permits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Applicant__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The applicant submitting the permit application.</description>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Permits as Applicant</relationshipLabel>
    <relationshipName>Applicant_Permit2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <description>Status of the permit as it moves through the business workflow.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Submitted Documents</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Transaction</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Finaled</fullName>
            </value>
            <value>
                <fullName>Enforcement</fullName>
            </value>
            <value>
                <fullName>Initial Review</fullName>
            </value>
            <value>
                <fullName>LOC Package</fullName>
            </value>
            <value>
                <fullName>LOC Issued</fullName>
            </value>
            <value>
                <fullName>LOC Documents Uploaded</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Form Assessment</fullName>
            </value>
            <value>
                <fullName>Final Evaluation</fullName>
            </value>
            <value>
                <fullName>Permit Approval</fullName>
            </value>
            <value>
                <fullName>Revision Approval</fullName>
            </value>
            <value>
                <fullName>Ready for Issuance</fullName>
            </value>
            <value>
                <fullName>Permit Issued</fullName>
            </value>
            <value>
                <fullName>Revision Issued</fullName>
            </value>
            <value>
                <fullName>Issued</fullName>
            </value>
            <value>
                <fullName>Permit Rejected</fullName>
            </value>
            <value>
                <fullName>Consolidated</fullName>
            </value>
            <value>
                <fullName>Permit Denied</fullName>
            </value>
            <value>
                <fullName>Revision Denied</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Undocumented Source</fullName>
            </value>
            <value>
                <fullName>APPLICATION GIS MAPPING</fullName>
            </value>
            <value>
                <fullName>Undocumented Source Pending Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <description>The permit type. This is typically related to the record type.</description>
    <label>Type (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agricultural Surface Water Pump</fullName>
            </value>
            <value>
                <fullName>Agricultural Water Withdrawal Application</fullName>
            </value>
            <value>
                <fullName>Agricultural Water Withdrawal Permit</fullName>
            </value>
            <value>
                <fullName>Agricultural Well Pump</fullName>
            </value>
            <value>
                <fullName>Application for Permit Consolidation</fullName>
            </value>
            <value>
                <fullName>Revision</fullName>
            </value>
            <value>
                <fullName>Permit Relinquishment</fullName>
            </value>
            <value>
                <fullName>Well and Pump Data</fullName>
            </value>
            <value>
                <fullName>Well Plug and Abandonment</fullName>
            </value>
            <value>
                <fullName>AG Water Metering Installation</fullName>
            </value>
            <value>
                <fullName>Undocumented Source</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AvoSubmissionDataRetrieverControllerTest.cls
@isTest
public class AvoSubmissionDataRetrieverControllerTest {
     @TestSetup
    static void dataSetup() {
             Account acc = new Account(
            Name = 'Michael L',
            BillingStreet = '123 Michael Street',
            BillingCity = 'Surrey',
            BillingState = 'BC',
            BillingPostalCode = '12345',
            BillingCountry = 'Canada'
        );
        insert acc;
        Contact contact = new Contact(
            LastName = 'Inc.',
            AccountId = acc.Id
        );
        insert contact;

 
        
        MUSW__Permit2__c entity = new MUSW__Permit2__c(
            MUSW__Type__c = 'Agricultural Water Withdrawal Application',
            MUSW__Status__c = 'Pending',
           // MUSW__Account__c = contact.AccountId,
           // MUSW__Applicant__c = contact.id,
            AVO_Planned_Date_of_Well_Install__c =system.today().addDays(-1),
            AVO_Planned_Date_of_Pump_Installation__c = system.today().addDays(-1),
            AVO_Property_Owner__c =contact.id,
            AVO_Operator_Manager__c = contact.id,
            AVO_PurIR__c = 'No',
            AVO_ZeroAcreage__c = 'No',
            AVO_Volumetric_Limits__c = 1
        );
        insert entity;      
        
            AVO_Compliance__c compliance = new AVO_Compliance__c(
            Name = 'Test Compliance',
            AVO_CompStatus__c = 'Resolved',
            AVO_ResolvedDt__c = System.today(),                  // Required field
            AVO_ResTypeCode__c = 'Corrective Action Taken'       // Required field
        );
        insert compliance;
        
        Id devRecordTypeId = Schema.SObjectType.MUSW__Master_Submission_List__c.getRecordTypeInfosByName().get('Application Submission').getRecordTypeId();
        
        MUSW__Master_Submission_List__c mstrSub = new MUSW__Master_Submission_List__c();
        mstrSub.Name ='testMaster';
        mstrSub.RecordTypeId =devRecordTypeId;
       // mstrSub.Permit_Type__c ='Groundwater';
        mstrSub.avo_Offset__c =2;
        mstrSub.Effective_Start_Date__c = system.today().addDays(-1); 
        mstrSub.Effective_End_Date__c = system.today().addDays(+5);
        mstrSub.Manual_Creation_Allowed__c = true;
        insert mstrSub;
        
    }
    @isTest
    private static void testgetAllowedSubmissionTypes(){
        Id recordId = [Select id from MUSW__Permit2__c limit 1].Id;
        Test.startTest();
        string Result = AvoSubmissionDataRetrieverController.getAllowedSubmissionTypes(recordId,'MUSW__Permit2__c');
        Test.stopTest();
        System.assertNotEquals(null, Result);
    }  
    
    @isTest
    private static void testgetSubmissionRecordTypeId(){
        string mstr = [select id,name from MUSW__Master_Submission_List__c where name='testMaster' limit 1].id; 
        //Id devRecordTypeId = Schema.SObjectType.MUSW__Master_Submission_List__c.getRecordTypeInfosByName().get('eb Submission Default').getRecordTypeId();
        //string recordType=string.valueOf(devRecordTypeId);
        Test.startTest();
        Id resultId = AvoSubmissionDataRetrieverController.getSubmissionRecordTypeId(mstr);
        Test.stopTest();
        System.assertNotEquals(null, resultId);
        
    }
    
    
    @isTest
    Private static void testgetSubmissionInformation(){
        string recordId = [select id,name from MUSW__Master_Submission_List__c  limit 1 ].id;
        AvoSubmissionDataRetrieverController.getSubmissionInformation(recordId);
    }
    
    @isTest
    private static void testCalculateDueDate(){
        MUSW__Master_Submission_List__c record =[
            SELECT Name, avo_Offset__c, avo_Offset_Type__c,Required__c
            FROM MUSW__Master_Submission_List__c LIMIT 1];
        Test.startTest();
        date resultdate = AvoSubmissionDataRetrieverController.CalculateDueDate(record);
        Test.stopTest();
        System.assertNotEquals(null, resultdate);
    }
    @isTest
    private static void testcreateSubmissions(){
        List<String> ids = new List<String>();
        List<MUSW__Permit2__c> recordid = [Select id from MUSW__Permit2__c limit 1];
        List<MUSW__Master_Submission_List__c> listids = [SELECT Id,Name,RecordTypeId,avo_Offset_Type__c
                                                         FROM MUSW__Master_Submission_List__c limit 2];
        for(MUSW__Master_Submission_List__c a :listids){
            ids.add(a.Id);
        }
        String Objectname ='MUSW__Permit2__c';
        Test.startTest();
        Id result = AvoSubmissionDataRetrieverController.createSubmissions(recordid[0].Id,ids,Objectname);
        Test.stopTest();
        System.assertNotEquals(null,result);
    }
        @isTest
    private static void testcreateSubmissionsCompliance(){
        List<String> ids = new List<String>();
        List<AVO_Compliance__c> recordid = [Select id from AVO_Compliance__c limit 1];
        List<MUSW__Master_Submission_List__c> listids = [SELECT Id,Name,RecordTypeId,avo_Offset_Type__c
                                                         FROM MUSW__Master_Submission_List__c limit 2];
        for(MUSW__Master_Submission_List__c a :listids){
            ids.add(a.Id);
        }
        String Objectname ='AVO_Compliance__c';
        Test.startTest();
        Id result = AvoSubmissionDataRetrieverController.createSubmissions(recordid[0].Id,ids,Objectname);
        Test.stopTest();
        System.assertNotEquals(null,result);
    }
    @istest
    public static void testcreateSubmissionsWithConfig(){
        string objname='MUSW__Permit2__c';
        //string recordId =[select id,name,MUSW__Status__c from MUSW__Permit2__c where MUSW__Status__c='Submitted' Limit 1 ].id;
        string recordId =[select id,name,MUSW__Status__c from MUSW__Permit2__c Limit 1 ].id;
        string masterRecId = [select id,name from MUSW__Master_Submission_List__c  limit 1 ].id;
        map<string,boolean> testMap=new map<string,boolean>();
        testMap.put(masterRecId, true);
        AvoSubmissionDataRetrieverController.createSubmissionsWithConfig(recordId, testMap, objname);
    }
    
    @istest
    public static void testcreateSubmissionsWithConfigCompliance(){
        string objname='AVO_Compliance__c';
        string recordId =[select id,name from AVO_Compliance__c Limit 1 ].id;
        string masterRecId = [select id,name from MUSW__Master_Submission_List__c  limit 1 ].id;
        map<string,boolean> testMap=new map<string,boolean>();
        testMap.put(masterRecId, true);
        AvoSubmissionDataRetrieverController.createSubmissionsWithConfig(recordId, testMap, objname);
    }

}