force-app/main/default/objects/AVO_Compliance__c/AVO_Compliance__c.object-meta.xml
<CustomObject>
    <label>Compliance</label>
    <nameField>
        <label>CompNum</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compliances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clariti__Payment__c/clariti__Payment__c.object-meta.xml
<CustomObject>
    <description>Payment is used to record the amount collected per payment method during the cart transaction</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{MM}{DD}{YYYY}-{000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clariti__Payment__c/fields/clariti__Payment__c.field-meta.xml
<CustomField>
    <fullName>clariti__Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>clariti__Payment__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clariti__Payment__c/fields/clariti__PaymentAmount__c.field-meta.xml
<CustomField>
    <fullName>clariti__PaymentAmount__c</fullName>
    <description>Payment amount collected for the payment transaction.</description>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/clariti__PaymentAllocation__c/clariti__PaymentAllocation__c.object-meta.xml
<CustomObject>
    <description>Payment Allocation is used to record amounts against the individual payable items e.g. Fees, Deposits, etc.</description>
    <label>Payment Allocation</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Payment Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/clariti__PaymentAllocation__c/fields/AVO_Compliance__c.field-meta.xml
<CustomField>
    <fullName>AVO_Compliance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compliance</label>
    <referenceTo>AVO_Compliance__c</referenceTo>
    <relationshipLabel>Payment Allocations</relationshipLabel>
    <relationshipName>Payment_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clariti__PaymentAllocation__c/fields/clariti__Fee__c.field-meta.xml
<CustomField>
    <fullName>clariti__Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fee</label>
    <referenceTo>MUSW__Fee__c</referenceTo>
    <relationshipLabel>Payment Allocations</relationshipLabel>
    <relationshipName>PaymentAllocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clariti__PaymentAllocation__c/fields/clariti__Payment__c.field-meta.xml
<CustomField>
    <fullName>clariti__Payment__c</fullName>
    <label>Payment</label>
    <referenceTo>clariti__Payment__c</referenceTo>
    <relationshipLabel>Payment Allocations</relationshipLabel>
    <relationshipName>PaymentAllocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MUSW__Fee__c/MUSW__Fee__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Fees/Fines associated to Permits, Complaints, Planning Applications</description>
    <label>Fee</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Fee__c/fields/AVO_Compliance__c.field-meta.xml
<CustomField>
    <fullName>AVO_Compliance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compliance</label>
    <referenceTo>AVO_Compliance__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Fee__c/fields/MUSW__Amount__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Amount__c</fullName>
    <description>An obligation amount (fee) that needs to be paid.</description>
    <inlineHelpText>Leave blank for default value (set after Save)</inlineHelpText>
    <label>Total</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AvoPaymentAllocationUpdateTriggerTest.cls
@isTest
public class AvoPaymentAllocationUpdateTriggerTest {

    @isTest
    static void testPaymentAllocationTrigger() {
         AVO_Compliance__c compliance = new AVO_Compliance__c(Name = 'Compliance Doc');
    insert compliance;
        // Step 1: Create a test MUSW__Fee__c record
        MUSW__Fee__c testFee = new MUSW__Fee__c(
            MUSW__Amount__c = 10 ,
            AVO_Compliance__c = compliance.id
        );
        insert testFee;
        
        clariti__Payment__c  payment = new clariti__Payment__c(
            clariti__PaymentAmount__c = 10
        );
        insert payment;

        // Step 2: Create a test clariti__PaymentAllocation__c record linked to the fee
        clariti__PaymentAllocation__c testPA = new clariti__PaymentAllocation__c(
         //   Name = 'Test PA',
            clariti__Fee__c = testFee.Id,
            AVO_Compliance__c = compliance.id,
            clariti__Payment__c = payment.id
        );

        Test.startTest();
        insert testPA;
        Test.stopTest();

        // Step 3: Query and assert that AVO_Compliance__c was updated correctly
        clariti__PaymentAllocation__c insertedPA = [
            SELECT Id, AVO_Compliance__c, clariti__Fee__c 
            FROM clariti__PaymentAllocation__c 
            WHERE Id = :testPA.Id
        ];
        
    }
}