force-app/main/default/objects/AVO_Compliance__c/AVO_Compliance__c.object-meta.xml
<CustomObject>
    <label>Compliance</label>
    <nameField>
        <label>CompNum</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compliances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Compliance__c/fields/AVO_CaseClass__c.field-meta.xml
<CustomField>
    <fullName>AVO_CaseClass__c</fullName>
    <label>CaseClass</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Permit Violations Compliance Case</fullName>
            </value>
            <value>
                <fullName>WWSA Compliance Case</fullName>
            </value>
            <value>
                <fullName>Meter Compliance Case</fullName>
            </value>
            <value>
                <fullName>Non-Initialized Use Case</fullName>
            </value>
            <value>
                <fullName>Statutory Compliance Case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Compliance__c/fields/AVO_Type__c.field-meta.xml
<CustomField>
    <fullName>AVO_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compliance Case</fullName>
            </value>
            <value>
                <fullName>Farmer Initiated Online Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <label>Type (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Variance</fullName>
            </value>
            <value>
                <fullName>Development Permit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Submission_List__c/MUSW__Master_Submission_List__c.object-meta.xml
<CustomObject>
    <label>Submission Template</label>
    <nameField>
        <label>Submission Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Master_Submission_List__c/fields/AVO_Case_Class__c.field-meta.xml
<CustomField>
    <fullName>AVO_Case_Class__c</fullName>
    <label>Case Class</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Permit Violations Compliance Case</fullName>
            </value>
            <value>
                <fullName>WWSA Compliance Case</fullName>
            </value>
            <value>
                <fullName>Meter Compliance Case</fullName>
            </value>
            <value>
                <fullName>Non-Initialized Use Case</fullName>
            </value>
            <value>
                <fullName>Statutory Compliance Case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Submission_List__c/fields/Avo_Compliance_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Compliance_Type__c</fullName>
    <label>Compliance Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Compliance_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Submission_List__c/fields/Avo_Offset__c.field-meta.xml
<CustomField>
    <fullName>Avo_Offset__c</fullName>
    <label>Offset</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MUSW__Master_Submission_List__c/fields/Avo_Offset_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Offset_Type__c</fullName>
    <label>Offset Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business Days</fullName>
            </value>
            <value>
                <fullName>Calendar Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Submission_List__c/fields/Avo_Permit_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Permit_Type__c</fullName>
    <label>Permit Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Permit_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Submission_List__c/fields/Manual_Creation_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Manual_Creation_Allowed__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Manual Creation Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MUSW__Master_Submission_List__c/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <label>Record Type</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MUSW__Master_Submission_List__c/recordTypes/Permit.recordType-meta.xml
<RecordType>
    <fullName>Permit</fullName>
    <active>true</active>
    <description>Permit Submissions</description>
    <label>Permit</label>
</RecordType>

force-app/main/default/objects/MUSW__Permit2__c/MUSW__Permit2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Permit application details</description>
    <label>Permit</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_Permit_Type__c.field-meta.xml
<CustomField>
    <fullName>AVO_Permit_Type__c</fullName>
    <label>Permit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AVO_Withdrawal_Permit_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <description>The permit type. This is typically related to the record type.</description>
    <label>Type (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agricultural Surface Water Pump</fullName>
            </value>
            <value>
                <fullName>Agricultural Water Withdrawal Application</fullName>
            </value>
            <value>
                <fullName>Agricultural Water Withdrawal Permit</fullName>
            </value>
            <value>
                <fullName>Agricultural Well Pump</fullName>
            </value>
            <value>
                <fullName>Application for Permit Consolidation</fullName>
            </value>
            <value>
                <fullName>Revision</fullName>
            </value>
            <value>
                <fullName>Permit Relinquishment</fullName>
            </value>
            <value>
                <fullName>Well and Pump Data</fullName>
            </value>
            <value>
                <fullName>Well Plug and Abandonment</fullName>
            </value>
            <value>
                <fullName>AG Water Metering Installation</fullName>
            </value>
            <value>
                <fullName>Undocumented Source</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Submission__c/MUSW__Submission__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Tracks online files</description>
    <label>Submission</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Submission__c/fields/AVO_Compliance__c.field-meta.xml
<CustomField>
    <fullName>AVO_Compliance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compliance</label>
    <referenceTo>AVO_Compliance__c</referenceTo>
    <relationshipLabel>Submissions</relationshipLabel>
    <relationshipName>Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Submission__c/fields/MUSW__Application2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Application2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>Submissions</relationshipLabel>
    <relationshipName>Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Submission__c/fields/MUSW__Due_Date__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Due_Date__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MUSW__Submission__c/fields/MUSW__Permit2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Permit2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Permit</label>
    <referenceTo>MUSW__Permit2__c</referenceTo>
    <relationshipLabel>Submissions</relationshipLabel>
    <relationshipName>Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Submission__c/fields/MUSW__Requested_DateTime__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Requested_DateTime__c</fullName>
    <label>Requested Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MUSW__Submission__c/fields/MUSW__Required__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MUSW__Submission__c/fields/MUSW__Submission_Template__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Submission_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submission Template</label>
    <referenceTo>MUSW__Master_Submission_List__c</referenceTo>
    <relationshipLabel>Submissions</relationshipLabel>
    <relationshipName>Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Avo_Compliance_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Compliance Case</fullName>
    </customValue>
    <masterLabel>Avo Compliance Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Avo_Permit_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agricultural Water Withdrawal Application</fullName>
    </customValue>
    <customValue>
        <fullName>Agricultural Water Withdrawal Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Application for Permit Consolidation</fullName>
    </customValue>
    <customValue>
        <fullName>Revision</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation Request</fullName>
    </customValue>
    <customValue>
        <fullName>Permit Relinquishment</fullName>
    </customValue>
    <customValue>
        <fullName>Well and Pump Data</fullName>
    </customValue>
    <customValue>
        <fullName>Well Plug &amp; Abandonment</fullName>
    </customValue>
    <customValue>
        <fullName>AG Water Metering Installation</fullName>
    </customValue>
    <masterLabel>Avo Permit Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/AVO_Withdrawal_Permit_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Groundwater</fullName>
    </customValue>
    <customValue>
        <fullName>Surface Water</fullName>
    </customValue>
    <customValue>
        <fullName>Well to Pond</fullName>
    </customValue>
    <customValue>
        <fullName>Undocumented Source</fullName>
        <isActive>false</isActive>
        <label>Undocumented Source</label>
    </customValue>
    <masterLabel>AVO Withdrawal Permit Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AvoSubmissionDataRetrieverController.cls
/**
 * Apex Controller used in AvoNewSubmissionController.js. Makes calls to GET and POST data for Submission Objects.
 * @author Michael Chung
 * last modified by Michael Chung
 * @date 05/13/2021
 * 
 */

public class AvoSubmissionDataRetrieverController {
// Method that returns the supported submission types for a specific Record ID.
    // The return value should be in a CSV format for multiple submission types
    @AuraEnabled
    public static String getAllowedSubmissionTypes(Id recordId, String sObjectName) {   
        String response = '';
        ResponseJSONWrapper wrapper = new ResponseJSONWrapper();
        List<MUSW__Master_Submission_List__c> submissionTypes;

        // step 1 - get a list of allowed submission types
        if(sObjectName == 'MUSW__Permit2__c') {
            // get the Permit Type and Id
            MUSW__Permit2__c permit = [
                SELECT Id, MUSW__Type__c
                FROM MUSW__Permit2__c
                WHERE Id = :recordId
            ];

            String permitType = permit.MUSW__Type__c;

            // Get the Master Submission List items that include the Permit Type
            submissionTypes = [
                SELECT Name, Id 
                FROM MUSW__Master_Submission_List__c 
                WHERE Avo_Permit_Type__c includes (:permitType)
                AND Active__c = true
                AND Manual_Creation_Allowed__c = true 
                ORDER BY Name ASC 
            ];
        }
        // step 2 - get a list of allowed submission types
        if(sObjectName == 'AVO_Compliance__c') {
            // get the Permit Type and Id
            AVO_Compliance__c Compliance = [
                SELECT Id,
                	   AVO_Type__c ,
                       AVO_CaseClass__c
                FROM AVO_Compliance__c
                WHERE Id = :recordId
            ];

            String complianceType = Compliance.AVO_Type__c;
			String caseClass = Compliance.AVO_CaseClass__c;

            // Get the Master Submission List items that include the Permit Type
            submissionTypes = [
                SELECT Name, Id 
                FROM MUSW__Master_Submission_List__c 
                WHERE Avo_Compliance_Type__c includes (:complianceType)
				AND AVO_Case_Class__c includes (:caseClass)  
                AND Active__c = true
                AND Manual_Creation_Allowed__c = true 
                ORDER BY Name ASC 
            ];
        }
        else{}

        wrapper.id = recordId;
        wrapper.submissionTypeList = new List<Option>();
    system.debug('only'+submissionTypes);
        for(MUSW__Master_Submission_List__c submissionType:submissionTypes)
        {
            Option option = new Option();

            option.label = submissionType.Name;
            option.value = submissionType.Id;
            
            // Adding Option objects (label & value) into the submissionTypeList
            wrapper.submissionTypeList.Add(option);
        }
        
        response = JSON.serialize(wrapper);
        system.debug('response'+response);

        return response;
    }   

    @AuraEnabled
    // Helper function used to determine the record type of the submission being created. The return record type will determine a different layout and dropdown listbox values for the submission to be created
    public static Id getSubmissionRecordTypeId(String masterSubmissionListId) {
        system.debug('Test'+ masterSubmissionListId);
            List<MUSW__Master_Submission_List__c> results = [
                SELECT Record_Type__c,RecordTypeId,RecordType.Name 
                FROM MUSW__Master_Submission_List__c
                WHERE Id =:masterSubmissionListId 	 
                LIMIT 1] ; 
            If (results.size() == 1) {
                
                Id recordTypeId = Schema.SObjectType.MUSW__Master_Submission_List__c.getRecordTypeInfosByName().get(results[0].RecordType.Name).getRecordTypeId();
                // MUSW__Submission__c to MUSW__Master_Submission_List__c
                 system.debug('Test'+recordTypeId);
                return recordTypeId;    
            } else {
                return Schema.SObjectType.MUSW__Master_Submission_List__c.getRecordTypeInfosByName().get('eb Submission Default').getRecordTypeId();
            } 
        //} catch (Exception ex) {
         //   return Schema.SObjectType.MUSW__Master_Submission_List__c.getRecordTypeInfosByName().get('Avo Submission Default').getRecordTypeId();
        //}
    }

    @AuraEnabled
    // Helper function used to get the Master Submission List item's name based off of the Master Submission List ID
    public static MUSW__Master_Submission_List__c getSubmissionInformation(String masterSubmissionListId) {
        system.debug('masterSubmissionListId>>>'+masterSubmissionListId);
        List<MUSW__Master_Submission_List__c> recordTypeId = [
            SELECT Name, Avo_Offset__c, Avo_Offset_Type__c,Required__c
            FROM MUSW__Master_Submission_List__c
            WHERE Id = :masterSubmissionListId
        ];

        return recordTypeId[0];
    }

    @AuraEnabled
    public static date CalculateDueDate(MUSW__Master_Submission_List__c item) {
        Date dueDate = Date.today();
        Integer offset =  item.Avo_Offset__c  == null? 0 :  Integer.valueOf(item.Avo_Offset__c);

        if (item.Avo_Offset_Type__c == 'Business Days') {
            dueDate = AvoCommon.AddBusinessDays(date.today(), offset);
        } else {
            dueDate = dueDate.addDays( offset);
        }

        return dueDate;
    }

 
    
    @AuraEnabled
    // Method used to create 1 or more Submissions
    public static Id createSubmissions(String recordId, List<String> masterSubmissionListIds, String sObjectName) {
        List<MUSW__Submission__c> submissions = new List<MUSW__Submission__c>();
        Id convertedId = Id.valueOf(recordId);
   system.debug('get'+recordId);
            system.debug('get1'+masterSubmissionListIds);

        if(sObjectName == 'MUSW__Permit2__c') {
            MUSW__Permit2__c permit = [
                SELECT MUSW__Type__c 
                FROM MUSW__Permit2__c 
                WHERE Id = :recordId
            ];
            //system.debug('get'+recordId);
           // system.debug('get1'+masterSubmissionListIds);
            // Create submission object(s) to then insert it into the DB
            for(String masterSubmissionListId : masterSubmissionListIds) {

                MUSW__Master_Submission_List__c item = getSubmissionInformation(masterSubmissionListId);
                
                MUSW__Submission__c submission = new MUSW__Submission__c(
                  //  Avo_Type__c  = item.Name,
                    MUSW__Permit2__c = convertedId,
                    Name = item.Name,
                    MUSW__Submission_Template__c = masterSubmissionListId,
                    MUSW__Requested_DateTime__c = DateTime.now(),
                    MUSW__Due_Date__c =  CalculateDueDate(item),
                    MUSW__Required__c = item.Required__c
                );
                submissions.add(submission);
            }
            insert submissions;
        }
 
  //For Compliance     
       if(sObjectName == 'AVO_Compliance__c') {
            AVO_Compliance__c permit = [
                SELECT AVO_Type__c 
                FROM AVO_Compliance__c 
                WHERE Id = :recordId
            ];
            //system.debug('get'+recordId);
           // system.debug('get1'+masterSubmissionListIds);
            // Create submission object(s) to then insert it into the DB
            for(String masterSubmissionListId : masterSubmissionListIds) {

                MUSW__Master_Submission_List__c item = getSubmissionInformation(masterSubmissionListId);
                
                MUSW__Submission__c submission = new MUSW__Submission__c(
                  //  Avo_Type__c  = item.Name,
                    AVO_Compliance__c = convertedId,
                    Name = item.Name,
                    MUSW__Submission_Template__c = masterSubmissionListId,
                    MUSW__Requested_DateTime__c = DateTime.now(),
                    MUSW__Due_Date__c =  CalculateDueDate(item),
                    MUSW__Required__c = item.Required__c
                );
                submissions.add(submission);
            }
            insert submissions;
        }

       /* if (sObjectName == 'MUSW__Application2__c') {
            MUSW__Application2__c application = [
                SELECT MUSW__Type__c 
                FROM MUSW__Application2__c 
                WHERE Id = :recordId
            ];
            // Create submission object(s) to then insert it into the DB
            for(String masterSubmissionListId : masterSubmissionListIds) {

                MUSW__Master_Submission_List__c item = getSubmissionInformation(masterSubmissionListId);

                MUSW__Submission__c submission = new MUSW__Submission__c(
                  //  Avo_Type__c       = item.Name,
                    MUSW__Application2__c        = convertedId,
                    Name = item.Name,
                    MUSW__Submission_Template__c = masterSubmissionListId,
                    MUSW__Requested_DateTime__c = DateTime.now(),
                    MUSW__Due_Date__c =  CalculateDueDate(item)
                );
                submissions.add(submission);
            }
            insert submissions;
        }*/
        // Return the first ID in the submissions. This works if 1 or more submissions are added.
        return submissions[0].id;
    }
 
    // Method used to create 1 or more Submissions
 	@AuraEnabled
    public static Id createSubmissionsWithConfig(String recordId, Map<String, boolean> masterListIdConfig, String sObjectName) {
        List<MUSW__Submission__c> submissions = new List<MUSW__Submission__c>();
        Id convertedId = Id.valueOf(recordId);
 

        if(sObjectName == 'MUSW__Permit2__c') {
            MUSW__Permit2__c permit = [
                SELECT MUSW__Type__c 
                FROM MUSW__Permit2__c 
                WHERE Id = :recordId
            ];
            // Create submission object(s) to then insert it into the DB
            for(String masterSubmissionListId : masterListIdConfig.keySet()) {

                MUSW__Master_Submission_List__c item = getSubmissionInformation(masterSubmissionListId);

                MUSW__Submission__c submission = new MUSW__Submission__c(
                 //   Avo_Type__c  = item.Name,
                    MUSW__Permit2__c        = convertedId,
                    Name = item.Name,
                    MUSW__Required__c = masterListIdConfig.get(masterSubmissionListId),
                    MUSW__Submission_Template__c = masterSubmissionListId,
                    MUSW__Requested_DateTime__c = DateTime.now(),
                    MUSW__Due_Date__c =CalculateDueDate(item)
                );
                submissions.add(submission);
            }
            insert submissions;
        }
        
  //For Compliance     
        if(sObjectName == 'AVO_Compliance__c') {
            AVO_Compliance__c permit = [
                SELECT AVO_Type__c 
                FROM AVO_Compliance__c 
                WHERE Id = :recordId
            ];
            // Create submission object(s) to then insert it into the DB
            for(String masterSubmissionListId : masterListIdConfig.keySet()) {

                MUSW__Master_Submission_List__c item = getSubmissionInformation(masterSubmissionListId);

                MUSW__Submission__c submission = new MUSW__Submission__c(
                 //   Avo_Type__c  = item.Name,
                    AVO_Compliance__c = convertedId,
                    Name = item.Name,
                    MUSW__Required__c = masterListIdConfig.get(masterSubmissionListId),
                    MUSW__Submission_Template__c = masterSubmissionListId,
                    MUSW__Requested_DateTime__c = DateTime.now(),
                    MUSW__Due_Date__c =CalculateDueDate(item)
                );
                submissions.add(submission);
            }
            insert submissions;
        }


      /*  if (sObjectName == 'MUSW__Application2__c') {
            MUSW__Application2__c application = [
                SELECT MUSW__Type__c 
                FROM MUSW__Application2__c 
                WHERE Id = :recordId
            ];
            // Create submission object(s) to then insert it into the DB
            for(String masterSubmissionListId : masterListIdConfig.keySet()) {

                MUSW__Master_Submission_List__c item = getSubmissionInformation(masterSubmissionListId);

                MUSW__Submission__c submission = new MUSW__Submission__c(
                    Avo_Type__c       = item.Name,
                    MUSW__Application2__c        = convertedId,
                    Name = item.Name,
                    MUSW__Required__c = masterListIdConfig.get(masterSubmissionListId),
                    MUSW__Submission_Template__c = masterSubmissionListId,
                    MUSW__Requested_DateTime__c = DateTime.now(),
                    MUSW__Due_Date__c =  CalculateDueDate(item)
                );
                submissions.add(submission);
            }
            insert submissions;
        } */
        // Return the first ID in the submissions. This works if 1 or more submissions are added.
        return submissions[0].id;
    }
    
    // Response JSON Wrapper Class
    public class ResponseJSONWrapper {
        public Id id;
        public List<Option> submissionTypeList;
    }

    // Object used to hold label and Id value for the submissions.
    public class Option {
        public String label;
        public String value;
    }
}