force-app/main/default/objects/MUSW__Submission__c/MUSW__Submission__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Tracks online files</description>
    <label>Submission</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Submission__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AvoSubmissionTriggerHandler.cls
/**
 * Description of class
 * trigger proxy for submisisons
 * @author Jason Li
 * last modified by Jason Li
 * @date 06/28/2021
 *  
 */
public class AvoSubmissionTriggerHandler extends AvoTriggerHandler { 
    
    public override void afterUpdate() {
        for(MUSW__Submission__c submission : (List<MUSW__Submission__c>) Trigger.new) { 
            MUSW__Submission__c oldSubmission = (MUSW__Submission__c)Trigger.oldMap.get(submission.Id);
            string oldStatus =  submission.MUSW__Status__c;
            string newStatus =  oldSubmission.MUSW__Status__c;
            System.debug('Triggering submission process engine');
           if (oldStatus <> newStatus){
                // task status has changed
                AvoProcessEngineSubmission engine = new AvoProcessEngineSubmission(submission);
                engine.run();
            }            
        }
    }
}