force-app/main/default/objects/AVO_Meter__c/AVO_Meter__c.object-meta.xml
<CustomObject>
    <label>Meter</label>
    <nameField>
        <label>Meter Serial Number (MSN)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Meter__c/fields/AVO_Status__c.field-meta.xml
<CustomField>
    <fullName>AVO_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>To be Updated</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Meter__c/fields/AVO_Type__c.field-meta.xml
<CustomField>
    <fullName>AVO_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Meter</fullName>
            </value>
            <value>
                <fullName>AG Water Metering Installation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Meter__c/recordTypes/Meter.recordType-meta.xml
<RecordType>
    <fullName>Meter</fullName>
    <active>true</active>
    <label>Meter</label>
</RecordType>

force-app/main/default/objects/AVO_Meter_Codeset__c/AVO_Meter_Codeset__c.object-meta.xml
<CustomObject>
    <label>Meter Codeset</label>
    <nameField>
        <label>Meter Codeset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meter Codesets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Meter_Codeset__c/fields/AVO_Make_ID__c.field-meta.xml
<CustomField>
    <fullName>AVO_Make_ID__c</fullName>
    <externalId>true</externalId>
    <label>Make ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AVO_Meter_Codeset__c/fields/AVO_Meter_Make__c.field-meta.xml
<CustomField>
    <fullName>AVO_Meter_Make__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meter Make</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Must look up to a Meter Make.</errorMessage>
        <filterItems>
            <field>AVO_Meter_Codeset__c.AVO_Type__c</field>
            <operation>equals</operation>
            <value>Meter Make</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AVO_Meter_Codeset__c</referenceTo>
    <relationshipLabel>Meter Models</relationshipLabel>
    <relationshipName>Meter_Models</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AVO_Meter_Codeset__c/fields/AVO_Model_ID__c.field-meta.xml
<CustomField>
    <fullName>AVO_Model_ID__c</fullName>
    <externalId>true</externalId>
    <label>Model ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AVO_Meter_Codeset__c/fields/AVO_Status__c.field-meta.xml
<CustomField>
    <fullName>AVO_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Meter_Codeset__c/fields/AVO_Type__c.field-meta.xml
<CustomField>
    <fullName>AVO_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Meter Make</fullName>
            </value>
            <value>
                <fullName>Meter Model</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Meter_Transaction__c/AVO_Meter_Transaction__c.object-meta.xml
<CustomObject>
    <label>Meter Transaction</label>
    <nameField>
        <label>Meter Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meter Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Meter_Transaction__c/fields/AVO_Batch_Status__c.field-meta.xml
<CustomField>
    <fullName>AVO_Batch_Status__c</fullName>
    <label>Batch Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Review Required</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Meter_Transaction__c/fields/AVO_Batch_Type__c.field-meta.xml
<CustomField>
    <fullName>AVO_Batch_Type__c</fullName>
    <label>Batch Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Batch Meter Entry</fullName>
            </value>
            <value>
                <fullName>Batch Meter Reading</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Meter_Transaction__c/fields/AVO_Type__c.field-meta.xml
<CustomField>
    <fullName>AVO_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agricultural Flow Meter Approval</fullName>
            </value>
            <value>
                <fullName>AG Water Metering Installation</fullName>
            </value>
            <value>
                <fullName>Batch Meter Entry</fullName>
            </value>
            <value>
                <fullName>Meter Allocation</fullName>
            </value>
            <value>
                <fullName>Meter Application</fullName>
            </value>
            <value>
                <fullName>Batch Meter Reading</fullName>
            </value>
            <value>
                <fullName>Meter Maintenance Request</fullName>
            </value>
            <value>
                <fullName>Meter Reading</fullName>
            </value>
            <value>
                <fullName>Meter Update</fullName>
            </value>
            <value>
                <fullName>Meter Entry</fullName>
            </value>
            <value>
                <fullName>Meter Replacement Installation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AvoExtractCSVControllerMeterEntryTest.cls
@isTest
public class AvoExtractCSVControllerMeterEntryTest {
    
    @isTest
    static void testExtractCSVSuccess() {
        AVO_Meter_Transaction__c batchMeterEntry = new AVO_Meter_Transaction__c(
            Name = 'MBTE-0000-0000',
            AVO_Batch_Type__c = 'Batch Meter Entry',
            RecordTypeId = Schema.SObjectType.AVO_Meter_Transaction__c.getRecordTypeInfosByName().get('Batch Meter Entry').getRecordTypeId(),
            AVO_Batch_Status__c = 'Pending'
        );
        insert batchMeterEntry;
        AVO_Meter_Codeset__c make = new AVO_Meter_Codeset__c(
        	Name = 'McCrometer',
            AVO_Status__c = 'A',
            AVO_Make_ID__c = '1',
            AVO_Type__c = 'Meter Make',
            RecordTypeId = Schema.SObjectType.AVO_Meter_Codeset__c.getRecordTypeInfosByName().get('Meter Make').getRecordTypeId()
        );
        insert make;
        AVO_Meter_Codeset__c model = new AVO_Meter_Codeset__c(
        	Name = 'G304-1',
            AVO_Meter_Make__c = make.Id,
            AVO_Status__c = 'A',
            AVO_Model_ID__c = '1',
            AVO_Type__c = 'Meter Model',
            RecordTypeId = Schema.SObjectType.AVO_Meter_Codeset__c.getRecordTypeInfosByName().get('Meter Model').getRecordTypeId()
        );
        insert model;
        
        // Prepare CSV content string
        String csvContent =
            'Serial No.,Make,Model,Unit of Measure,Inside Diameter,Outside Diameter,Multiplier,Meter Storage Location,State Purchased,Battery Based,Date Purchased,Order ID,RegisterOrientation\n' +
             'AG22-0359,McCrometer,G304-1,Acre/Inches,4.03,4.05,0.01,Warehouse Left-wall,Yes,Yes,,362962,Horizontal\n';

        ContentVersion cv = new ContentVersion(
            Title = 'TestCSV',
            PathOnClient = 'TestCSV.csv',
            VersionData = Blob.valueOf(csvContent)
        );
        insert cv;
        
        ContentDocumentLink cdl = new ContentDocumentLink(
            ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id].ContentDocumentId,
            LinkedEntityId = batchMeterEntry.Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        );
        insert cdl;
        
        Test.startTest();
        AvoExtractCSVControllerMeterEntry.extractCSV(batchMeterEntry.Id);
        Test.stopTest();
        
        System.assertEquals(true, true);
    }
    
    @isTest
    static void testExtractCSVFailNoMakeModel() {
        AVO_Meter_Transaction__c batchMeterEntry = new AVO_Meter_Transaction__c(
            Name = 'MBTE-0000-0000',
            AVO_Batch_Type__c = 'Batch Meter Entry',
            RecordTypeId = Schema.SObjectType.AVO_Meter_Transaction__c.getRecordTypeInfosByName().get('Batch Meter Entry').getRecordTypeId(),
            AVO_Batch_Status__c = 'Pending'
        );
        insert batchMeterEntry;

        // Prepare CSV content string
        String csvContent =
            'Serial No.,Make,Model,Unit of Measure,Inside Diameter,Outside Diameter,Multiplier,Meter Storage Location,State Purchased,Battery Based,Date Purchased,Order ID,RegisterOrientation\n' +
             'AG22-0359,McCrometer,G304-1,Acre/Inches,4.03,4.05,0.01,Warehouse Left-wall,Yes,Yes,,362962,Horizontal\n';

        ContentVersion cv = new ContentVersion(
            Title = 'TestCSV',
            PathOnClient = 'TestCSV.csv',
            VersionData = Blob.valueOf(csvContent)
        );
        insert cv;
        
        ContentDocumentLink cdl = new ContentDocumentLink(
            ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id].ContentDocumentId,
            LinkedEntityId = batchMeterEntry.Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        );
        insert cdl;
        
        Test.startTest();
        try {
            AvoExtractCSVControllerMeterEntry.extractCSV(batchMeterEntry.Id);
        } catch (AuraHandledException ex) {
            System.debug('test');
        }
        
        Test.stopTest();
        
        System.assertEquals(true, true);
    }
    
    @isTest
    static void testExtractCSVFailNoFile() {
        AVO_Meter_Transaction__c batchMeterEntry = new AVO_Meter_Transaction__c(
            Name = 'MBTE-0000-0000',
            AVO_Batch_Type__c = 'Batch Meter Entry',
            RecordTypeId = Schema.SObjectType.AVO_Meter_Transaction__c.getRecordTypeInfosByName().get('Batch Meter Entry').getRecordTypeId(),
            AVO_Batch_Status__c = 'Pending'
        );
        insert batchMeterEntry;

        Test.startTest();
        try {
            AvoExtractCSVControllerMeterEntry.extractCSV(batchMeterEntry.Id);
        } catch (AuraHandledException ex) {
            System.debug('test');
        }
        
        Test.stopTest();
        
        System.assertEquals(true, true);
    }
    
    @isTest
    static void testExtractCSVFailNoBatchEntryRecord() {
        AVO_Meter__c meter = new AVO_Meter__c(
            Name = '12345'
        );
        insert meter;

        Test.startTest();
        try {
            AvoExtractCSVControllerMeterEntry.extractCSV(meter.Id);
        } catch (AuraHandledException ex) {
            System.debug('test');
        }
        
        Test.stopTest();
        
        System.assertEquals(true, true);
    }
    
    @isTest
    static void testExtractCSVFailInvalidCSV() {
        AVO_Meter_Transaction__c batchMeterEntry = new AVO_Meter_Transaction__c(
            Name = 'MBTE-0000-0000',
            AVO_Batch_Type__c = 'Batch Meter Entry',
            RecordTypeId = Schema.SObjectType.AVO_Meter_Transaction__c.getRecordTypeInfosByName().get('Batch Meter Entry').getRecordTypeId(),
            AVO_Batch_Status__c = 'Pending'
        );
        insert batchMeterEntry;
        AVO_Meter_Codeset__c make = new AVO_Meter_Codeset__c(
        	Name = 'McCrometer',
            AVO_Status__c = 'A',
            AVO_Make_ID__c = '1',
            AVO_Type__c = 'Meter Make',
            RecordTypeId = Schema.SObjectType.AVO_Meter_Codeset__c.getRecordTypeInfosByName().get('Meter Make').getRecordTypeId()
        );
        insert make;
        AVO_Meter_Codeset__c model = new AVO_Meter_Codeset__c(
        	Name = 'G304-1',
            AVO_Meter_Make__c = make.Id,
            AVO_Status__c = 'A',
            AVO_Model_ID__c = '1',
            AVO_Type__c = 'Meter Model',
            RecordTypeId = Schema.SObjectType.AVO_Meter_Codeset__c.getRecordTypeInfosByName().get('Meter Model').getRecordTypeId()
        );
        insert model;
        
        // Prepare CSV content string
        String csvContent =
            'Serial No.,Make,Model,Unit of Measure,Inside Diameter,Outside Diameter,Multiplier,Meter Storage Location,State Purchased,Battery Based,Date Purchased,Order ID,RegisterOrientation\n' +
             ',,,test,,,,test,test,test,,,test\n';

        ContentVersion cv = new ContentVersion(
            Title = 'TestCSV',
            PathOnClient = 'TestCSV.csv',
            VersionData = Blob.valueOf(csvContent)
        );
        insert cv;
        
        ContentDocumentLink cdl = new ContentDocumentLink(
            ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id].ContentDocumentId,
            LinkedEntityId = batchMeterEntry.Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        );
        insert cdl;
        
        Test.startTest();
        try {
            AvoExtractCSVControllerMeterEntry.extractCSV(batchMeterEntry.Id);
        } catch (AuraHandledException ex) {
            System.debug('test');
        }
        Test.stopTest();
        
        System.assertEquals(true, true);
    }
    
    @isTest
    static void testExtractCSVFailDuplicateMeter() {
        AVO_Meter__c meter = new AVO_Meter__c(
            Name = 'AG22-0359'
        );
        insert meter;
        AVO_Meter_Transaction__c batchMeterEntry = new AVO_Meter_Transaction__c(
            Name = 'MBTE-0000-0000',
            AVO_Batch_Type__c = 'Batch Meter Entry',
            RecordTypeId = Schema.SObjectType.AVO_Meter_Transaction__c.getRecordTypeInfosByName().get('Batch Meter Entry').getRecordTypeId(),
            AVO_Batch_Status__c = 'Pending'
        );
        insert batchMeterEntry;
        AVO_Meter_Codeset__c make = new AVO_Meter_Codeset__c(
        	Name = 'McCrometer',
            AVO_Status__c = 'A',
            AVO_Make_ID__c = '1',
            AVO_Type__c = 'Meter Make',
            RecordTypeId = Schema.SObjectType.AVO_Meter_Codeset__c.getRecordTypeInfosByName().get('Meter Make').getRecordTypeId()
        );
        insert make;
        AVO_Meter_Codeset__c model = new AVO_Meter_Codeset__c(
        	Name = 'G304-1',
            AVO_Meter_Make__c = make.Id,
            AVO_Status__c = 'A',
            AVO_Model_ID__c = '1',
            AVO_Type__c = 'Meter Model',
            RecordTypeId = Schema.SObjectType.AVO_Meter_Codeset__c.getRecordTypeInfosByName().get('Meter Model').getRecordTypeId()
        );
        insert model;
        
        // Prepare CSV content string
        String csvContent =
            'Serial No.,Make,Model,Unit of Measure,Inside Diameter,Outside Diameter,Multiplier,Meter Storage Location,State Purchased,Battery Based,Date Purchased,Order ID,RegisterOrientation\n' +
             'AG22-0359,McCrometer,G304-1,Acre/Inches,4.03,4.05,0.01,Warehouse Left-wall,Yes,Yes,,362962,Horizontal\n';


        ContentVersion cv = new ContentVersion(
            Title = 'TestCSV',
            PathOnClient = 'TestCSV.csv',
            VersionData = Blob.valueOf(csvContent)
        );
        insert cv;
        
        ContentDocumentLink cdl = new ContentDocumentLink(
            ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id].ContentDocumentId,
            LinkedEntityId = batchMeterEntry.Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        );
        insert cdl;
        
        Test.startTest();
        try {
            AvoExtractCSVControllerMeterEntry.extractCSV(batchMeterEntry.Id);
        } catch (AuraHandledException ex) {
            System.debug('test');
        }
        Test.stopTest();
        
        System.assertEquals(true, true);
    }
    
    @isTest
    static void testExtractCSVFailMakeModelMismatch() {
        AVO_Meter_Transaction__c batchMeterEntry = new AVO_Meter_Transaction__c(
            Name = 'MBTE-0000-0000',
            AVO_Batch_Type__c = 'Batch Meter Entry',
            RecordTypeId = Schema.SObjectType.AVO_Meter_Transaction__c.getRecordTypeInfosByName().get('Batch Meter Entry').getRecordTypeId(),
            AVO_Batch_Status__c = 'Pending'
        );
        insert batchMeterEntry;
        AVO_Meter_Codeset__c make = new AVO_Meter_Codeset__c(
        	Name = 'McCrometer',
            AVO_Status__c = 'A',
            AVO_Make_ID__c = '1',
            AVO_Type__c = 'Meter Make',
            RecordTypeId = Schema.SObjectType.AVO_Meter_Codeset__c.getRecordTypeInfosByName().get('Meter Make').getRecordTypeId()
        );
        insert make;
        AVO_Meter_Codeset__c model = new AVO_Meter_Codeset__c(
        	Name = 'G304-1',
            AVO_Meter_Make__c = make.Id,
            AVO_Status__c = 'A',
            AVO_Model_ID__c = '1',
            AVO_Type__c = 'Meter Model',
            RecordTypeId = Schema.SObjectType.AVO_Meter_Codeset__c.getRecordTypeInfosByName().get('Meter Model').getRecordTypeId()
        );
        insert model;
        AVO_Meter_Codeset__c make2 = new AVO_Meter_Codeset__c(
        	Name = 'Seametrics',
            AVO_Status__c = 'A',
            AVO_Make_ID__c = '2',
            AVO_Type__c = 'Meter Make',
            RecordTypeId = Schema.SObjectType.AVO_Meter_Codeset__c.getRecordTypeInfosByName().get('Meter Make').getRecordTypeId()
        );
        insert make2;
        AVO_Meter_Codeset__c model2 = new AVO_Meter_Codeset__c(
        	Name = 'G304-2',
            AVO_Meter_Make__c = make2.Id,
            AVO_Status__c = 'A',
            AVO_Model_ID__c = '2',
            AVO_Type__c = 'Meter Model',
            RecordTypeId = Schema.SObjectType.AVO_Meter_Codeset__c.getRecordTypeInfosByName().get('Meter Model').getRecordTypeId()
        );
        insert model2;
        
        // Prepare CSV content string
        String csvContent =
            'Serial No.,Make,Model,Unit of Measure,Inside Diameter,Outside Diameter,Multiplier,Meter Storage Location,State Purchased,Battery Based,Date Purchased,Order ID,RegisterOrientation\n' +
             'AG22-0359,McCrometer,G304-2,Acre/Inches,4.03,4.05,0.01,Warehouse Left-wall,Yes,Yes,,362962,Horizontal\n';

        ContentVersion cv = new ContentVersion(
            Title = 'TestCSV',
            PathOnClient = 'TestCSV.csv',
            VersionData = Blob.valueOf(csvContent)
        );
        insert cv;
        
        ContentDocumentLink cdl = new ContentDocumentLink(
            ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id].ContentDocumentId,
            LinkedEntityId = batchMeterEntry.Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        );
        insert cdl;
        
        Test.startTest();
        try {
            AvoExtractCSVControllerMeterEntry.extractCSV(batchMeterEntry.Id);
        } catch (AuraHandledException ex) {
            System.debug('test');
        }
        Test.stopTest();
        
        System.assertEquals(true, true);
    }
    
}