force-app/main/default/objects/AVO_Meter__c/AVO_Meter__c.object-meta.xml
<CustomObject>
    <label>Meter</label>
    <nameField>
        <label>Meter Serial Number (MSN)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Meter__c/fields/AVO_Type__c.field-meta.xml
<CustomField>
    <fullName>AVO_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Meter</fullName>
            </value>
            <value>
                <fullName>AG Water Metering Installation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Meter__c/recordTypes/Meter.recordType-meta.xml
<RecordType>
    <fullName>Meter</fullName>
    <active>true</active>
    <label>Meter</label>
</RecordType>

force-app/main/default/objects/AVO_Meter_Transaction__c/AVO_Meter_Transaction__c.object-meta.xml
<CustomObject>
    <label>Meter Transaction</label>
    <nameField>
        <label>Meter Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meter Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Meter_Transaction__c/fields/AVO_Batch_ID__c.field-meta.xml
<CustomField>
    <fullName>AVO_Batch_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch ID</label>
    <referenceTo>AVO_Meter_Transaction__c</referenceTo>
    <relationshipLabel>Meter Transactions (Batch ID)</relationshipLabel>
    <relationshipName>Meter_Transactions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AVO_Meter_Transaction__c/fields/AVO_Batch_Status__c.field-meta.xml
<CustomField>
    <fullName>AVO_Batch_Status__c</fullName>
    <label>Batch Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Review Required</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AVO_Meter_Transaction__c/fields/AVO_CSV_Read__c.field-meta.xml
<CustomField>
    <fullName>AVO_CSV_Read__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CSV Read</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AVO_Meter_Transaction__c/fields/AVO_Date_Uploaded__c.field-meta.xml
<CustomField>
    <fullName>AVO_Date_Uploaded__c</fullName>
    <label>Date Uploaded</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AVO_Meter_Transaction__c/fields/AVO_Meter_ID__c.field-meta.xml
<CustomField>
    <fullName>AVO_Meter_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meter (MSN)</label>
    <referenceTo>AVO_Meter__c</referenceTo>
    <relationshipLabel>Meter Transactions</relationshipLabel>
    <relationshipName>Meter_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AVO_Meter_Transaction__c/fields/AVO_Meter_Serial_Number_MSN__c.field-meta.xml
<CustomField>
    <fullName>AVO_Meter_Serial_Number_MSN__c</fullName>
    <label>Meter Serial Number (MSN)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AVO_Meter_Transaction__c/fields/AVO_Reading__c.field-meta.xml
<CustomField>
    <fullName>AVO_Reading__c</fullName>
    <label>Meter Reading</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AVO_Meter_Transaction__c/fields/AVO_Reading_Date__c.field-meta.xml
<CustomField>
    <fullName>AVO_Reading_Date__c</fullName>
    <label>Meter Reading Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AVO_Meter_Transaction__c/fields/AVO_Type__c.field-meta.xml
<CustomField>
    <fullName>AVO_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agricultural Flow Meter Approval</fullName>
            </value>
            <value>
                <fullName>AG Water Metering Installation</fullName>
            </value>
            <value>
                <fullName>Batch Meter Entry</fullName>
            </value>
            <value>
                <fullName>Meter Allocation</fullName>
            </value>
            <value>
                <fullName>Meter Application</fullName>
            </value>
            <value>
                <fullName>Batch Meter Reading</fullName>
            </value>
            <value>
                <fullName>Meter Maintenance Request</fullName>
            </value>
            <value>
                <fullName>Meter Reading</fullName>
            </value>
            <value>
                <fullName>Meter Update</fullName>
            </value>
            <value>
                <fullName>Meter Entry</fullName>
            </value>
            <value>
                <fullName>Meter Replacement Installation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AvoExtractCSVControllerMeterReading.cls
// This is the one being used
public with sharing class AvoExtractCSVControllerMeterReading {
    @AuraEnabled
    public static void extractCSV(Id recordId) {
        System.debug('RecordId IS: ' + recordId);
        AVO_Meter_Transaction__c batchMeterReading;

        try {
            batchMeterReading = [
                SELECT Id,
                    (SELECT Id, FileExtension FROM CombinedAttachments WHERE FileExtension = 'csv')
                FROM AVO_Meter_Transaction__c
                WHERE Id = :recordId
                LIMIT 1
            ];
        } catch (Exception e) {
            System.debug('Error occurred while querying Batch Meter Reading: ' + e.getMessage());
            return;
        }

        if (batchMeterReading != null) {
            List<CombinedAttachment> combinedAttachments = batchMeterReading.CombinedAttachments;
            if (combinedAttachments.size() == 0) {
                throw new AuraHandledException('No uploaded CSV files found. Please upload a CSV file.');
            }
            for (CombinedAttachment combinedAttachment : combinedAttachments) {
                System.debug('show' + combinedAttachment);

                if (combinedAttachment.FileExtension == 'csv') {
                    ContentVersion contentVersion = [
                        SELECT VersionData
                        FROM ContentVersion
                        WHERE ContentDocumentId = :combinedAttachment.Id
                    ];
                          system.debug('notes id ' + combinedAttachment.Id);
                    if (contentVersion != null) {
                        
                        Set<String> existingMSNSet = new Set<String>();
            
                        for (AVO_Meter__c existingMeter : [SELECT Id, Name FROM AVO_Meter__c]) {
                            existingMSNSet.add(existingMeter.Name);
                        }
                        
                        // Parse the CSV data
                        String csvData = contentVersion.VersionData.toString();
                        List<String> rows = csvData.split('\n');
						Id meterReadingRecordTypeId = Schema.SObjectType.AVO_Meter_Transaction__c.getRecordTypeInfosByName().get('Meter Reading').getRecordTypeId();
                        
                        // Extract field names from the first row
                        List<String> fieldNames = rows[0].split(',');

                        Set<String> msnSet = new Set<String>();
                        // Check CSV data
                        Boolean isMissingFields = false;
                        String errorMessage = '';
                        for (Integer i = 1; i < rows.size(); i++) {
                            List<String> rowData = rows[i].split(',');
                            if (String.isBlank(rowData[0])) {
                                errorMessage = errorMessage + 'Row ' + i + ': Meter Serial Number Missing\n';
                                isMissingFields = true;
                            } else { 
                                msnSet.add(rowData[0]);
                                if (!existingMSNSet.contains(rowData[0].trim())) {
                                    errorMessage = errorMessage + 'Row ' + i + ': Meter Serial Number ' + rowData[0] + ' is not in the system\n';
                                    isMissingFields = true;
                                }
                            }
                        }

                        if (isMissingFields) {
                            errorMessage = 'Required data fields are missing for the following rows\n' + errorMessage;
                            throw new AuraHandledException(errorMessage);
                        }
                        
                        List<AVO_Meter__c> existingMeters = [SELECT Id, Name FROM AVO_Meter__c WHERE Name IN :msnSet];
                        Map<String, AVO_Meter__c> msnMeterMap = new Map<String, AVO_Meter__c>();
                        for (AVO_Meter__c existingMeter : existingMeters) {
                            if (!msnMeterMap.containsKey(existingMeter.Name)) {
                                msnMeterMap.put(existingMeter.Name, existingMeter);
                            }
                        }
                        
                        // Process the CSV data and create new meterReadingRecords
                        List<AVO_Meter_Transaction__c> meterReadings = new List<AVO_Meter_Transaction__c>();

                        for (Integer i = 1; i < rows.size(); i++) {
                            List<String> rowData = rows[i].split(',');
							AVO_Meter_Transaction__c meterReading = new AVO_Meter_Transaction__c();
                            
                            meterReading.RecordTypeId = meterReadingRecordTypeId;
                            meterReading.AVO_Type__c = 'Meter Reading'; 
                            meterReading.AVO_Batch_ID__c = batchMeterReading.Id;
                            meterReading.AVO_Meter_ID__c = msnMeterMap.get(rowData[0]).Id;
                            meterReading.AVO_Reading__c = String.isNotBlank(rowData[19]) ? Decimal.valueOf(rowData[19]) : null;
                            meterReading.AVO_Reading_Date__c = Date.today();
                            meterReading.AVO_Meter_Serial_Number_MSN__c = msnMeterMap.get(rowData[0]).Name;
                            
                            meterReadings.add(meterReading);
                                                              
                        }
                        // Update the meterReadingRecordList
                        if (!meterReadings.isEmpty()) {
                            System.debug('inserting meter readings...');
                            insert meterReadings;
                        }
                        batchMeterReading.AVO_CSV_Read__c = true;
                        batchMeterReading.AVO_Date_Uploaded__c = System.today();
                        batchMeterReading.AVO_Batch_Status__c = 'Pending Approval';
                        update batchMeterReading;
                    }
                }
                else {
                    throw new AuraHandledException('The uploaded file is not a CSV file.');
                }
            }
        }
    }
}