force-app/main/default/objects/AVO_Exception_Logger__c/AVO_Exception_Logger__c.object-meta.xml
<CustomObject>
    <label>Avo Exception Logger</label>
    <nameField>
        <displayFormat>EXP-{000000}</displayFormat>
        <label>Avo Exception Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Avo Exception Logger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AVO_Exception_Logger__c/fields/Exception_Cause__c.field-meta.xml
<CustomField>
    <fullName>Exception_Cause__c</fullName>
    <label>Exception Cause</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/AVO_Exception_Logger__c/fields/Exception_Cause_Override__c.field-meta.xml
<CustomField>
    <fullName>Exception_Cause_Override__c</fullName>
    <label>Exception Cause Override</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AVO_Exception_Logger__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <label>Line_Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AVO_Exception_Logger__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/AvoLogException.cls
/**
* Description of class
* a class extended from AvoCustomException
* @author Jason Li
* last modified by Jason Li
* @date 03/23/2021
*
*/
public class AvoLogException extends Exception {
    public String ModuleName {get; set;}
    public String StackTrace {get; set;}
    public String ClassName {get; set;}
    public String MethodName {get; set;}
    public String ExceptionCause {get; set;}
        
    public void log(Exception ex)
    {
    	try
        {
        	extractExceptionData(ex); 
            writeToObject(ex); 
        }
        catch(Exception e)
        {
         	new AvoLogException().Module('LogException').log(e);            
        }        	        
    }
    
    public AvoLogException Module(String Name)
    {
    	ModuleName = name;
        return this;
    }
    
    public AvoLogException ExceptionCause(String cause)
    {
    	ExceptionCause = cause;
        return this;
    }
    
    public void extractExceptionData(Exception ex)
    {
        try
        {
            stackTrace = ex.getStackTraceString().substringBefore('\n');
            className = stackTrace.substringAfter('.').substringBefore('.');	
            methodName = stackTrace.substringBefore(':').substringAfter(className).substringAfter('.');    
        }
        catch(Exception e)
        {
        	new AvoLogException().Module('LogException').log(e); 
        }      	                        
    }
    
    public void writeToObject(Exception ex)
    {
    	try
        {
            AVO_Exception_Logger__c logger = new AVO_Exception_Logger__c();
            logger.Module_Name__c = ModuleName;
            logger.Stack_Trace__c = ex.getStackTraceString();
            logger.Class_Name__c = className;
            logger.Method_Name__c = methodName;
            logger.Line_Number__c = ex.getLineNumber();
            logger.Exception_Type__c = ex.getTypeName();
            logger.Exception_Cause_Override__c = ExceptionCause; 
            logger.Exception_Cause__c = String.valueOf(ex.getCause());
            
            logger.Exception_Message__c = ex.getMessage();
            
            insert logger;    
        }
        
        catch(Exception e)
        {
        	new AvoLogException().Module('LogException').log(e);     
        }   
    }    
}