force-app/main/default/objects/Avocette_Settings__mdt/Avocette_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Avocette Settings</label>
    <pluralLabel>Avocette Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Avocette_Settings__mdt/fields/Boolean_Value__c.field-meta.xml
<CustomField>
    <fullName>Boolean_Value__c</fullName>
    <defaultValue>false</defaultValue>
    <description>a setting may have a boolean value, a string value, or a numeric value</description>
    <label>Boolean Value</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MUSW__Address__c/MUSW__Address__c.object-meta.xml
<CustomObject>
    <description>Address represents a location on a parcel.</description>
    <label>Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Address__c/fields/MUSW__Parcel__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Parcel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the parcel record to which this address belongs to.</description>
    <inlineHelpText>Provide the Parcel that is associated to this address.</inlineHelpText>
    <label>Parcel</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MUSW__Parcel__c.MUSW__Historic__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>MUSW__Parcel__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Inspection__c/MUSW__Inspection__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Ensure work is done in compliance with rules and regulations</description>
    <label>Inspection</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Inspection__c/fields/MUSW__Address__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>MUSW__Address__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Inspection__c/fields/MUSW__Parcel__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Parcel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated Parcel (Address).</description>
    <label>Parcel</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MUSW__Parcel__c.MUSW__Historic__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>MUSW__Parcel__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Inspection__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <description>Scope of the inspection activity to be done.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Building</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>Initial Inspection</fullName>
            </value>
            <value>
                <fullName>AG Permitting Site Verification Form</fullName>
            </value>
            <value>
                <fullName>Code Enforcement Inspection</fullName>
            </value>
            <value>
                <fullName>Codes / Zoning</fullName>
            </value>
            <value>
                <fullName>Farmer Initiated Online Request</fullName>
            </value>
            <value>
                <fullName>Permit Inspection</fullName>
            </value>
            <value>
                <fullName>Site Visit Request</fullName>
            </value>
            <value>
                <fullName>WWSA Inspection</fullName>
            </value>
            <value>
                <fullName>Site Visit Report</fullName>
            </value>
            <value>
                <fullName>Groundwater Withdrawal Information</fullName>
            </value>
            <value>
                <fullName>Surface Water Withdrawal Information</fullName>
            </value>
            <value>
                <fullName>Meter &amp; Telemetry Information</fullName>
            </value>
            <value>
                <fullName>Well Construction Inspection</fullName>
            </value>
            <value>
                <fullName>Well Plug and Abandon Inspection</fullName>
            </value>
            <value>
                <fullName>Ag Site Inspection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Inspection_List__c/MUSW__Master_Inspection_List__c.object-meta.xml
<CustomObject>
    <label>Inspection Template</label>
    <nameField>
        <label>Inspection Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inspection Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Master_Inspection_List__c/fields/Avo_Active__c.field-meta.xml
<CustomField>
    <fullName>Avo_Active__c</fullName>
    <formula>IF( AND(Effective_Start_Date__c&lt;TODAY(),
       (OR(ISBLANK(Effective_End_Date__c),
	       Effective_End_Date__c&gt; TODAY())
		) 
		),True,False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MUSW__Master_Inspection_List__c/fields/Avo_Complaint_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Complaint_Type__c</fullName>
    <label>Complaint Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Service Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Inspection_List__c/fields/Avo_Manual_Creation_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Avo_Manual_Creation_Allowed__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Manual Creation Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MUSW__Master_Inspection_List__c/fields/Avo_Permit_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Permit_Type__c</fullName>
    <label>Permit Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Permit_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Inspection_List__c/fields/Avo_Planning_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Planning_Application_Type__c</fullName>
    <label>Planning Application Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Planning_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Inspection_List__c/fields/Avo_Violation_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Violation_Type__c</fullName>
    <label>Violation Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Violation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/MUSW__Permit2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Permit application details</description>
    <label>Permit</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_Permit_Type__c.field-meta.xml
<CustomField>
    <fullName>AVO_Permit_Type__c</fullName>
    <label>Permit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AVO_Withdrawal_Permit_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Address__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to address to which the permit is associated to.</description>
    <inlineHelpText>Provide the address that this permit belongs to.</inlineHelpText>
    <label>Address</label>
    <referenceTo>MUSW__Address__c</referenceTo>
    <relationshipLabel>Permits</relationshipLabel>
    <relationshipName>Permits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Parcel__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Parcel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated parcel or address of the permit.</description>
    <label>Parcel</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MUSW__Parcel__c.MUSW__Historic__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>MUSW__Parcel__c</referenceTo>
    <relationshipLabel>Permits</relationshipLabel>
    <relationshipName>Permit2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <description>The permit type. This is typically related to the record type.</description>
    <label>Type (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agricultural Surface Water Pump</fullName>
            </value>
            <value>
                <fullName>Agricultural Water Withdrawal Application</fullName>
            </value>
            <value>
                <fullName>Agricultural Water Withdrawal Permit</fullName>
            </value>
            <value>
                <fullName>Agricultural Well Pump</fullName>
            </value>
            <value>
                <fullName>Application for Permit Consolidation</fullName>
            </value>
            <value>
                <fullName>Revision</fullName>
            </value>
            <value>
                <fullName>Permit Relinquishment</fullName>
            </value>
            <value>
                <fullName>Well and Pump Data</fullName>
            </value>
            <value>
                <fullName>Well Plug and Abandonment</fullName>
            </value>
            <value>
                <fullName>AG Water Metering Installation</fullName>
            </value>
            <value>
                <fullName>Undocumented Source</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit__c/MUSW__Permit__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Deprecated. Permit application details including process dates and status</description>
    <label>Permit (Deprecated)</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permits (Deprecated)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Permit__c/fields/MUSW__Parcel__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Parcel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parcel</label>
    <referenceTo>MUSW__Parcel__c</referenceTo>
    <relationshipName>Permits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Violation__c/MUSW__Violation__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Violation cited on Complaints</description>
    <label>Violation</label>
    <nameField>
        <displayFormat>VI-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Violations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Violation__c/fields/MUSW__Parcel__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Parcel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the associated parcel record.</description>
    <label>Parcel</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MUSW__Parcel__c.MUSW__Historic__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>MUSW__Parcel__c</referenceTo>
    <relationshipLabel>Violations</relationshipLabel>
    <relationshipName>Violations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Violation__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary descriptor of the violation. Unlike most type fields in the system, this is a lookup to the ordinance table rather than a picklist.</description>
    <label>Ordinance Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MUSW__Violation_Type__c.MUSW__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>MUSW__Violation_Type__c</referenceTo>
    <relationshipLabel>Violations</relationshipLabel>
    <relationshipName>Violations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Avo_Permit_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agricultural Water Withdrawal Application</fullName>
    </customValue>
    <customValue>
        <fullName>Agricultural Water Withdrawal Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Application for Permit Consolidation</fullName>
    </customValue>
    <customValue>
        <fullName>Revision</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation Request</fullName>
    </customValue>
    <customValue>
        <fullName>Permit Relinquishment</fullName>
    </customValue>
    <customValue>
        <fullName>Well and Pump Data</fullName>
    </customValue>
    <customValue>
        <fullName>Well Plug &amp; Abandonment</fullName>
    </customValue>
    <customValue>
        <fullName>AG Water Metering Installation</fullName>
    </customValue>
    <masterLabel>Avo Permit Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Avo_Planning_Application_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Variance</fullName>
    </customValue>
    <customValue>
        <fullName>Development Permit</fullName>
    </customValue>
    <masterLabel>Avo Planning Application Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/AVO_Withdrawal_Permit_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Groundwater</fullName>
    </customValue>
    <customValue>
        <fullName>Surface Water</fullName>
    </customValue>
    <customValue>
        <fullName>Well to Pond</fullName>
    </customValue>
    <customValue>
        <fullName>Undocumented Source</fullName>
        <isActive>false</isActive>
        <label>Undocumented Source</label>
    </customValue>
    <masterLabel>AVO Withdrawal Permit Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AvoInspectionDataRetrieverController.cls
/// pre-requisites
/// MUSW__Master_Inspection_List__c should have the following fields:
/// Avo_Permit_Type__c
/// Avo_Active__c
/// Avo_Manual_Creation_Allowed__c

/// Avo_Planning_Application_Type__c
/// Avo_Complaint_Type__c
/// version 1.0
public class AvoInspectionDataRetrieverController {
    // Method that returns the supported inspection types for a specific Record ID.
    // The return value should be in a CSV format for multiple inspection types

    static boolean InspectionAllowedForPermit  = false;
    static boolean InspectionAllowedForApplication = false;
    static boolean InspectionAllowedForComplaint = false;
    static boolean InspectionAllowedForViolation = false;

    private static void getSettingsFromMetedata()
    {
        List<Avocette_Settings__mdt> avocetteSettings = Avocette_Settings__mdt.getAll().values();

        For(Avocette_Settings__mdt mdt:avocetteSettings)
        {
            if (mdt.label == 'InspectionForPermit' && mdt.Boolean_Value__c == true)
                InspectionAllowedForPermit = true;
            if (mdt.label == 'InspectionForApplication' && mdt.Boolean_Value__c == true)
                InspectionAllowedForApplication = true;
            if (mdt.label == 'InspectionForComplaint' && mdt.Boolean_Value__c == true)
                InspectionAllowedForComplaint = true;
            if (mdt.label == 'InspectionForViolation' && mdt.Boolean_Value__c == true)
                InspectionAllowedForViolation = true;
    }

    }

    @AuraEnabled
    public static String getAllowedInspectionTypes(Id recordId, String sObjectName) {   
        getSettingsFromMetedata();
        
        String response = '';
        ResponseJSONWrapper wrapper = new ResponseJSONWrapper();
        List<MUSW__Master_Inspection_List__c> inspectionTypes;

        // step 1 - get a list of allowed inspection types
        if(sObjectName == 'MUSW__Permit2__c') {
            if (InspectionAllowedForPermit == true) {
                // get the Permit Type and Id
                MUSW__Permit2__c permit = [
                    SELECT Id, MUSW__Type__c
                    FROM MUSW__Permit2__c
                    WHERE Id = :recordId
                ];
                String permitType = permit.MUSW__Type__c;
                // Get the Master Inspection List items that include the Permit Type
                inspectionTypes = [
                    SELECT Name, Id 
                    FROM MUSW__Master_Inspection_List__c 
                    WHERE Avo_Permit_Type__c includes (:permitType)
                        AND Avo_Active__c = true 
                        AND Avo_Manual_Creation_Allowed__c = true 
                    ORDER BY Name ASC 
                ];
            } else {
                string error = 'Inspection creation for Permit is not allowed. Check metadata setup "Avocette Settings"';
                System.debug(error);
                throw new AuraHandledException(error);
            }
        } else if (sObjectName == 'MUSW__Violation__c' ) {
            if (InspectionAllowedForViolation == true) {
                // Get the Master Inspection List items that include the Application Type
                inspectionTypes = [
                    SELECT Name, Id 
                    FROM MUSW__Master_Inspection_List__c 
                    WHERE  Avo_Active__c = true
                    AND Avo_Manual_Creation_Allowed__c = true
                    AND Avo_Violation_Type__c != null
                    ORDER BY Name ASC 
                ];
            }
            else {
                string error = 'Inspection creation for Viloation is not allowed. Check metadata setup "Avocette Settings"';
                System.debug(error);
                throw new AuraHandledException(error);
            }
        }

        wrapper.id = recordId;
        wrapper.inspectionTypeList = new List<Option>();

        for(MUSW__Master_Inspection_List__c inspectionType:inspectionTypes)
        {
            Option option = new Option();

            option.label = inspectionType.Name;
            option.value = inspectionType.Id;
            
            // Adding Option objects (label & value) into the inspectionTypeList
            wrapper.inspectionTypeList.Add(option);
        }
        system.debug('get'+JSON.serialize(wrapper));
        response = JSON.serialize(wrapper);

        return response;
    }   

    @AuraEnabled
    // Helper function used to determine the record type of the inspection being created. The return record type will determine a different layout and dropdown listbox values for the inspection to be created
    public static Id getInspectionRecordTypeId(String masterInspectionListId) {
    
        try {
            List<MUSW__Master_Inspection_List__c> results = [
                SELECT Record_Type__c 
                FROM MUSW__Master_Inspection_List__c 
                WHERE Id = :masterInspectionListId 	 
                LIMIT 1] ; 
            
            If (results.size() == 1) {
                Id recordTypeId = Schema.SObjectType.MUSW__Inspection__c.getRecordTypeInfosByName().get(results[0].Record_Type__c).getRecordTypeId();
                return recordTypeId;    
            } else {
                return Schema.SObjectType.MUSW__Inspection__c.getRecordTypeInfosByName().get('eb Inspection Default').getRecordTypeId();
            } 
        } catch (Exception ex) {
            System.Debug('Failed to retrieve fee record type: ' + masterInspectionListId);
            return Schema.SObjectType.MUSW__Inspection__c.getRecordTypeInfosByName().get('eb Inspection Default').getRecordTypeId();
        }
    }

    @AuraEnabled
    // Helper function used to get the Master Inspection List item's name based off of the Master Inspection List ID
    public static String getInspectionName(String masterInspectionListId) {
        List<MUSW__Master_Inspection_List__c> recordTypeId = [
            SELECT Name
            FROM MUSW__Master_Inspection_List__c
            WHERE Id = :masterInspectionListId
        ];
        return recordTypeId[0].Name;
    }

    @AuraEnabled
    // Helper function used to get the Master Fee List item's Amount Value and convert it to an Integer
    public static List<MUSW__Master_Inspection_List__c> getInspectionInformation(List<String> masterListIds) {
        List<MUSW__Master_Inspection_List__c> results = [
            SELECT Name, Id
            FROM MUSW__Master_Inspection_List__c
            WHERE Id = :masterListIds
        ];
        return results;
    }

    @AuraEnabled
    // Helper function used to determine the record type of the inspection being created. The return record type will determine a different layout and dropdown listbox values for the inspection to be created
    public static Map<Id, Id> getInspectionRecordTypeIds(List<String> masterListIds) {
        Id defaultRecordTypeId = [
            SELECT Id
            FROM   RecordType
            WHERE  SObjectType = 'MUSW__Inspection__c'
            AND    Name = 'Site Visit Request'
            LIMIT  1
        ].Id;
        Map<Id, Id> results = new Map<Id, Id>();
      
        List<MUSW__Master_Inspection_List__c> inspections = [
            SELECT Record_Type__c 
            FROM MUSW__Master_Inspection_List__c 
            WHERE Id = :masterListIds ] ; 
        If (inspections.size() > 0) {
            for(MUSW__Master_Inspection_List__c item: inspections) {
                try {
                    Id recordTypeId = Schema.SObjectType.MUSW__Inspection__c.getRecordTypeInfosByName().get(item.Record_Type__c).getRecordTypeId();
                    results.put(item.id, recordTypeId);
                } catch (Exception ex) {
                    System.Debug('Failed to retrieve fee record type: ' + item.id);
                    results.put(item.id, defaultRecordTypeId);
                }
            }
        } 
        return results;        
    }
    
    @AuraEnabled
    // Method used to create 1 or more Inspections
    public static Id createInspections(String recordId, List<String> masterInspectionListIds, String sObjectName) {
        List<MUSW__Inspection__c> inspections = new List<MUSW__Inspection__c>();
        Id convertedId = Id.valueOf(recordId);

        List<MUSW__Master_Inspection_List__c> selectedInspections = getInspectionInformation(masterInspectionListIds);
        Map<Id, Id> recordTypeIds = getInspectionRecordTypeIds(masterInspectionListIds);

        
        for(MUSW__Master_Inspection_List__c item : selectedInspections) {

            Id recordTypeId = recordTypeIds.get(item.id);
            MUSW__Inspection__c inspection = new MUSW__Inspection__c(
                RecordTypeId       = recordTypeId,
                MUSW__Type__c      = item.Name
            );

            if(sObjectName == 'MUSW__Permit2__c') {
                MUSW__Permit2__c permit = [
                    SELECT MUSW__Type__c , MUSW__Parcel__c, MUSW__Address__c
                    FROM MUSW__Permit2__c 
                    WHERE Id = :recordId
                ];
                inspection.MUSW__Permit__c = convertedId;
                inspection.MUSW__Parcel__c = permit.MUSW__Parcel__c;
                inspection.MUSW__Address__c = permit.MUSW__Address__c;                
            }

            if(sObjectName == 'MUSW__Violation__c') {
                inspection.Avo_Violation__c  = convertedId;
            }
            inspections.add(inspection);
        }

        insert inspections;
        // Return the first ID in the inspections. This works if 1 or more inspections are added.
        return inspections[0].id;
    }
    
    // Response JSON Wrapper Class
    public class ResponseJSONWrapper {
        public Id id;
        public List<Option> inspectionTypeList;
    }

    // Object used to hold label and Id value for the inspections.
    public class Option {
        public String label;
        public String value;
    }
}