force-app/main/default/objects/clariti__Cart__c/clariti__Cart__c.object-meta.xml
<CustomObject>
    <description>Cart is used to process the transaction for a collection of cart items</description>
    <label>Cart</label>
    <nameField>
        <displayFormat>C-{MM}{DD}{YYYY}-{000}</displayFormat>
        <label>Cart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clariti__Cart__c/fields/clariti__Account__c.field-meta.xml
<CustomField>
    <fullName>clariti__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account is associated with the cart transaction.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Carts</relationshipLabel>
    <relationshipName>Carts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clariti__Cart__c/fields/clariti__Status__c.field-meta.xml
<CustomField>
    <fullName>clariti__Status__c</fullName>
    <description>Status of the cart.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/clariti__Payment__c/clariti__Payment__c.object-meta.xml
<CustomObject>
    <description>Payment is used to record the amount collected per payment method during the cart transaction</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{MM}{DD}{YYYY}-{000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clariti__Payment__c/fields/clariti__Account__c.field-meta.xml
<CustomField>
    <fullName>clariti__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Account that made the payment.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clariti__Payment__c/fields/clariti__Cart__c.field-meta.xml
<CustomField>
    <fullName>clariti__Cart__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to cart associated to the the payment transaction.</description>
    <label>Cart</label>
    <referenceTo>clariti__Cart__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clariti__Payment__c/fields/clariti__MerchantId__c.field-meta.xml
<CustomField>
    <fullName>clariti__MerchantId__c</fullName>
    <label>Merchant Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/clariti__Payment__c/fields/clariti__Payment__c.field-meta.xml
<CustomField>
    <fullName>clariti__Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>clariti__Payment__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clariti__Payment__c/fields/clariti__PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>clariti__PaymentMethod__c</fullName>
    <description>Payment Method used to make the payment.</description>
    <label>Payment Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clariti__Payment__c/fields/clariti__Status__c.field-meta.xml
<CustomField>
    <fullName>clariti__Status__c</fullName>
    <description>Status of the payment transaction.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Initiated</fullName>
            </value>
            <value>
                <fullName>Partially Refunded</fullName>
            </value>
            <value>
                <fullName>Fully Refunded</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CybersourcePaymentGatewayProcessor.cls
global with sharing class CybersourcePaymentGatewayProcessor extends clariti.PaymentProcessor {

    public static final String CART_IN_PROGRESS = 'In Progress';
    public static final String PAYMENT_INITIATED = 'Initiated';

    global override clariti.PaymentService.PaymentResult processInitiatedPayment(
        String cartId,
        List<clariti.PaymentService.PaymentMethod> paymentMethods,
        String paymentDetails
    ) {
        clariti.PaymentService.PaymentResult paymentResult = new clariti.PaymentService.PaymentResult();
        paymentResult.success = true;

        try {
            clariti__Cart__c cart = new clariti.CartSelector().getCartAndItemsById(cartId, new Set<String>());
            cart.clariti__Status__c = CART_IN_PROGRESS;

            clariti__Payment__c payment = new clariti__Payment__c(
                clariti__Cart__c = cart.Id,
                clariti__Account__c = cart.clariti__Account__c,
                clariti__Status__c = PAYMENT_INITIATED,
                clariti__PaymentMethod__c = paymentMethods[0].name,
                clariti__MerchantId__c = paymentDetails
            );
            insert payment;

            paymentResult.paymentName = payment.Name;
            paymentResult.paymentId = payment.Id;
            paymentResult.paymentMethod = paymentMethods[0].name;

        } catch (DmlException e) {
            System.debug(e.getStackTraceString());
            paymentResult.failureReason = e.getMessage();
            paymentResult.success = false;
        }

        return paymentResult;
    }    
}