force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/Avo_Gross_Sq_Ft_of_Building_Construction__c.field-meta.xml
<CustomField>
    <fullName>Avo_Gross_Sq_Ft_of_Building_Construction__c</fullName>
    <label>Gross Sq Ft of Building Construction</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Description__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Description__c</fullName>
    <description>Description of what the application is for.</description>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <label>Type (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Variance</fullName>
            </value>
            <value>
                <fullName>Development Permit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Fee__c/MUSW__Fee__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Fees/Fines associated to Permits, Complaints, Planning Applications</description>
    <label>Fee</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Fee__c/fields/Master_Fee_List__c.field-meta.xml
<CustomField>
    <fullName>Master_Fee_List__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Fee List</label>
    <referenceTo>MUSW__Master_Fee_List__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Fee__c/fields/MUSW__Application2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Application2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the associated application record.</description>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Fee__c/fields/MUSW__Description__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MUSW__Fee__c/fields/MUSW__Permit2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Permit2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the associated permit record.</description>
    <label>Permit</label>
    <referenceTo>MUSW__Permit2__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Fee__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <description>The type of fee. Each type may have a different accounting code.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Violations</fullName>
            </value>
            <value>
                <fullName>Upward Adjustments</fullName>
            </value>
            <value>
                <fullName>Downward Adjustments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Fee_List__c/MUSW__Master_Fee_List__c.object-meta.xml
<CustomObject>
    <label>Fee Template</label>
    <nameField>
        <label>Fee Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fee Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Master_Fee_List__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>IF( AND(Effective_Start_Date__c&lt;TODAY(),
       (OR(ISBLANK(Effective_End_Date__c),
	       Effective_End_Date__c&gt; TODAY())
		) 
		),True,False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MUSW__Master_Fee_List__c/fields/Avo_Planning_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Planning_Application_Type__c</fullName>
    <label>Planning Application Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Planning_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Fee_List__c/fields/Base__c.field-meta.xml
<CustomField>
    <fullName>Base__c</fullName>
    <label>Base</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MUSW__Master_Fee_List__c/fields/Fee_Calculation_Type__c.field-meta.xml
<CustomField>
    <fullName>Fee_Calculation_Type__c</fullName>
    <label>Fee Calculation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flat</fullName>
                <default>true</default>
                <label>Flat</label>
            </value>
            <value>
                <fullName>Tiered</fullName>
            </value>
            <value>
                <fullName>Fee Based</fullName>
            </value>
            <value>
                <fullName>Work Item Based</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Fee_List__c/fields/Flat_Amount__c.field-meta.xml
<CustomField>
    <fullName>Flat_Amount__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Flat Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MUSW__Master_Fee_List__c/fields/GL_Account__c.field-meta.xml
<CustomField>
    <fullName>GL_Account__c</fullName>
    <label>GL Account</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MUSW__Master_Fee_List__c/fields/High_Tier_Limit__c.field-meta.xml
<CustomField>
    <fullName>High_Tier_Limit__c</fullName>
    <label>High Tier Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MUSW__Master_Fee_List__c/fields/Low_Tier_Limit__c.field-meta.xml
<CustomField>
    <fullName>Low_Tier_Limit__c</fullName>
    <label>Low Tier Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MUSW__Master_Fee_List__c/fields/Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Multiplier__c</fullName>
    <label>Multiplier</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MUSW__Master_Fee_List__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <label>Fee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Fee_List__c/fields/Related_Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Related_Work_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Work Item</label>
    <referenceTo>MUSW__Master_Work_Item_List__c</referenceTo>
    <relationshipName>Master_Fee_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Master_Fee_List__c/recordTypes/Permit.recordType-meta.xml
<RecordType>
    <fullName>Permit</fullName>
    <active>true</active>
    <description>Permit Fees</description>
    <label>Permit</label>
</RecordType>

force-app/main/default/objects/MUSW__Master_Work_Item_List__c/MUSW__Master_Work_Item_List__c.object-meta.xml
<CustomObject>
    <label>Work Item Template</label>
    <nameField>
        <label>Work Item Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Item Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Master_Work_Item_List__c/fields/MUSW__Description__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Description__c</fullName>
    <description>User friendly name of Work Item</description>
    <label>Description</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/MUSW__Permit2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Permit application details</description>
    <label>Permit</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Permit2__c/fields/Avo_Estimated_Cost__c.field-meta.xml
<CustomField>
    <fullName>Avo_Estimated_Cost__c</fullName>
    <label>Estimated Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/Avo_Fee_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Avo_Fee_Calculation__c</fullName>
    <label>Fee Calculation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Estimated Value</fullName>
            </value>
            <value>
                <fullName>Valuation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_Permit_Type__c.field-meta.xml
<CustomField>
    <fullName>AVO_Permit_Type__c</fullName>
    <label>Permit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AVO_Withdrawal_Permit_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/Avo_Proposed_Occupancy__c.field-meta.xml
<CustomField>
    <fullName>Avo_Proposed_Occupancy__c</fullName>
    <label>Proposed Occupancy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Occupancy_Classification</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/Avo_Type_Construction__c.field-meta.xml
<CustomField>
    <fullName>Avo_Type_Construction__c</fullName>
    <label>Type Construction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Type_of_Construction</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/Avo_Value_of_Sign__c.field-meta.xml
<CustomField>
    <fullName>Avo_Value_of_Sign__c</fullName>
    <label>Value of Sign</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Description__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Description__c</fullName>
    <description>Description of the work to be permitted.</description>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <description>The permit type. This is typically related to the record type.</description>
    <label>Type (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agricultural Surface Water Pump</fullName>
            </value>
            <value>
                <fullName>Agricultural Water Withdrawal Application</fullName>
            </value>
            <value>
                <fullName>Agricultural Water Withdrawal Permit</fullName>
            </value>
            <value>
                <fullName>Agricultural Well Pump</fullName>
            </value>
            <value>
                <fullName>Application for Permit Consolidation</fullName>
            </value>
            <value>
                <fullName>Revision</fullName>
            </value>
            <value>
                <fullName>Permit Relinquishment</fullName>
            </value>
            <value>
                <fullName>Well and Pump Data</fullName>
            </value>
            <value>
                <fullName>Well Plug and Abandonment</fullName>
            </value>
            <value>
                <fullName>AG Water Metering Installation</fullName>
            </value>
            <value>
                <fullName>Undocumented Source</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/recordTypes/All.recordType-meta.xml
<RecordType>
    <fullName>All</fullName>
    <active>false</active>
    <label>All</label>
</RecordType>

force-app/main/default/objects/MUSW__Permit2__c/recordTypes/Building.recordType-meta.xml
<RecordType>
    <fullName>Building</fullName>
    <active>false</active>
    <description>Permit related to a Building</description>
    <label>Building</label>
</RecordType>

force-app/main/default/objects/MUSW__Work_Item__c/MUSW__Work_Item__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Breakdown of work and items on a Permit that impacts the total construction valuation</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Work_Item__c/fields/MUSW__Permit2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Permit2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Permit</label>
    <referenceTo>MUSW__Permit2__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Work_Item__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Living Space</fullName>
            </value>
            <value>
                <fullName>Deck</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Work_Item__c/recordTypes/Building.recordType-meta.xml
<RecordType>
    <fullName>Building</fullName>
    <active>true</active>
    <label>Building</label>
</RecordType>

force-app/main/default/globalValueSets/Avo_Planning_Application_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Variance</fullName>
    </customValue>
    <customValue>
        <fullName>Development Permit</fullName>
    </customValue>
    <masterLabel>Avo Planning Application Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Avo_Type_of_Construction.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>IB</fullName>
    </customValue>
    <customValue>
        <fullName>IIA</fullName>
    </customValue>
    <customValue>
        <fullName>IIB</fullName>
    </customValue>
    <customValue>
        <fullName>IIIA</fullName>
    </customValue>
    <customValue>
        <fullName>IIIB</fullName>
    </customValue>
    <customValue>
        <fullName>IV</fullName>
    </customValue>
    <customValue>
        <fullName>VA</fullName>
    </customValue>
    <customValue>
        <fullName>VB</fullName>
    </customValue>
    <masterLabel>Type of Construction</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/AVO_Withdrawal_Permit_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Groundwater</fullName>
    </customValue>
    <customValue>
        <fullName>Surface Water</fullName>
    </customValue>
    <customValue>
        <fullName>Well to Pond</fullName>
    </customValue>
    <customValue>
        <fullName>Undocumented Source</fullName>
        <isActive>false</isActive>
        <label>Undocumented Source</label>
    </customValue>
    <masterLabel>AVO Withdrawal Permit Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AvoFeeDataRetrieverController.cls
public class AvoFeeDataRetrieverController {
 // Method that returns the supported fee types for a specific Record ID.
    // The return value should be in a CSV format for multiple fee types
    @AuraEnabled
    public static String getAllowedFeeTypes(Id recordId, String sObjectName) {   
        String response = '';
        ResponseJSONWrapper wrapper = new ResponseJSONWrapper();
        List<MUSW__Master_Fee_List__c> feeTypes;
       
        Decimal criteria = 0;

        // step 1 - get a list of allowed fee types
        if(sObjectName == 'MUSW__Permit2__c') {
            // get the Permit Type and Id
            MUSW__Permit2__c permit = [
                SELECT Id, MUSW__Type__c,
                Avo_Estimated_Cost__c,
                Avo_Value_of_Sign__c,
                Avo_Type_Construction__c,
                Avo_Proposed_Occupancy__c,
                Avo_Fee_Calculation__c
                FROM MUSW__Permit2__c
                WHERE Id = :recordId
            ];

            String permitType = permit.MUSW__Type__c;
         
            criteria =  getCriteriaForTieredCalculation(sObjectName, permit, null);
           // system.debug('first'+criteria);

            // Get the Master Fee List items that include the Permit Type
            feeTypes = [
                SELECT Name, Id,
                Flat_Amount__c,
                High_Tier_Limit__c,
                Low_Tier_Limit__c,
                Fee_Calculation_Type__c
                FROM MUSW__Master_Fee_List__c 
                WHERE Avo_Permit_Type__c includes (:permitType)
                AND Active__c = true
                AND Manual_Creation_Allowed__c = true 
                AND Fee_Calculation_Type__c != 'Work Item Based'
                ORDER BY Name ASC 
            ];
        } 
        
       /* else if (sObjectName == 'MUSW__Application2__c') {
            // get the Application Type and Id
            MUSW__Application2__c application = [
                SELECT Id, MUSW__Type__c, Avo_Gross_Sq_Ft_of_Building_Construction__c
                FROM MUSW__Application2__c
                WHERE Id = :recordId
            ];

            String applicationType = application.MUSW__Type__c;

            criteria =  getCriteriaForTieredCalculation(sObjectName, null, application);

            // Get the Master Fee List items that include the Application Type
            feeTypes = [
                SELECT Name, Id,
                Flat_Amount__c,
                High_Tier_Limit__c, 
                Low_Tier_Limit__c,
                Fee_Calculation_Type__c
                FROM MUSW__Master_Fee_List__c 
                WHERE Avo_Planning_Application_Type__c includes (:applicationType)
                AND Active__c = true
                AND Manual_Creation_Allowed__c = true                
                AND Fee_Calculation_Type__c != 'Work Item Based'
                ORDER BY Name ASC 
            ];
        } */
        

        wrapper.id = recordId;
        wrapper.feeTypeList = new List<Option>();

        for(MUSW__Master_Fee_List__c feeType:feeTypes)
        {
            Option option = new Option();

            option.label = feeType.Name;
            option.value = feeType.Id;
            //Code updated by Siri due to facing issuess on 31-03-22
              option.flatamount=0;
           option.higeramount=0;
            option.lowamount=0;
            if (feeType.Flat_Amount__c!=null)
            {
                option.flatamount=feeType.Flat_Amount__c;
            }
            if (feeType.High_Tier_Limit__c!=null)
            {
                option.flatamount=feeType.High_Tier_Limit__c;
            }
            if (feeType.Low_Tier_Limit__c!=null)
            {
                option.flatamount=feeType.Low_Tier_Limit__c;
            }
          
            //end changes.
             //comented by siri for tiered free calculation type on 02-04-22(for avoiding estimated cost)
          /* if (feeType.Fee_Calculation_Type__c == 'Tiered') {

                system.debug('criteria12'+matchTieredCondition(sObjectName, criteria, feeType));
                if (matchTieredCondition(sObjectName, criteria, feeType)) {
                    wrapper.feeTypeList.Add(option);
                }
           } else {
               wrapper.feeTypeList.Add(option);   
           }*/
            //end
               wrapper.feeTypeList.Add(option);  
        }
        response = JSON.serialize(wrapper);

        return response;
    }  
   //Code updated by Siri due to facing issuess on 31-03-22
    @AuraEnabled
    public static  List<MUSW__Master_Fee_List__c> getfeetypedata(Id recordId)
    {
        List<MUSW__Master_Fee_List__c> feeTypes1;
        feeTypes1 = [
                SELECT Name, Id,
                Fee_Calculation_Type__c,
                Flat_Amount__c,
                High_Tier_Limit__c,
                Low_Tier_Limit__c
                FROM MUSW__Master_Fee_List__c 
                WHERE Id=:recordId
            ];
        return feeTypes1;
    }
    //end changes.

    @AuraEnabled
    // Helper function used to determine the record type of the fee being created. The return record type will determine a different layout and dropdown listbox values for the fee to be created
    public static Id getFeeRecordTypeId(String recordType) {

      
        try {
            Id recordTypeId = Schema.SObjectType.MUSW__Fee__c.getRecordTypeInfosByName().get(recordType).getRecordTypeId();
                
            return recordTypeId;
        } catch (Exception ex) {
            System.Debug('Failed to retrieve fee record type: ' + recordType);
            return Schema.SObjectType.MUSW__Fee__c.getRecordTypeInfosByName().get('Avo Fee Default').getRecordTypeId();
        }
    }

    @AuraEnabled
    // Helper function used to get the Master Fee List item's Amount Value and convert it to an Integer
    public static List<MUSW__Master_Fee_List__c> getFeeListInformation(List<String> masterFeeListIds) {
        
        List<MUSW__Master_Fee_List__c> fees = [
            SELECT Base__c, 
            High_Tier_Limit__c,
            Low_Tier_Limit__c,
            Fee_Calculation_Type__c,
            Multiplier__c,
            Flat_Amount__c,
            Name,
            Record_Type__c,
            Related_Work_Item__r.Name,
            RecordTypeId,
            GL_Account__c
            FROM MUSW__Master_Fee_List__c
            WHERE Id = :masterFeeListIds
        ];
        return fees;
    }
    
    @AuraEnabled
    // Method used to create the selected Fee record
    public static Id createFee(Integer quantity, String recordId, String masterFeeListId, String sObjectName) {
        System.debug('quantity' +quantity);
        System.debug('recordId' +recordId);
        System.debug('masterFeeListId' +masterFeeListId);
        System.debug('sObjectName' +sObjectName);
        MUSW__Fee__c fee = new MUSW__Fee__c();
        Id convertedId = Id.valueOf(recordId);

        List<String> ids = new List<String>();
        ids.add(masterFeeListId);

        List<Integer> quantities = new List<Integer>();
        quantities.add(quantity);
        system.debug('quantities >>>' +quantities);
        system.debug('recordId >>>' +recordId);
        system.debug('ids >>>' +ids);
        system.debug('sObjectName >>>' +sObjectName);
        return createMultipleFees(quantities, recordId, ids, sObjectName);
    }

    @AuraEnabled
    // Method used to create the selected Fee record
    public static Id createMultipleFees(List<Integer> quantities, String recordId, List<String> masterFeeListIds, String sObjectName) {
        system.debug('Values are >>>> '+quantities+'-----'+recordId+'----'+masterFeeListIds+'-----'+sObjectName);
        Id returnId;
        List<MUSW__Fee__c> fees = new List<MUSW__Fee__c>();
        Id convertedId = Id.valueOf(recordId);
        system.debug('get record id'+recordId);
        system.debug('get id'+convertedId);

        List<MUSW__Master_Fee_List__c> selectedFees = getFeeListInformation(masterFeeListIds);
        List<MUSW__Work_Item__c> relatedWorkItems = new   List<MUSW__Work_Item__c>();
        system.debug('selectedFees'+selectedFees);
        if(sObjectName == 'MUSW__Permit2__c') { 
            relatedWorkItems = [
                SELECT Id, MUSW__Description__c, MUSW__Quantity__c, MUSW__Value_Per_Unit__c
                FROM MUSW__Work_Item__c
                WHERE MUSW__Permit2__c = :recordId
            ];
        system.debug('relatedWorkItems >>>>1' + relatedWorkItems);
        }
        system.debug('relatedWorkItems >>>>2' + relatedWorkItems);
       
        Integer index = 0;
        Integer quantity = 1;
        for(MUSW__Master_Fee_List__c fee : selectedFees) {
            quantity = quantities[index];
            System.debug('fee to create: ' + fee.Name + ' quantity: ' + quantity);
            
            index++;
            Decimal feeCalculation = 0; 
            //comented by siri for tiered free calculation type on 02-04-22(for avoiding estimated cost)
           /* if (fee.Fee_Calculation_Type__c == 'Tiered') {
                feeCalculation = 0;
            }*/
            //end
            
            if (fee.Fee_Calculation_Type__c == 'Work Item Based') {

                    system.debug('relatedWorkItems >>>> '+relatedWorkItems);
                    for(MUSW__Work_Item__c workItem: relatedWorkItems) {
                       if (fee.Related_Work_Item__r.Name == workItem.MUSW__Description__c) {
                            feeCalculation = workItem.MUSW__Value_Per_Unit__c * quantity;
                           
                       }else{
                           feeCalculation =0;
                       }
                    } 
              }
            else {

                if (fee.Flat_Amount__c != null) {
                    feeCalculation = fee.Flat_Amount__c * quantity;
                } else if (fee.Base__c != null) {
                    feeCalculation = fee.Base__c * quantity;
                }

            }

            if(sObjectName == 'MUSW__Permit2__c') {
                MUSW__Permit2__c permit = [
                    SELECT MUSW__Type__c,
                    Avo_Estimated_Cost__c,
                    Avo_Value_of_Sign__c,
                    Avo_Type_Construction__c,
                    Avo_Proposed_Occupancy__c,
                    Avo_Fee_Calculation__c,
                    L_F_Water_Main__c,
                    L_F_Sanitary_Sewer_Main__c
                    FROM MUSW__Permit2__c 
                    WHERE Id = :recordId
                ];

    //comented by siri for tiered free calculation type on 02-04-22(for avoiding estimated cost)
            /*    if (fee.Fee_Calculation_Type__c == 'Tiered') {

                    Decimal cost = getCriteriaForTieredCalculation(sObjectName, permit, null);

                    if (!matchTieredCondition(sObjectName, cost, fee)) {
                        continue;
                    }

                    feeCalculation = calculateTieredFee(sObjectName, cost, fee) * quantity;
                }*/ 
                //end
                //code add by siri for tiered free calculation as low tiered value
                if (fee.Fee_Calculation_Type__c == 'Tiered') {
                    
                     feeCalculation=(fee.Low_Tier_Limit__c) * quantity; 
                    
                }
                //end
               

                
                if (fee.Fee_Calculation_Type__c == 'Work Item Based') {
                    if (fee.Related_Work_Item__r.Name == null) {
                        feeCalculation = calculateCombinedWorkItemFee(permit, fee, relatedWorkItems);
                    } 
                }

                feeCalculation = handlePermitFeeSpecialCases(permit, fee, feeCalculation);
               Id recordTypeId = Schema.SObjectType.MUSW__Fee__c.getRecordTypeInfosByName().get('All').getRecordTypeId();
                MUSW__Fee__c newFee = new MUSW__Fee__c();
                   newFee.MUSW__Quantity__c         = quantity;
                    newFee.MUSW__Amount__c           = feeCalculation;
                    newFee.Master_Fee_List__c         = fee.Id;
                    newFee.RecordTypeId              = recordTypeId;
                    newFee.MUSW__Type__c             = fee.Name;
                    newFee.MUSW__Permit2__c          = convertedId;
                    newFee.Avo_GL_Account__c = fee.GL_Account__c;
                
                system.debug('newFee >>>>>' +newFee);
                fees.add(newFee);
                
            }
           //  return returnId;
          /*  if (sObjectName == 'MUSW__Application2__c') {
                MUSW__Application2__c application = [
                    SELECT MUSW__Type__c,
                    Avo_Number_of_Lots_in_Development__c,
                    Avo_Gross_Sq_Ft_of_Building_Construction__c,
                    Avo_Number_of_New_Lots__c,
                    Avo_Number_of_Lots__c
                    FROM MUSW__Application2__c 
                    WHERE Id = :recordId
                ];
                System.debug('name : ' + fee.Name);
               
               feeCalculation = handleApplicationFeeSpecialCases(application, fee, feeCalculation);
      //comented by siri for tiered free calculation type on 02-04-22(for avoiding estimated cost)           
             /*   if (fee.Fee_Calculation_Type__c == 'Tiered') {

                    Decimal cost = getCriteriaForTieredCalculation(sObjectName, null, application);

                    if (!matchTieredCondition(sObjectName, cost, fee)) {
                        continue;
                    }

                    feeCalculation = calculateTieredFee(sObjectName, cost, fee) * quantity;
                }
                //end
    
                MUSW__Fee__c newFee = new MUSW__Fee__c(
                    MUSW__Quantity__c        = quantity,
                    MUSW__Amount__c          = feeCalculation,
                  //  RecordTypeId             = fee.RecordTypeId,
                    MUSW__Type__c            = fee.Name,
                    MUSW__Application2__c    = convertedId,
                    Avo_GL_Account__c = fee.GL_Account__c
                );
                fees.add(newFee);
            } */
    
        }
       
       insert fees;
       
        // Return the selected Fee ID
        return fees.size() > 0 ? fees[0].id : recordId;
    }


    @AuraEnabled
    public static Decimal getCriteriaForTieredCalculation(String sObjectName, MUSW__Permit2__c permit, MUSW__Application2__c application) {
        if(sObjectName == 'MUSW__Permit2__c' ) {
            if (permit.MUSW__Type__c == 'Temporary Park Access Permit' ||
            (permit.MUSW__Type__c == 'Amendment or Extension of TPA' 
            && permit.Avo_Fee_Calculation__c == 'Estimated Value'
            || permit.Avo_Fee_Calculation__c == null
            ) ||
            (permit.MUSW__Type__c == 'Good Neighbor Access Permit' 
            && permit.Avo_Fee_Calculation__c == 'Estimated Value'
            || permit.Avo_Fee_Calculation__c == null
            )
            ) 
            {
                return  permit.Avo_Estimated_Cost__c;
            } 
    
          /*  if (permit.MUSW__Type__c == 'Sign Permit') {
                return permit.Avo_Value_of_Sign__c;
            }*/

         /*  if ((permit.MUSW__Type__c == 'Manufactured Home Permit' 
            || permit.MUSW__Type__c == 'Residential Building Permit') && permit.Avo_Fee_Calculation__c == 'Valuation') {

                List<string> applicableItems = new List<string>();

                if (permit.MUSW__Type__c == 'Manufactured Home Permit' ) {
                    applicableItems.add('Front Porch');
                    applicableItems.add('Landings/Porches/Decks - Front');
                    applicableItems.add('Landings/Porches/Decks - Rear');
                    applicableItems.add('Rear Porch');
                } else if (permit.MUSW__Type__c == 'Residential Building Permit') {
                    applicableItems.add('New/Proposed Carport/Garage');
                    applicableItems.add('New/Proposed Heated Areas');
                    applicableItems.add('New/Proposed Heated Basement');
                    applicableItems.add('New/Proposed Porch (Porch has a roof)');
                }
               
                System.debug('permit proposed occupancy: ' + permit.Avo_Proposed_Occupancy__c);
                System.debug('permit type of construction: ' + permit.Avo_Type_Construction__c);
                
                AggregateResult[] totalSqft = [
                    SELECT SUM(MUSW__Quantity__c)totalSqft
                    FROM MUSW__Work_Item__c
                    WHERE MUSW__Permit2__c = :permit.id 
                    AND MUSW__Description__c in :applicableItems
                ];

                List<MUSW__Master_Valuation_List__c> factors = [
                    SELECT Id, Use_Group__c, IA__c,
                    IB__c,
                    IIA__c,
                    IIB__c,
                    IIIA__c,
                    IIIB__c,
                    IV__c,
                    VA__c,
                    VB__c
                    FROM MUSW__Master_Valuation_List__c
                    WHERE Use_Group__c = :permit.Avo_Proposed_Occupancy__c
                    AND Avo_Active__c = true
                ];

                if (factors.size() > 0 && totalSqft.size() > 0) {
                    
                    Decimal sumAmount = (Decimal) totalSqft[0].get('totalSqft');
                    Decimal valuationFactor = (Decimal) factors[0].get(permit.Avo_Type_Construction__c + '__c');
                    System.debug('total: ' + sumAmount );
                    System.debug(' factor ' + valuationFactor);

                    if (sumAmount == null || valuationFactor == null)
                    {
                        return 0;
                    }

                    return sumAmount * valuationFactor;
                } else {
                    return 0;
                }

            }*/


        } 

       /* if (sObjectName == 'MUSW__Application2__c') {
            if (application.MUSW__Type__c == 'Plans Review') 
            {
                return  application.Avo_Gross_Sq_Ft_of_Building_Construction__c;
            } 
        }*/

        return 0;
    }

    @AuraEnabled
    public static boolean matchTieredCondition(String sObjectName, Decimal criteria, MUSW__Master_Fee_List__c feeType){

        if (criteria == null)
            criteria = 1;

        if(sObjectName == 'MUSW__Permit2__c' &&
        criteria > feeType.Low_Tier_Limit__c && criteria <= feeType.High_Tier_Limit__c) {
            return true;
        } 

        if (sObjectName == 'MUSW__Application2__c' &&
        criteria > feeType.Low_Tier_Limit__c && criteria <= feeType.High_Tier_Limit__c) {
            return true;
        }

        return false;
    }

    @AuraEnabled
    public static Decimal calculateTieredFee(String sObjectName, Decimal criteria, MUSW__Master_Fee_List__c fee) {
        Decimal result = 0;
        Decimal base = 0;
        Decimal lowerLimit = fee.Low_Tier_Limit__c;
        Decimal multiplier = fee.Multiplier__c;
      //Code updated by Siri due to facing issuess on 24-03-22
        if(criteria== null)
        {
              criteria = 0;
        }
        if(multiplier== null)
        {
              multiplier = 0;
        }
        //end
 
        if (lowerLimit == 0) {
            base = fee.Flat_Amount__c == null ? 0 :  Integer.valueOf( fee.Flat_Amount__c);
            
        } else {
            base = fee.Base__c;
           
        }

        if(sObjectName == 'MUSW__Permit2__c') {
            Decimal overCost = (criteria - lowerLimit) / 1000;
            Long divisionResult = overCost.round(System.RoundingMode.UP);
            
            System.debug('criteria ' + criteria + ' lowerLimit ' + lowerLimit);

            System.debug('base ' + base + ' division result ' + divisionResult + ' multipe: ' + multiplier);
            if(base== null)
        {
              base = 0;
        }
        if(multiplier== null)
        {
              multiplier = 0;
        }
            result = base + divisionResult * multiplier;
        }

        if (sObjectName == 'MUSW__Application2__c') {
            if (fee.Name == 'Fire Marshal Plan Review Submittal Fee') {
                if (lowerLimit == 0) {
                    result = base;
                } else {
                    result = criteria * multiplier;
                }
            }           
        }

        return result;
    }

    @AuraEnabled
    public static Decimal calculateCombinedWorkItemFee(MUSW__Permit2__c permit, MUSW__Master_Fee_List__c masterFee, 
    List <MUSW__Work_Item__c> relatedWorkItems) {
        Decimal result = 0;
    
        Decimal totalQuantity = 0;
        Decimal flatAmount = 0;

        for(MUSW__Work_Item__c workItem: relatedWorkItems) {
            totalQuantity += workItem.MUSW__Quantity__c == null ? 1 : workItem.MUSW__Quantity__c;
        }
        
        flatAmount = masterFee.Flat_Amount__c == null ? 0 : masterFee.Flat_Amount__c;
        
        result = totalQuantity * flatAmount;
           
        return result;
    }

    @AuraEnabled
    public static Decimal handlePermitFeeSpecialCases(MUSW__Permit2__c permit, MUSW__Master_Fee_List__c fee, Decimal originAmount) {
        Decimal feeCalculation = 0;
        
        if(fee.Name == 'Inspection Costs for Water' || fee.Name == 'Inspection Costs for Sanitary Sewer'){
            System.debug('PUD Fee Special Case');

            Decimal waterMainCost = permit.L_F_Water_Main__c == null ? 0 : permit.L_F_Water_Main__c;
            Decimal sanitaryMainCost = permit.L_F_Sanitary_Sewer_Main__c == null ? 0 : permit.L_F_Sanitary_Sewer_Main__c;

            Decimal waterCost = waterMainCost * 0.8;
            Decimal mainCost =  sanitaryMainCost * 1.85;
            Decimal totalCost = waterCost + mainCost;
          
            if (totalCost < 250)
            {
                totalCost = 250;
                Decimal waterNumber = permit.L_F_Water_Main__c == null || permit.L_F_Water_Main__c == 0 ? 1 : permit.L_F_Water_Main__c;
                Decimal mainNumber = permit.L_F_Sanitary_Sewer_Main__c == null || permit.L_F_Sanitary_Sewer_Main__c == 0 ? 1 : permit.L_F_Sanitary_Sewer_Main__c;
                Decimal totalNumber = waterNumber + mainNumber;

                if (fee.Name == 'Inspection Costs for Water') {
                    Decimal prorateCost = (totalCost - waterCost - mainCost) * waterNumber / totalNumber;
                    feeCalculation = waterCost + prorateCost.setScale(1, System.RoundingMode.CEILING);

                    System.debug('Rate cost: ' + prorateCost + ' cost ' + waterCost);
                }

                if (fee.Name == 'Inspection Costs for Sanitary Sewer') {
                    Decimal prorateCost = (totalCost - waterCost - mainCost) * mainNumber / totalNumber;
                    feeCalculation = mainCost + prorateCost.setScale(1, System.RoundingMode.FLOOR);

                    System.debug('Rate cost: ' + prorateCost + ' cost ' + mainCost);
                }

            } else {
                if (fee.Name == 'Inspection Costs for Water') {
                    feeCalculation = waterCost;
                }

                if (fee.Name == 'Inspection Costs for Sanitary Sewer') {
                    feeCalculation = mainCost;
                }
                
            }        
        } else {
            feeCalculation = originAmount;
        }

        return feeCalculation;
    }
    
    @AuraEnabled
    public static Decimal handleApplicationFeeSpecialCases(MUSW__Application2__c application, MUSW__Master_Fee_List__c fee, Decimal originAmount) {
        Decimal feeCalculation = 0;
        
        if(fee.Name == 'Preliminary Plat Lot Fee'){
            System.debug('Prelim Plat fee lot:' + application.Avo_Number_of_Lots__c);
            if(application.Avo_Number_of_Lots__c == null){
                feeCalculation = 0;
            }
            else{

                feeCalculation = 10 * application.Avo_Number_of_Lots__c;
            }
        } else if(fee.Name == 'Final Plat Lot Fee'){
            System.debug('Final Plat fee');
            if(application.Avo_Number_of_New_Lots__c == null){
                feeCalculation = 0;
            }
            else{

                feeCalculation = 30 * application.Avo_Number_of_New_Lots__c;

                if (feeCalculation >= 500) 
                {
                    feeCalculation = 500;
                }
            }
        } else {
            feeCalculation = originAmount;
        }

        return feeCalculation;
    }

    
    // Response JSON Wrapper Class
    public class ResponseJSONWrapper {
        public Id id;
        public List<Option> feeTypeList;
    }

    // Object used to hold label and Id value for the fees.
    public class Option {
        public String label;
        public String value;
        public Decimal flatamount;
        public Decimal higeramount;
        public Decimal lowamount;
        
    }
}