force-app/main/default/objects/Master_Review_List__c/Master_Review_List__c.object-meta.xml
<CustomObject>
    <label>Master Review List</label>
    <nameField>
        <label>Master Review List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Review Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Review_List__c/fields/Avo_Offset__c.field-meta.xml
<CustomField>
    <fullName>Avo_Offset__c</fullName>
    <label>Offset</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Review_List__c/fields/Avo_Offset_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Offset_Type__c</fullName>
    <label>Offset Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business Days</fullName>
            </value>
            <value>
                <fullName>Calendar Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Review_List__c/fields/Avo_Permit_Type__c.field-meta.xml
<CustomField>
    <fullName>Avo_Permit_Type__c</fullName>
    <label>Permit Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Avo_Permit_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Review_List__c/fields/Manual_Creation_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Manual_Creation_Allowed__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Manual Creation Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Master_Review_List__c/fields/Owner_Queue_User__c.field-meta.xml
<CustomField>
    <fullName>Owner_Queue_User__c</fullName>
    <label>Owner (Queue/User)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Master_Review_List__c/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <label>Record Type</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Applicant__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Contact applicant associated with the application.</description>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications as Applicant</relationshipLabel>
    <relationshipName>Application2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <label>Type (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Variance</fullName>
            </value>
            <value>
                <fullName>Development Permit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/MUSW__Permit2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Permit application details</description>
    <label>Permit</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Permit2__c/fields/AVO_Permit_Type__c.field-meta.xml
<CustomField>
    <fullName>AVO_Permit_Type__c</fullName>
    <label>Permit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AVO_Withdrawal_Permit_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Applicant__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The applicant submitting the permit application.</description>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Permits as Applicant</relationshipLabel>
    <relationshipName>Applicant_Permit2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <description>The permit type. This is typically related to the record type.</description>
    <label>Type (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agricultural Surface Water Pump</fullName>
            </value>
            <value>
                <fullName>Agricultural Water Withdrawal Application</fullName>
            </value>
            <value>
                <fullName>Agricultural Water Withdrawal Permit</fullName>
            </value>
            <value>
                <fullName>Agricultural Well Pump</fullName>
            </value>
            <value>
                <fullName>Application for Permit Consolidation</fullName>
            </value>
            <value>
                <fullName>Revision</fullName>
            </value>
            <value>
                <fullName>Permit Relinquishment</fullName>
            </value>
            <value>
                <fullName>Well and Pump Data</fullName>
            </value>
            <value>
                <fullName>Well Plug and Abandonment</fullName>
            </value>
            <value>
                <fullName>AG Water Metering Installation</fullName>
            </value>
            <value>
                <fullName>Undocumented Source</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Review__c/MUSW__Review__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Tracks the collaborative plan review process and associated documents</description>
    <label>Review</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Review__c/fields/MUSW__Application2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Application2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Review__c/fields/MUSW__Due_Date__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Due_Date__c</fullName>
    <description>Due date for completion of the review.</description>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MUSW__Review__c/fields/MUSW__Permit2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Permit2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Permit</label>
    <referenceTo>MUSW__Permit2__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Review__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AG Program Manager Review</fullName>
                <label>Step 1 - AG Program Manager Approval</label>
            </value>
            <value>
                <fullName>Director Office Review</fullName>
            </value>
            <value>
                <fullName>Evaluation of Withdrawal 1st Cut</fullName>
            </value>
            <value>
                <fullName>Evaluation of Withdrawal 2nd Cut</fullName>
            </value>
            <value>
                <fullName>Irrigation Efficiency Cert Review</fullName>
            </value>
            <value>
                <fullName>Low Flow Protection Plan Review</fullName>
            </value>
            <value>
                <fullName>Special Appraisal</fullName>
            </value>
            <value>
                <fullName>Water Conservation Plan Review</fullName>
            </value>
            <value>
                <fullName>Water Reuse Visibility Study Review</fullName>
            </value>
            <value>
                <fullName>Water Shed Manager Review</fullName>
                <label>Step 3 - Water Shed Manager Approval</label>
            </value>
            <value>
                <fullName>Water Supply Manager Review</fullName>
                <label>Step 2 - Water Supply Manager Approval</label>
            </value>
            <value>
                <fullName>Well Data Form Review</fullName>
            </value>
            <value>
                <fullName>Completeness Review</fullName>
            </value>
            <value>
                <fullName>Waiver Review</fullName>
            </value>
            <value>
                <fullName>Withdrawal LOC Review</fullName>
            </value>
            <value>
                <fullName>Form Assessment Review</fullName>
            </value>
            <value>
                <fullName>Final Evaluation Review</fullName>
            </value>
            <value>
                <fullName>Meter Installation Review</fullName>
            </value>
            <value>
                <fullName>Requester Review</fullName>
            </value>
            <value>
                <fullName>Permitting Review</fullName>
            </value>
            <value>
                <fullName>Compliance Review</fullName>
            </value>
            <value>
                <fullName>Metering Review</fullName>
            </value>
            <value>
                <fullName>WWSA Review</fullName>
            </value>
            <value>
                <fullName>GIS Review</fullName>
            </value>
            <value>
                <fullName>Meter Review</fullName>
            </value>
            <value>
                <fullName>Step 5 - Director Approval</fullName>
            </value>
            <value>
                <fullName>Permit Management Review</fullName>
            </value>
            <value>
                <fullName>Step 4 - Deputy Director Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Avo_Permit_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agricultural Water Withdrawal Application</fullName>
    </customValue>
    <customValue>
        <fullName>Agricultural Water Withdrawal Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Application for Permit Consolidation</fullName>
    </customValue>
    <customValue>
        <fullName>Revision</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation Request</fullName>
    </customValue>
    <customValue>
        <fullName>Permit Relinquishment</fullName>
    </customValue>
    <customValue>
        <fullName>Well and Pump Data</fullName>
    </customValue>
    <customValue>
        <fullName>Well Plug &amp; Abandonment</fullName>
    </customValue>
    <customValue>
        <fullName>AG Water Metering Installation</fullName>
    </customValue>
    <masterLabel>Avo Permit Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/AVO_Withdrawal_Permit_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Groundwater</fullName>
    </customValue>
    <customValue>
        <fullName>Surface Water</fullName>
    </customValue>
    <customValue>
        <fullName>Well to Pond</fullName>
    </customValue>
    <customValue>
        <fullName>Undocumented Source</fullName>
        <isActive>false</isActive>
        <label>Undocumented Source</label>
    </customValue>
    <masterLabel>AVO Withdrawal Permit Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AvoReviewDataRetrieverController.cls
/**
* Apex Controller used in accnewReviewController.js. Makes calls to GET and POST data for Review Objects.
* @author Michael Chung
* last modified by Michael Chung
* @date 05/13/2021
* 
*/
public class AvoReviewDataRetrieverController {
    // Method that returns the supported review types for a specific Record ID.
    // The return value should be in a CSV format for multiple review types
    @AuraEnabled
    public static String getAllowedReviewTypes(Id recordId, String sObjectName) {   
        String response = '';
        ResponseJSONWrapper wrapper = new ResponseJSONWrapper();
        List<Master_Review_List__c> reviewTypes;
 
        // step 1 - get a list of allowed review types
        if(sObjectName == 'MUSW__Permit2__c') {
            // get the Permit Type and Id
            MUSW__Permit2__c permit = [
                SELECT Id, MUSW__Type__c
                FROM MUSW__Permit2__c
                WHERE Id = :recordId
            ];
 
            String permitType = permit.MUSW__Type__c;
 
            // Get the Master Review List items that include the Permit Type
            reviewTypes = [
               SELECT Name, Id 
                FROM Master_Review_List__c 
                WHERE Avo_Permit_Type__c includes (:permitType)
                AND Active__c = true
                AND Manual_Creation_Allowed__c = true 
                ORDER BY Name ASC 
            ];
        }
 
        wrapper.id = recordId;
        wrapper.reviewTypeList = new List<Option>();
 
        for(Master_Review_List__c reviewType:reviewTypes)
        {
            Option option = new Option();
 
            option.label = reviewType.Name;
            option.value = reviewType.Id;
            // Adding Option objects (label & value) into the reviewTypeList
            wrapper.reviewTypeList.Add(option);
        }
        system.debug('get>>'+JSON.serialize(wrapper));
        response = JSON.serialize(wrapper);

 
        return response;
    }   
 
    @AuraEnabled
    // Helper function used to determine the record type of the review being created. The return record type will determine a different layout and dropdown listbox values for the review to be created
    public static Id getReviewRecordTypeId(String recordType) {
 
        try {
            Id recordTypeId = Schema.SObjectType.MUSW__Review__c.getRecordTypeInfosByName().get(recordType).getRecordTypeId();
            return recordTypeId;    
        } catch (Exception ex) {
            return  Schema.SObjectType.MUSW__Review__c.getRecordTypeInfosByName().get('AVO Review Default').getRecordTypeId();
        }
    }
 
 
    @AuraEnabled
    // Helper function used to get the Master Review List item's name based off of the Master Review List ID
    public static List<Master_Review_List__c> getMasterListInfo(List<String> ids) {
        List<Master_Review_List__c> result = [
            SELECT Name,Record_Type_ID__c,Record_Type__c, Owner_Queue_User__c, Avo_Offset__c, Avo_Offset_Type__c
            FROM Master_Review_List__c
            WHERE Id = :ids
        ];
   system.debug('re' +result);
        return result;
    }
 
    @AuraEnabled
    // Method used to create 1 or more Reviews
    public static Id createReviews(String recordId, List<String> masterReviewListIds, String sObjectName) {
        List<MUSW__Review__c> reviews = new List<MUSW__Review__c>();
        Id convertedId = Id.valueOf(recordId);
 
        List<Master_Review_List__c> selectedReviews = getMasterListInfo(masterReviewListIds);
 
        if(sObjectName == 'MUSW__Permit2__c') {
            MUSW__Permit2__c permit = [
                SELECT MUSW__Type__c, MUSW__Applicant__c
                FROM MUSW__Permit2__c 
                WHERE Id = :recordId
            ];
            // Create review object(s) to then insert it into the DB
            for(Master_Review_List__c selectedReview : selectedReviews) {
              Id recordTypeId =                 getReviewRecordTypeId(selectedReview.Record_Type__c);
              Date dueDate = Date.today();
              Integer offset =  selectedReview.Avo_Offset__c == null? 0 :  Integer.valueOf(selectedReview.Avo_Offset__c);
 
              if (selectedReview.Avo_Offset_Type__c == 'Business Days') {
                  dueDate = AvoCommon.AddBusinessDays(date.today(), offset);
              } else {
                  dueDate = dueDate.addDays( offset);
              }
 
                MUSW__Review__c review = new MUSW__Review__c(
                   RecordTypeId        = recordTypeId,
                    MUSW__Type__c  = selectedReview.Name,
                    MUSW__Permit2__c    = convertedId,
                    MUSW__Due_Date__c = dueDate
                );
                System.Debug('Start Creating Reviews1');
                AssignQueueOwner(selectedReview, review);
                reviews.add(review);
            }
            insert reviews;
        }
		
        if (sObjectName == 'MUSW__Application2__c') {
            MUSW__Application2__c application = [
                SELECT MUSW__Type__c 
                FROM MUSW__Application2__c 
                WHERE Id = :recordId
            ];
 
 
            // Create review object(s) to then insert it into the DB
            for(Master_Review_List__c selectedReview : selectedReviews) {
                Id recordTypeId =
                getReviewRecordTypeId(selectedReview.Record_Type__c) ;
                Date dueDate = Date.today();
                Integer offset =  selectedReview.Avo_Offset__c == null? 0 :  Integer.valueOf(selectedReview.Avo_Offset__c);
 
                if (selectedReview.Avo_Offset_Type__c == 'Business Days') {
                    dueDate = AvoCommon.AddBusinessDays(date.today(), offset);
                } else {
                    dueDate = dueDate.addDays( offset);
                }
 
 
                MUSW__Review__c review = new MUSW__Review__c(
                    RecordTypeId        = recordTypeId,
                    MUSW__Type__c  = selectedReview.Name,
                    MUSW__Application2__c    = convertedId,
                    MUSW__Due_Date__c = dueDate
                );
 
                
                if (selectedReview.Owner_Queue_User__c != null) {
                    List<Group> queues = [select Id, Name from Group where Type = 'Queue' and Name =:selectedReview.Owner_Queue_User__c];
                    if (queues.size() > 0) {
                        review.OwnerId = queues[0].Id;
                    }
                }
 
 
                reviews.add(review);
            }
            insert reviews;
        }
		
        // Return the first ID in the reviews. This works if 1 or more reviews are added.
        return reviews[0].id;   
    }
 
    @AuraEnabled
    public static void AssignQueueOwner(Master_Review_List__c selectedReview, MUSW__Review__c review) {
        System.Debug('Owner Queue---- ' + selectedReview.Owner_Queue_User__c);
        if (selectedReview.Owner_Queue_User__c != null) {
            List<Group> queues = [select Id, Name from Group where Type = 'Queue' and Name =:selectedReview.Owner_Queue_User__c];
 
            System.Debug('Finding Queue');
            if (queues.size() > 0) {
                System.Debug('Assign Queue');
                review.OwnerId = queues[0].Id;
            }
    	}
    }
    // Response JSON Wrapper Class
    public class ResponseJSONWrapper {
        public Id id;
        public List<Option> reviewTypeList;
    }
 
    // Object used to hold label and Id value for the reviews.
    public class Option {
        public String label;
        public String value;
    }
}