force-app/main/default/objects/MUSW__EventLog__c/MUSW__EventLog__c.object-meta.xml
<CustomObject>
    <description>This object is used to log the event for each action of users.</description>
    <label>Event Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__EventLog__c/fields/MUSW__Message__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Message__c</fullName>
    <description>This is used to show the message of logging.</description>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__EventLog__c/fields/MUSW__MessageLong__c.field-meta.xml
<CustomField>
    <fullName>MUSW__MessageLong__c</fullName>
    <label>Detailed Message</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MUSW__EventLog__c/fields/MUSW__Record_ID__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Record_ID__c</fullName>
    <description>The &apos;Related Record ID&apos; field represents the unique identifier of a record associated with this event log entry. It helps establish connections between event logs and specific records, making it easier to trace events back to their originating source. This field plays a vital role in simplifying the debugging process and providing essential context for event log analysis.</description>
    <label>Related Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__EventLog__c/fields/MUSW__Severity__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Severity__c</fullName>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>INFO</fullName>
                <default>true</default>
                <label>INFO</label>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__EventLog__c/fields/MUSW__Time_Stamp__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Time_Stamp__c</fullName>
    <description>This field is used to record the ending date and time of the event or workflow action that triggered the creation of an Event Log.</description>
    <label>End Time Stamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MUSW__EventLog__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GENERAL</fullName>
                <default>true</default>
                <label>GENERAL</label>
            </value>
            <value>
                <fullName>SOQL</fullName>
            </value>
            <value>
                <fullName>SOSL</fullName>
            </value>
            <value>
                <fullName>DML</fullName>
            </value>
            <value>
                <fullName>EMAIL</fullName>
            </value>
            <value>
                <fullName>WEBSERVICES</fullName>
            </value>
            <value>
                <fullName>EXCEPTION</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__EventLog__c/fields/MUSW__User__c.field-meta.xml
<CustomField>
    <fullName>MUSW__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Event_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AvoDataMigrationQueueable.cls
public class AvoDataMigrationQueueable implements Queueable {

    private string sObjectName;
    public AvoDataMigrationQueueable(string sObjectName) {
        this.sObjectName = sObjectName;
    }

    public void execute(QueueableContext context) {

        // this will update all records from the sObjectName without a value in the AVO_GUID__c field;
        try {
            AvoDataMigration.updateGuid(this.sObjectName);
        } catch (Exception e) {
            system.debug(this.sObjectName);
            log('GUID update failed -' + sObjectName, e.getMessage() + '\r\n' + e.getStackTraceString(), 'ERROR', null );
        } finally {
        }
    }

    private void log(string message, string details, string type, Id recordId) { 
        MUSW__EventLog__c eventLog = new MUSW__EventLog__c();
        
        if (type == 'ERROR') {
            eventLog.MUSW__Type__c = 'EXCEPTION';
            eventLog.MUSW__Severity__c = 'ERROR';
        } else {
            eventLog.MUSW__Type__c = 'GENERAL';
            eventLog.MUSW__Severity__c = 'INFO';
        }

        eventLog.MUSW__Message__c = message;
        eventLog.MUSW__MessageLong__c = details;
        eventLog.MUSW__User__c = UserInfo.getUserId();
        eventlog.MUSW__Time_Stamp__c = System.now();
        if (recordId !=null){
            eventLog.MUSW__Record_ID__c = recordId;
        }
        Insert eventLog;
    }
}